supermicro/x10sll-f.nix
This adds necessary kernel modules to control IPMI and hardware random generator from TPM. I also have a watchdog module enabled, but here it is commented because enabling it by default is not a good idea IMO. I left it as an example, however.
=> supermicro/x10sll-f: init

dell/xps-15-9550.nix
Now that libinput builds and has proper nixos-module support on nixos-unstable.
=> Dell XPS 9550: Better to use libinput than synaptics

lenovo/x220i-tablet.nix
Here's a patch that shows how to add support for
- TrackPoint
- (alternatively) better touchpad support
- volume/mute buttons
- active hard-drive protection
- fingerprint reader
I've been using these options for a couple of days on a non-tablet X220i. See https://github.com/dancek/dotfiles/blob/master/nixos/thinkpad-x220i/configuration.nix
=> Thinkpad X220i: configure more hardware

raspberry_pi/rpi2.nix
See discussion at https://github.com/NixOS/nixpkgs/issues/24170
=> rpi2.nix: pkgs.platforms.raspberrypi2 is no longer correct

apple/macbook-pro-10-1.nix, dell/xps-15-9550.nix, lenovo/thinkpad/t460s.nix
hardware-configuration.nix is still relied upon for hard drive configuration, and it handles variations of hardware (custom configurations, subrevisions).
=> treewide: drop hardware-configuration.nix boilerplate

lenovo/ideapad/z510.nix, lenovo/thinkpad/general-intel.nix, lenovo/thinkpad/general.nix, lenovo/thinkpad/t410.nix, lenovo/thinkpad/t460s.nix, lenovo/thinkpad/x140e.nix, lenovo/thinkpad/x220i-tablet.nix
* `hardware.trackpoint.emulateWheel = true;` is very biased, this module is only for ThinkPads anyway, so default value should be used
* All options should have smaller priority than user-set values (e.g. `services.tlp.enable`)
* Hardware profile should not pull in stuff into system environment unless it's hardware-specific (`pkgs.acpi` is not)
* `sound.mediaKeys` clashes with DE, e.g. Xfce handling sound keys
* Drop redundant `synaptics.enable = false;`
=> thinkpad: cleanup

.travis.yml, tests/eval-test.sh
=> add Travis-CI to the repo

CODEOWNERS, README.org, lenovo/thinkpad/x230/default.nix
This PR introduces X230 to the nixos-hardware repo.
For Battery Management and power control `acpi_call` is used instead of `tp-smapi`. Additionally,  `va` and `vdpau`acceleration is enabled.
`tpm-rng` provides an extra entropy source for rngd (which is enabled by default).
=> x230: init

LICENSE
I plan to license the current work under CC0.
Summary: https://creativecommons.org/publicdomain/zero/1.0/
Full text: https://creativecommons.org/publicdomain/zero/1.0/legalcode
This license will facilitate copying parts of profiles without having to attribute. Technically most of the code in this repo is probably non-copyrightable, but it's a gray area, and it's better to be explicit.
Ideally I'd like all previous contributors to license their changes under CC0-1.0.
Some profiles have been originally imported from NixOS Wiki. See: https://web.archive.org/web/20140705105912/https://nixos.org/wiki/Nix_Wiki:Copyrights
> For now when contributing to the wiki you agree that your content may be relicensed to whatever license is choosen by the nix community. Subscribe to the mailinglist to stay …
=> LICENSE: license under CC0-1.0

lenovo/thinkpad/acpi_call.nix, lenovo/thinkpad/t480s/default.nix, lenovo/thinkpad/x230/default.nix
Things seem to mostly work well (except the trackpad, which I haven't figured out yet).
We do want `acpi_call` for tlp, though.
=> Add a basic t480s profile

common/cpu/intel/default.nix
This seems to be the current best practice.
https://www.phoronix.com/scan.php?page=article&item=intel-modesetting-2017&num=1
https://jlk.fjfi.cvut.cz/arch/manpages/man/modesetting.4
=> intel: videoDrivers: intel -> modesetting

common/cpu/intel/default.nix
https://wiki.archlinux.org/index.php/Kernel_mode_setting#Early_KMS_start
Rationale is to provide a somewhat nicer boot experience.
=> cpu/intel: early KMS

README.md, lenovo/thinkpad/x1/6th-gen/default.nix
Just a couple of commits to fix the X1 profile.  The first fixes the reference to a file that was renamed and the second  fixes acpi override file.
=> Fix unusable Lenovo Thinkpad X1 profile

README.md, default.nix, lenovo/thinkpad/x260/default.nix
Added a profile for x260.
- TLP config includes a fix for BTRFS(the first line), which e.g. is not present in config for x1 6th gen. AFAIK this should not influence the performance too much, yet it should prevent possible bugs/data corruption, which BTRFS users may encounter otherwise, hence I think it's a good idea to put it there.
- While working on this I noticed that most of the other ThinkPad profiles do not include the `acpi_call`, which is required, e.g. for TLP to work. Did not include the fixes, as that is out of scope of this PR.
- Maybe it would be a good idea to extract the TLP config into a (shared) function, which would generate powersaving config given the battery count?
=> lenovo/thinkpad/x260: Init

common/cpu/amd/default.nix, common/cpu/intel/default.nix
This should alleviate concerns raised in https://github.com/NixOS/nixpkgs/issues/33018.
=> common/cpu: default microcode updates to enableRedistributableFirmware

lenovo/thinkpad/x1/6th-gen/default.nix
With UEFI >= 1.30, there's an explicit option to enable S3 power management.
Once this is selected, S3 is enabled and "deep" is selected as the default
/sys/power/mem_sleep value without requiring any kernel boot parameters.
=> lenovo x1 carbon gen6: update S3 suspend

lenovo/thinkpad/x1/6th-gen/default.nix
Fixes #98 , as it should not be set.
=> lenovo-x1: removed battery TLP threshholds

pcengines/apu/default.nix
Prior to this commit, an apu's boot would go through stages of varying visibility:
1. BIOS: exposed to serial
2. GRUB: not exposed to serial
3. Linux: exposed to serial
This commit changes (2) to be visible over serial, so the entire boot is visible over serial.
Tested on nixos 18.09 on a https://www.pcengines.ch/apu1d.htm
References:
* https://www.gnu.org/software/grub/manual/grub/grub.html#Serial-terminal
* https://github.com/NixOS/nixpkgs/issues/37013#issuecomment-379226915
=> pcengines/apu: expose GRUB over serial

README.md, lenovo/thinkpad/t470s/default.nix
Also noted that the t480s was already supported but not on the list of profiles.
=> Added basic support for the t470s

common/pc/laptop/cpu-throttling-bug.nix
The systemd unit has an incorrect specification. The intent of the description is as per systemd documentation (https://www.freedesktop.org/software/systemd/man/systemd.unit.html):
```
Description=¶
A human readable name for the unit. This is used by systemd (and other UIs) as the label for the unit, so this string should identify the unit rather than describe it, despite the name. "Apache2 Web
Server" is a good example. Bad examples are "high-performance light-weight
HTTP server" (too generic) or "Apache2" (too specific and meaningless for people who do not know Apache). systemd will use this string as a noun in status messages ("Starting
description...", "Started
description.", "Reached target
description.", "Failed to start
description."), so it should be capitalized, and should not be …
```
=> Specify a correct unit description

common/pc/ssd/default.nix
This will run TRIM once a week using a systemd timer. Running TRIM regularly
will improves the performance and increases the SSDs lifespan. Since it is based
on the utillinux no additional package is required.
=> enable fstrim on SSDs

toshiba/swanky/default.nix
Both unstable and 19.03 come with 4.19+ kernels
making this option obsolete.
Disclaimer: I don't own this hardware and my change is purely based
on the comment in the code.
=> toshiba/swanky: switch to default kernels

README.md, lenovo/thinkpad/t490/default.nix, lenovo/thinkpad/t490/t490-profile-set.conf
This fixes the pulseaudio profiles of the Thinkpad T490.
The laptop contains a single audio card with 5 sub-devices. Default pulseaudio only offers a single sink which can only be switched between speaker/HDMI via a manual profile change.
This configures a profile set for pulseaudio which offers multiple sinks corresponding to the speaker + 4 HDMI ports. This allows the user to play audio streams on the speaker and any of the 4 HDMI/USB-C ports at the same time.
=> Add better pulseaudio support for thinkpad t490

lenovo/thinkpad/default.nix, lenovo/thinkpad/x1/6th-gen/default.nix
* Enable wheel emulation by default if trackpoint support is enabled
* Set proper TrackPoint name for ThinkPad X1 Carbon 6th Gen
Please refer to the commit messages for further details :)
=> thinkpad: minor trackpoint fixes

lenovo/thinkpad/x250/default.nix
This kernel module is needed to, for example, support tlp's
- `START_CHARGE_THRESH_BAT?` and
- `STOP_CHARGE_THRESH_BAT?`
options.
=> thinkpad/x250: add acpi_call

lenovo/thinkpad/t490/default.nix
The previous matcher was overly broad, which caused it to disable newly found usb audio chips.
=> match specifically on the sound chip

dell/xps/15-7590/default.nix
These suggested options for X users are taken from my configuration, but aren't quite universal enough to be enabled by default.
=> Add Dell XPS 15-7590 suggested options

dell/xps/15-7590/default.nix
Virtual console options were renamed in 20.03; use `console.earlySetup` or `boot.earlyVconsoleSetup` depending on OS version.
Follows discussion in https://github.com/NixOS/nixos-hardware/pull/114#discussion_r374953204
=> Support NixOS 19.09 for <dell/xps/15-7590>

README.md, dell/xps/15-9560/README.wiki, dell/xps/15-9560/default.nix, dell/xps/15-9560/intel/default.nix, dell/xps/15-9560/nvidia/default.nix, dell/xps/15-9560/xps-common.nix
Add xps 9560 with its own quirks, I added versions:
1 default one, with nvidia working and intel working, needs optirun to
run application with nvidia
2 intel only, I am using this as my daily driver for long time, only
intel is turned on and nvidia is turned off and doesn't drain any
power.
3 nvidia only, intel is dissabled and nvidia is picked as default gpu,
no need to fiddle with optirun etc, good for gpu heavy application.
All these settings needs to reboot to work properly.
=> Adding Dell XPS 15 9560

README.md, lenovo/thinkpad/t495/default.nix
The E495 and T495 are based on the same core Ryzen platform, so the
E495 tweaks apply similarly to the T495.
Tested on my own T495, works well.
=> lenovo/thinkpad/t495: init from e495.

lenovo/thinkpad/t495/default.nix
Saving/loading the backlight state requires the acpi_backlight=native
kernel parameter.
acpi_call is required by TLP to get access to battery conditioning
information from the firmware.
Signed-off-by: David Anderson <dave@natulte.net>
=> thinkpad/t495: fix backlight save/load and and battery conditioning.

lenovo/thinkpad/x230/default.nix
Set TLP charging thresholds to values recommended by the TLP developer on [ThinkPad-Forum.de](https://thinkpad-forum.de/threads/184510-elementary-OS-Thinkpad-X230-einrichten?p=1865345&viewfull=1#post1865345).
=> Change TLP charge thresholds

lenovo/thinkpad/x230/default.nix
see https://github.com/NixOS/nixos-hardware/pull/154#issuecomment-617181517
=> x230: don't enable battery thresholds by default

README.md
Following the current instructions yields these errors for some reason:
```
$ sudo nixos-rebuild switch
warning: Nix search path entry '/nix/var/nix/profiles/per-user/root/channels/nixos' does not exist, ignoring
error: file 'nixpkgs/nixos' was not found in the Nix search path (add it using $NIX_PATH or -I), at (string):1:13
building Nix...
warning: Nix search path entry '/nix/var/nix/profiles/per-user/root/channels/nixos' does not exist, ignoring
error: file 'nixpkgs/nixos' was not found in the Nix search path (add it using $NIX_PATH or -I)
warning: Nix search path entry '/nix/var/nix/profiles/per-user/root/channels/nixos' does not exist, ignoring
error: file 'nixpkgs' was not found in the Nix search path (add it using $NIX_PATH or -I)
warning: Nix search path entry …
```
=> README: fix nix-channel --update command

README.md, dell/latitude/3480/default.nix
The touchpad is painful to use unless the "psmouse" kernel module
is disabled.
=> New dell/latitude/3480

README.md, tuxedo/infinitybook/v4/default.nix
This is required so that the keyboard driver is reloaded after suspend.
=> Add InfinityBook v4

common/cpu/intel/default.nix
Provides hardware accelerated video playback from Broadwell onwards.
Older boards (e.g. Sandy Bridge) are not supported. I'm not sure if they should specifically be excluded.
More info:
* https://github.com/intel/media-driver#supported-platforms
* https://wiki.archlinux.org/index.php/Hardware_video_acceleration#Intel
Closes #99.
=> intel: add intel-media-driver

dell/xps/13-9360/default.nix
Fixes deprecation warning:
>trace: warning: The option `i18n.consoleFont` defined in `/nix/var/nix/profiles/per-user/root/channels/nixos-hardware/dell/xps/13-9360` has been renamed to `console.font'.
=> dell/xps/13-9360: Stop using i18n.consoleFont

common/pc/laptop/default.nix
This setting has been part of NixOS since version 16.09.
It's defined in [services/hardware/tlp.nix](https://github.com/NixOS/nixpkgs/blob/82b5f87fcc710a99c47c5ffe441589807a8202af/nixos/modules/services/hardware/tlp.nix#L59).
=> pc/laptop: remove redundant cpuFreqGovernor setting

README.md, dell/xps/13-9343/default.nix
I have no idea if `throttled` and `thermald` are needed since `common/pc/laptop` has `tlp`. I copied them from another profile.
Also I wonder if `boot.extraModulePackages = [ config.boot.kernelPackages.broadcom_sta ];` should be in the profile since `hardware-configuration.nix` already has it. I wonder if it could help people figure out that they need to make a custom iso with that driver to be able to install with the wifi. Maybe it could be noted in a README.
> With kernel 4.6.5 and tlp, the idle power usage can reach ~2.3 W with the kernel parameter pcie_aspm=force enabled. 
https://wiki.archlinux.org/index.php/Dell_XPS_13_(9343)#Powersaving
I also wonder if this should be included or only noted in a README. If included I'm not sure how the user could disable it.
=> add xps 13 (9343)

dell/xps/13-9360/default.nix
Removed setting console.font for >= 20.03
because the auto generated `hardware-configuration.nix` now sets:
```
console.font = lib.mkDefault "${pkgs.terminus_font}/share/consolefonts/ter-u28n.psf.gz";
```
Which cause the following error when also importing `<nixos-hardware/dell/xps/13-9360>`:
```
The option `console.font' has conflicting definitions, in 
`/etc/nixos/hardware-configuration.nix' and 
`/nix/var/nix/profiles/per-user/root/channels/nixos-hardware/dell/xps/13-9360'.
```
Closes #177
=> dell/xps/13-9360: conflicting font fix

flake.nix
I wished to simplify my nix expression of my system, and I wanted to be able to do this quickly (without having to make change in this repo, as I mainly wanted the common/gpu/nvidia option to replace the code I copied from the nixos wiki). I decided to use flake, but I couldn't find a way to call the common/gpu/nvidia.nix file. I decided to add the other module in common/ too, for those who are interested by that. I will probably add a module for my laptop soon, btw.
=> permit to access config in common/ via the flake

README.md, flake.nix, lenovo/thinkpad/l14/amd/default.nix, lenovo/thinkpad/l14/default.nix, lenovo/thinkpad/l14/intel/default.nix
This PR adds support for the Lenovo Thinkpad L14 Gen 1 laptop with AMD Ryzen CPU (Renoir).
I'm not 100% sure where to put the module. If some one has a better idea than `l14-amd` I'm all ears. Should it be `l14/amd` instead?
=> Add support for the Lenovo Thinkpad L14 (AMD) laptop

common/pc/default.nix
`ath3k` requires non-free firmware.
This improves boot speed if `enableRedistributableFirmware` is false.
=> common/pc: disable ath3k if non-free firmware is not available

README.md, flake.nix, lenovo/thinkpad/t14s/amd/default.nix, lenovo/thinkpad/t14s/amd/gen1/default.nix, lenovo/thinkpad/t14s/default.nix
Adds special settings for AMD models. linuxPackages 5.8 is currently only available in 20.09, but is required for backlight and microphone to work. The graphics chipset should work with older kernels (reportedly also 5.4), but this is untested.
There is some manual work required to get suspend and the fingerprint sensor to work, so I left a comment, in the hopes that it may be found. It's probably infeasible to put a warning, since the firmware version and UEFI settings are hard to detect from nix.
=> t14s: fix minimum kernel version

lenovo/thinkpad/x260/default.nix
With switching from NixOS 20.03 to 20.09, the `services.tlp.extraConfig` option became deprecated and was replaced by `services.tlp.settings`.
The ThinkPad X260 is only device within `nixos-hardware` which makes use of this configuration.
=> lenovo/thinkpad/x260: use services.tlp.settings

lenovo/thinkpad/x260/default.nix
The video driver causes short freezes from time to time, especially if an external monitor is attached. Adding the `i915.enable_psr=0` kernel parameter mitigates those freezes.
This is a known problem for the X260, as mentioned in the [Arch Wiki](https://wiki.archlinux.org/index.php/Lenovo_ThinkPad_X260#Thinkpad_X260). It occurred mainly after switching to kernel version five.
=> lenovo/thinkpad/x260: i915.enable_psr=0 parameter

apple/README.md, apple/default.nix
not 100% sure it should be default, as technically cmd is a super key, but being accustomed to PC keyboard layout I think it might easily be default.
ref: https://wiki.archlinux.org/index.php/Apple_Keyboard#Switching_Cmd_and_Alt/AltGr
=> macbook: added option for swapped cmd and opt

apple/macbook-pro/12-1/README.md, apple/macbook-pro/12-1/default.nix
fixes #211.
fixes #210.
Added default CPU governor "conservative" to enable gradually increasing/decreasing CPU freq, rather than using "powersave", which would keep CPU freq at 0.8Ghz.
Added power Up/Down PM commands which will unload and load brcmfmac on state change. This is not elegant way, to say the least.
=> apple/macbook-pro/12-1: PM: set cpuFreqGovernor and power Up/Down commands

README.md, dell/g3/3779/default.nix, flake.nix
Add initial support for the Dell G3 3779.
This laptop runs NixOS fine with Nvidia PRIME offload.
Regards,
=> dell/g3/3779: init

lenovo/thinkpad/l14/amd/default.nix
I've updated the comment about disabling the IOMMU to refer to the new BIOS version that claims to fix issues. There is no functional change here, but the comment should guide people to the right place if they really want the IOMMU to be enabled.
=> lenovo/thinkpad/l14/amd: update iommu comment

raspberry-pi/2/default.nix
This option is no longer needed. Also remove boot.extraTTYs since
NixOS is older than 20.03 is no longer supported.
=> raspberry-2: remove console.extraTTYs

common/gpu/nvidia-disable.nix, dell/xps/15-9550/default.nix, dell/xps/15-9560/intel/default.nix, flake.nix
This is already used in XPS 15-9560, but instead of defining it in XPS 15-9560 let's create a separate profile and expose it for those who want to disable their NVIDIA GPU.
=> Add nvidia-disable profile

lenovo/thinkpad/x270/default.nix
Disable "Panel Self Refresh" for ThinkPad X270.  Fix random screen freezes.
I own a ThinkPad X270.  This has been verified on my device.
=> ThinkPad X270: Disable Panel Self Refresh

microsoft/surface/README.md, microsoft/surface/default.nix
This adds [surface-control](https://github.com/linux-surface/surface-control), a command line tool to control various aspects of the Microsoft Surface line of devices from the command line.
This PR depends on https://github.com/NixOS/nixpkgs/pull/111690, and is a draft until it is merged.
=> microsoft-surface: add surface-control

CODEOWNERS, README.md, flake.nix, system76/darp6/default.nix, system76/default.nix
This integrates the System76 hardware support at https://github.com/stites/system76-nixos into this repo.  @stites did the bulk of the work in that repo, and I added support for the Darter Pro.
This PR *only* includes the kernel modules for now, along with some NixOS options for controlling which modules are enabled.  These kernel modules are needed for multimedia keys and keyboard backlights to work on System76's laptops.  System76 provides also some daemons and tools for hardware management, and some of these are included in the other repo, but I haven't had the time/need/interest use them yet.
I have the darp6 and all hardware works, with the two `system76-acpi` and `system76-io` modules.  I can't personally test the `system76` module as my laptop doesn't need it, but I'm including it …
=> Add support for System76 hardware, specifically the Darter Pro 6

flake.nix
For computers like the Lenovo X1 Carbon Gen 2 no extra configuration is needed (as far as I'm aware), so the default x1 config can be used. However, this is not currently possible with flakes, since the configuration isn't exposed in flake.nix.
I suspect that the same argument could be had for other laptops. Would it be a good idea to expose all generic configurations, instead of only this one?
=> Add default lenovo-thinkpad-x1 config to flake.nix

common/gpu/amd/default.nix, common/gpu/amd/sea-islands/default.nix, common/gpu/amd/southern-islands/default.nix, flake.nix
Inspired by [https://github.com/NixOS/nixpkgs/issues/116619](https://github.com/NixOS/nixpkgs/issues/116619), I decided to create basic profiles for AMD GPUs according to the NixOS Wiki [article](https://nixos.wiki/wiki/AMD_GPU).
The profile for Sea Islands works fine on my machine (R9 290X), I expect the one for Southern Islands to work equally well.
=> Add profiles for AMD GPUs

apple/macbook-pro/12-1/default.nix
=> apple/macbook-pro/12-1/default.nix: Fixed impure <nixpkgs> import.

raspberry-pi/4/default.nix, raspberry-pi/4/modesetting.nix
This adds a pair of option to enable and configure the vendor-specific modesetting driver for the Raspberry Pi 4B.
```nix
{
imports = [
./nixos-hardware/raspberry-pi/4
];
hardware.raspberry-pi."4".fkms-3d.enable = true;
}
```
Since we're using `lib.mkBefore`, even if a user has set `fbdev` (wrongly) in their `videoDrivers` it will use `modesetting` first. Adding `fbdev` ensures there's a fallback plan in case things break with modesetting in the future.
You'll know modesetting is enabled if you can configure the resolution of the display in your desktop environment.
There's also:
```
[samuel@pi4-nixdev:~]$ dmesg | grep -i kms
[    2.165923] vc4-drm gpu: bound fe600000.firmwarekms (ops vc4_fkms_ops [vc4])
```
* * *
- https://logs.nix.samueldr.com/nixos-aarch64/2021-05-12#1620854599-16208551 …
=> raspberry-pi/4: Add modesetting option

raspberry-pi/4/default.nix, raspberry-pi/4/dwc2.nix, raspberry-pi/4/modesetting.nix
This pull request adds the nixos module option
```
hardware.raspberry-pi."4".dwc2.enable = true;
```
which puts the dwc2 controller into otg mode by default, which can also be changed using:
```
hardware.raspberry-pi."4".dwc2.dr_mode = <one of "host", "peripheral", "otg" (otg is default)>;
```
the DTS content should basically be the same as  https://github.com/raspberrypi/linux/blob/rpi-5.10.y/arch/arm/boot/dts/overlays/dwc2-overlay.dts, but that did not work.
I ended up decompiling `dwc2.dtbo` from the rpi4 kernel package (selected by `hardware.deviceTree.kernelPackage`) using this command:
```
${pkgs.dtc}/bin/dtc -I dtb -O dts ${config.hardware.deviceTree.kernelPackage}/dtbs/overlays/dwc2.dtbo
```
and then took its content, modified the top-level `compatible` clause and that worked. …
=> Raspberry pi 4: Add dwc2 usb otg gadget support

README.md, flake.nix, friendlyarm/nanopc-t4/README.md, friendlyarm/nanopc-t4/default.nix
As suggested by @Mic92 in https://github.com/NixOS/nixpkgs/pull/111034 I'm submitting [my fixes](https://github.com/jakubgs/nixos-nanopc-t4) for the [FriendlyARM NanoPC-T4](https://www.friendlyarm.com/index.php?route=product/product&product_id=225) device.
I'm not sure if forcing a specific kernel version is kosher, but on the other hand I don't know if my kernel config changes will work on any other version. I'm open to suggestions as to how to do this better.
Also unusure if I should call the folder `friendlyarm` or `friendlyelec`.
=> friendlyarm/nanopc-t4: init

common/pc/laptop/default.nix
Gnome 40 now uses [power-profile-daemon](https://gitlab.freedesktop.org/hadess/power-profiles-daemon ),which clashes with tlp.
This check will disable tlp whenever it finds that the
power-profiles-daemon is activated. This should also
fix the issue mentioned in #260.
I'm not 100% sure if this is "the way" to do it, but it fixes the problem
on my end. For reference, I'm using the Lenovo Thinkpad T495.
Also, this will be my first pull request to this project. So if I'm doing
anything wrong, please let me know :).
=> Tlp and power profiles daemon clash

raspberry-pi/4/default.nix, raspberry-pi/4/tc358743.nix
I made tc358743 HDMI-to-CSI-2 board work on the rpi with nixos. 
(the board that i use is from [ali express](https://de.aliexpress.com/item/4000102166176.html?spm=a2g0s.9042311.0.0.45b14c4dmRSO6V))
this relates to the `ustreamer` PR on nixpkgs: https://github.com/NixOS/nixpkgs/pull/124955
=> raspberry-pi/4: Add tc358743 option

lenovo/thinkpad/t14s/amd/default.nix
The Thinkpad T14s AMD editions include AMD integrated graphics that can be handled by the /common/gpu/amd module.
=> thinkpad t14s amd: add amd gpu module

dell/xps/15-9500/default.nix
Fix WiFi support on Dell XPS 9500 ([Intel® Killer™ Wi-Fi 6 AX1650s](https://ark.intel.com/content/www/us/en/ark/products/211610/intel-killer-wi-fi-6-ax1650-i-s.html)) 
Currently seeing these crashes on AX networks along with very slow speeds.
```
Jun 09 12:15:09 nixos kernel: iwlwifi 0000:00:14.3: Microcode SW error detected. Restarting 0x0.
Jun 09 12:15:09 nixos kernel: iwlwifi 0000:00:14.3: Start IWL Error Log Dump:
Jun 09 12:15:09 nixos kernel: iwlwifi 0000:00:14.3: Status: 0x00000040, count: 6
Jun 09 12:15:09 nixos kernel: iwlwifi 0000:00:14.3: Loaded firmware version: 59.601f3a66.0 QuZ-a0-hr-b0-59.ucode
Jun 09 12:15:09 nixos kernel: iwlwifi 0000:00:14.3: 0x000019D7 | ADVANCED_SYSASSERT          
Jun 09 12:15:09 nixos kernel: iwlwifi 0000:00:14.3: 0x0000BE06 | trm_hw_status0
Jun 09 …
```
=> Fix 9500 AX Crashes

microsoft/surface/default.nix
depends on https://github.com/NixOS/nixpkgs/pull/124600
Tested on Surface Pro 5 along with the current kernel patching (5.10.19). I'm interested in upgrading to 5.11.
=> surface: add iptsd

common/gpu/nvidia-disable.nix
Two reasons for this change:
- `intel` drivers are not updated from quite a long time (since ~2019), and `modesetting` is the preferred one for Intel iGPUs.
- Technically you may want to disable NVIDIA GPUs on laptops with AMD processors too.
We don't want to pin `modesetting` here because it is already the default since PR: https://github.com/NixOS/nixpkgs/pull/111551.
=> Remove intel drivers from nvidia-disable

README.md, onenetbook/4/default.nix, onenetbook/4/goodix-stylus-mastykin/5.12.12.patch.patch, onenetbook/4/goodix-stylus-mastykin/Makefile, onenetbook/4/goodix-stylus-mastykin/default.nix
One Netbook 4 has a buggy stylus driver.
This submission compiles a patched one as an alternative kernel module and blacklists the mainline one.
No idea how idiomatic this is, suggestions are welcome.
=> Add onenetbook/4

raspberry-pi/4/default.nix, raspberry-pi/4/poe-hat.nix
This enables support for official [PoE Hat](https://www.raspberrypi.org/products/poe-hat/) for raspberry pi 4. Specifically, it adds controls for the included fans / cooling device. It adds a module option:
```
hardware.raspberry-pi."4".poe-hat.enable = true;
```
=> raspberry-pi/4: Add poe-hat option

raspberry-pi/4/audio.nix, raspberry-pi/4/default.nix
This adds an option to enable and configure audio on the Raspberry Pi 4.
```nix
{
imports = [
./nixos-hardware/raspberry-pi/4
];
hardware.raspberry-pi."4".audio.enable = true;
}
```
Enabling this setting does two things:
1. Apply a dts overlay that is equivalent to `dtparam=audio=on`. This was [authored](https://gist.github.com/samueldr/e83102caf431ccef8bc2e825f9273ca7) by @samueldr, who told me to test and make a PR and here we are :)
2. configure `module-udev-detect` with `tsched=0` in pulseaudio's `default.pa`. This is a commonly recommended fix ([1](https://steamcommunity.com/app/353380/discussions/6/1642042464753800526) [2](https://steamcommunity.com/app/353380/discussions/6/1642042464753800526) [3](https://wiki.archlinux.org/title/PulseAudio/Troubleshooting#Glitches,_skips_or_crackli …
=> rpi4: add module for audio settings

lenovo/thinkpad/e495/default.nix
Saving/loading the backlight state requires the `acpi_backlight=native` kernel parameter.
=> lenovo/thinkpad/e495: use native acpi backlight

raspberry-pi/4/audio.nix
Follow-up to #301 :)
Watched a video yesterday evening, got audio glitches after some 15 minutes. Applied the setting, audio issues gone.
=> raspberry-pi/4: Include tsched=0 fix in audio module

apple/macbook-pro/10-1/default.nix, dell/xps/13-9360/default.nix, dell/xps/15-9560/xps-common.nix
- We should not enable canTouchEfiVariables by default as this
wears out the EFI storage.
- We should not set systemd-boot as default. This is up to the user to
decide. There are exceptions when hardware only supports specific
bootloaders so.
=> remove systemd-boot from hardware profiles

raspberry-pi/4/audio.nix
Fixes #302, by fixing the syntax (parenthesis) and using mkOverride 990 as a slightly higher priority default - two identical priorities apparently also clash.
=> raspberry-pi/4: fix usage of mkDefault in audio module

microsoft/surface/firmware/surface-go/ath10k/ath10k-replace.nix
The standard ATH10k source image doesn't work, and the version from KillerNetworking fails to download with non-browser tools.
This adjusts the source repo to github.com/mexisme/linux-surface_ath10k-firmware which is a mirror of the KillerNetworking image.
Note: https://github.com/linux-surface/linux-surface/issues/542 (via https://github.com/linux-surface/linux-surface/issues/41) will hopefully make this obsolete in the future, but getting the updated firmware image into the Kernel has proved slow and challenging.
=> Fix source repo for MS Surface Go ATH10k Firmware image

lenovo/thinkpad/t420/default.nix
The T420 seems to have partial (readonly) support for the tp-smapi module, which TLP can make use of:
> Install tp-smapi kernel modules for extended battery info (e.g. the cycle count)
See https://github.com/linrunner/TLP/commit/903d7fa67d8da61af85d59e9bd5eac371d366dc1
=> lenovo/thinkpad/t420: add tp-smapi

common/gpu/amd/default.nix
In order for many Proton Games to work OOTB with modern AMD graphics cards `driversi686Linux.amdvlk` is needed.
I didn't include the package previously as it hadn't been backported into stable, now I think it's a good time to include it.
=> AMD: include 32-bit driver for Vulkan

common/cpu/intel/default.nix
At the moment the OpenGL extraPackages for Intel are only added for the 64bit variant, but not the 32bit one.
The AMD does add its modules to the 32bit variant: https://github.com/NixOS/nixos-hardware/blob/a57fc74bc3c88537b7f80bc7bee428dd9e9a34ca/common/gpu/amd/default.nix#L13-L15
Note that `pkgsi686Linux` was used instead of `driversi686Linux`, because `intel-media-driver` was not defined for `driversi686Linux` in nixpkgs: https://github.com/nixos/nixpkgs/blob/87304645b876629a056d4e4b3043b99d125a054d/pkgs/top-level/all-packages.nix#L15882-L15892
=> fix(intel): add opengl packages for 32bit

common/cpu/intel/default.nix
Reverts pr #333 as it breaks 21.05 based configurations.
Error:
`error: Package ‘intel-gmmlib-21.1.3’ in /nix/store/ql6s3pl8gfv6v1n3ffsww0yspbji5lx3-source/pkgs/development/libraries/intel-gmmlib/default.nix:21 is not supported on ‘i686-linux’, refusing to evaluate.`
To prevent people having to spend time to trace this error back to nixos-hardware, I think we should revert this now and discuss a solution afterwards.
=> Revert "Merge pull request #333 from bobvanderlinden/pr-intel-32bit"

README.md, flake.nix, lenovo/thinkpad/x1/9th-gen/default.nix
This solves lagging noticeable on high-resolution screens.
=> Use a more recent kernel for Thinkpad X1

friendlyarm/nanopc-t4/default.nix
This option no longer has any effects. We can set kernel parameter now, but since I don't this device it's not clear to me which tty I would need to configure.
cc @jakubgs
=> nanopc-t4: remove deprecated serial speed

dell/xps/13-9310/default.nix
I've upstreamed these patches in NixOS/nixpkgs#144409, which means we no
longer have to build the kernel every time we update just to get
bluetooth working :tada:
While these changes have landed in master, they haven't been back-ported
to 21.05. They will be available via 21.11, which I'm currently testing
(along with this commit) by setting my `nixos` channel to the necessary
nixpkgs pre-release branch, e.g.
```bash
sudo nix-channel --remove nixos
sudo nix-channel --add https://github.com/NixOS/nixpkgs/archive/release-21.11.tar.gz nixos
sudo nix-channel --update nixos
```
*Note that if you use the above branch like I am, you might miss the
cache on some pkgs and spend even longer building those (looking at you
libreoffice).*
As of writing this PR, the current kernel is 5.15.4 and all …
=> xps-9310: Remove upstreamed kernel patches with custom config

lenovo/thinkpad/x1/6th-gen/default.nix, lenovo/thinkpad/x1/7th-gen/default.nix, lenovo/thinkpad/x1/9th-gen/default.nix
Import ssd config for models that always use an ssd.
I did not add the import for all X1 models since the [earlier models](https://pcsupport.lenovo.com/eg/en/products/laptops-and-netbooks/thinkpad-x-series-laptops/thinkpad-x1-carbon-type-20a7-20a8/solutions/pd013126-notebook-hard-drives-reference-guide) might have an internal HDD depending on the configuration.
=> thinkpad/x1: import ssd config for relevant models

lenovo/thinkpad/x1/default.nix
NixOS disables the Intel IOMMU by default (NixOS/nixpkgs#4956) due to hardware comparability issues. In testing I've discovered no issues with either a X1 Gen 1 or X1 Gen 9, so it stands to reason the X1 line generally supports the Intel IOMMU.
=> thinkpad/x1: enable Intel IOMMU

flake.nix
Flake output `nixosModules.lenovo-thinkpad-l13-yoga` referenced wrong module path `./lenovo/thinkpad/l13-yoga/yoga`:
```
$ nix flake check --no-build --keep-going
error (ignored): error: getting status of '/nix/store/hpj9vw2smvlwc257w96k78fk12q2v6cy-source/lenovo/thinkpad/l13-yoga': No such file or directory
error: some errors were encountered during the evaluation
```
This merge request changes the path to `./lenovo/thinkpad/l13/yoga`
=> Fix flake output lenovo-thinkpad-l13-yoga

microsoft/surface/firmware/surface-go/ath10k/ath10k-replace.nix
The outputHash would change and frequently cause this to not work. This
gets around the issue by using the built version firmwareLinuxNonfree as
a source instead of trying to patch it directly.
=> Refactor ath10k-replace to no longer need an outputHash

common/cpu/intel/default.nix
`libvdpau-va-gl` is a wrapper around VAAPI to have a VDPAU driver, which is required for Intel GPU's. `VDPAU_DRIVER` environment variable is set to "va_gl" now, since it defaults to "nvidia".
=> common/cpu/intel: define VDPAU_DRIVER env variable

raspberry-pi/4/default.nix, raspberry-pi/4/pwm0.nix
This adds hardware PWM support on GPIO 18. There's probably a better way to do this, but this should be good enough for a start.
Usage: `hardware.raspberry-pi."4".pwm0.enable = true;`
=> Add rpi4 pwm0 support

asus/battery.nix
Fixes chargeUpto setting getting reset after suspend/resume cycle by using a systemd service which runs after suspend instead of tmpfiles.
Fixes #373
=> asus/battery.nix: fix chargeUpto after suspend/resume, make script optional

common/gpu/amd/default.nix
RADV has been proven faster than AMDVLK by [more](https://www.phoronix.com/scan.php?page=article&item=amdvlk-radv-eo2021&num=1) [than](https://www.phoronix.com/scan.php?page=article&item=radv-amdvlk-july21&num=1) [one](https://linuxreviews.org/The_Best_Linux_Vulkan_Driver_For_AMD_GPUs:_Mesa_RADV_vs_AMDVLK) benchmark, and is recommended by projects like [DXVK](https://github.com/doitsujin/dxvk/wiki/Driver-support#amd-drivers).
I set an environment variable instead of removing AMDLK so that it can be easily switched to by setting `AMD_VULKAN_ICD=AMDVLK`.
=> AMD: Prefer RADV

common/pc/hdd/default.nix, common/pc/ssd/default.nix
Setting very low value to swapiness will not probably benefit most users, so I just removed those configs in hdd/ssd module to revert to kernel's default value.
https://askubuntu.com/questions/420026/why-is-the-default-swappiness-60-what-would-be-the-effect-if-i-lower-the-swappi/438363#438363
https://askubuntu.com/questions/184217/why-most-people-recommend-to-reduce-swappiness-to-10-20/184221#184221
Lower swappiness could just make the system slower when it runs out of memory, or even cause freezes: https://askubuntu.com/questions/184217/why-most-people-recommend-to-reduce-swappiness-to-10-20/1028193#1028193
With higher swappiness value the system copies infrequently used region of physical memory to the disk much earlier, recuding the latency of memory allocation in low-memory …
=> Remove swappiness config

lenovo/thinkpad/x1/default.nix
IOMMU still breaks suspend/resume on multiple Lenovo models including X1.
Currently broken on at least Gen4 which I'm testing on. Hard locks the system during suspend.
This thread claims it works on Gen4 with kernel 5.16.1 but it doesn't work on my hardware, firmware fully updated.
https://bugzilla.kernel.org/show_bug.cgi?id=197029
This should probably be turned on individually for models known to work until it can be more thoroughly tested.
=> Remove `intel_iommu=on` by default for all X1 models.

framework/default.nix
The current lts (5.15) also did not work with this wifi chip. I have not tested 5.16 but 5.17 works for me.
=> framework: bump kernel version

common/cpu/intel/cpu-only.nix, common/cpu/intel/default.nix, common/gpu/intel.nix, common/gpu/nvidia.nix, flake.nix
Is this a good idea?
Should all the profiles using `common/cpu/intel` be modified to also have `common/gpu/intel`? If the same computer model can sometime have an Nvidia card, it could cause the problem I'm trying to fix.
An alternative could be to use an optional `withGPU ? true` .
Another alternative could be to use `mkOverride 900 "nvidia"` with the `common/gpu/nvidia` (see https://github.com/NixOS/nixos-hardware/issues/388#issuecomment-1060933059)
fix #388
=> extract GPU stuff from common/cpu/intel to common/gpu/intel.nix

lenovo/thinkpad/x270/default.nix
This pull request adds acpi call for lenovo thinkpad x270, thus allowing to use tlp.
I also use `<nixos-hardware/common/pc/laptop/ssd/default.nix>` but not all x270 have an SSD (though the majority have it I think)
I wonder if I can add the ssd config even if all x270 don’t have an SSD
=> Add acpi_call for lenovo thinkpad x270

dell/xps/15-9560/nvidia/default.nix
Also rename deprecated `hardware.nvidia.optimus_prime.*' to `hardware.nvidia.prime.*' since NixOS 20.09.
> The hardware.nvidia.optimus_prime.enable service has been renamed to
> hardware.nvidia.prime.sync.enable and has many new enhancements.
> Related nvidia prime settings may have also changed.
See https://nixos.org/manual/nixos/stable/release-notes.html#sec-release-20.09
=> dell-xps-15-9560-nvidia: switch to Nvidia Offload mode to save battery power

framework/default.nix
Two minor tweaks; one to improve power usage after resume - and one to make fprintd possible to disable from another nix config.
=> framework: add nvme.noacpi=1 and make fprintd optional

lenovo/thinkpad/p14s/amd/gen2/default.nix
When upgrading to 22.05, my wireless card did not work anymore, because the default linux version in NixOS 22.05 is 5.15, which does not yet include rtw89. This fixes this by ensuring that the latest version is used on older kernel versions.
=> p14s: ensure rtw89 driver is available

common/gpu/nvidia.nix
The `-a` from exec sets the `$0` from the process. So `exec -a "$0"` would set the name of the new process to `nvidia-offload` (the name of the script), however this is causing issues with a few programs that try to interpret `$0` in a special way. For example, see `wine`:
```
$ nvidia-offload /nix/store/zhv91s26gsrl1w8yn9800xd03a31r3wj-wine-osu-7.0/bin/wine .osu/drive_c/osu/osu\!.exe
/nix/store/zhv91s26gsrl1w8yn9800xd03a31r3wj-wine-osu-7.0/bin/nvidia-offload: could not open
```
What I think `wine` is doing here is trying to re-exec `wine` again, but to do so it tries to figure out the original call of wine by readind `$0`, and will fail in this case because the `$0` was changed because of the `nvidia-offload` script using `-a` flag, as explained above.
Instead, let's simplify this. There …
=> nvidia: remove `-a` flag from exec

README.md, flake.nix, lenovo/thinkpad/x1-extreme/gen4/default.nix
This doesn't configure NVIDIA graphics card settings as it's an optional component in this laptop and frankly I have no idea how to configure it - the problem is that HDMI port on laptops with NVIDIA card is connected to NVIDIA graphics card, and simply using `offload` won't make this work, but at the same time disabling power management is probably bad for battery if you don't need HDMI.
=> thinkpad/x1-extreme/gen4: add module

common/gpu/amd/default.nix
I should have done this in #391.
Still, with this you can set `environment.variables.AMD_VULKAN_ICD = "AMDVLK";` in `configuration.nix`.
=> AMD: Add lib.mkDefault to AMD_VULKAN_ICD

lenovo/legion/15ach6/default.nix
Since the latest kernel `5.18` even when the onboard AMD GPU is active `/var/lib/systemd/backlight/pci-0000:05:00.0:backlight:amdgpu_bl0` does not exist.
=> Fix legion 7 slim 15ach6

README.md, flake.nix, lenovo/legion/15ach6/default.nix, lenovo/thinkpad/t460p/default.nix
This PR adds support for the Thinkpad T460p. It is identical to T460 and T460s. It's main purpose is to make it clear to users which to select to configure for that specific model without having to look at the other T460 variants and decide that they are all identical. It has been tested on a T460p.
=> Adds support for Thinkpad T460p

dell/inspiron/5515/default.nix, dell/inspiron/5515/fix_touchpad.sh
On rare occasions, the module would be removed before suspend and the touchpad would be
disabled on boot.
I have been testing this for weeks and it does not look racy anymore.
=> inspiron-5515: fix race for fix-touchpad.sh

raspberry-pi/4/apply-overlays-dtmerge.nix, raspberry-pi/4/default.nix, raspberry-pi/4/pkgs-overlays.nix, raspberry-pi/4/poe-plus-hat.nix
Changes here:
* update the poe-hat-overlay dts to work with the 5.15y release of rpis kernel
* add poe-plus-hat-overlay for use with the [PoE+ HAT](https://www.raspberrypi.com/products/poe-plus-hat/)
* using `dtmerge` from `libraspberypi` instead of `fdtoverlay` for the added overlays that require it's the usage
This should provide a ready-to-use solution for:
* https://github.com/NixOS/nixpkgs/pull/79370#issuecomment-772373007
* https://discourse.nixos.org/t/fdt-err-notfound-when-trying-to-apply-device-tree-overlay-on-raspberry-pi-4/19650
There's likely many ways these expressions could be made better, so feedback is very much appreciated.
=> raspberry-pi-4: add poe-plus-hat, update poe-hat, use dtmerge instead of fdtoverlay

README.md, dell/xps/13-9350/default.nix, flake.nix
There’s not much to configure here, but I figure it’s worth documenting that.
Notable omissions:
- `i915.enable_fbc` is unnecessary; frame buffer compression is enabled [automatically](https://github.com/torvalds/linux/blob/v5.18/drivers/gpu/drm/i915/display/intel_fbc.c#L1631-L1635).
```syslog
i915 device info: display version: 9
i915 device info: has_fbc: yes
```
- `i915.enable_psr` is unnecessary; panel self refresh is enabled [by default](https://github.com/torvalds/linux/blob/v5.18/drivers/gpu/drm/i915/display/intel_psr.c#L994).
```syslog
i915 device info: has_psr: yes
i915 device info: has_psr_hw_tracking: yes
```
- `i915.enable_rc6` [no longer exists](https://github.com/torvalds/linux/commit/fb6db0f5bf1d4d3a4af6242e287fa795221ec5b8); RC6 sleep is automatically configured.
```syslog …
```
=> Add Dell XPS 13 9350

pine64/pinebook-pro/default.nix
Upstream udev has had that since 2020: https://github.com/systemd/systemd/commit/f25e30dec4958ba3ab972b823210fcbc9dd231da
Tested on my Pinebook Pro. Brightness keys still work.
=> pine64-pinebook-pro: remove superfluous bright/sleep keys

pine64/pinebook-pro/default.nix
Power management should be left to a power management daemon (e.g. gnome-power-manager) or for users to set/override themselves (e.g. by setting a CPU governor).
I use governor 'schedutil', which is big.LITTLE aware, and thus can sensibly downclock, but min_freq prevents that.
=> pine64-pinebook-pro: remove inappropriate overriding of min_freq

raspberry-pi/4/i2c.nix
Recently I had an application where I wanted to tweak the default 100khz clock frequency of the i2c0 bus to 1mhz, so I decided to expand the i2c dts'es here to include that option.
I'm still very new to nix expressions, so I am sure this code can be simplified in many different ways - feedback is appreciated.
Applying the following:
```nix
{
options.hardware.raspberry-pi."4" = {
i2c0 = {
enabled = true;
frequency = 1000000;
};
};
}
```
Results in:
```
xxd -g4  /proc/device-tree/soc/i2c@7e804000/clock-frequency
00000000: 000f4240 # 1_000_000
```
=> raspberry-pi-4: add i2c clock-frequency option

README.md, apple/macbook-pro/11-5/README.md, apple/macbook-pro/11-5/default.nix
This:
* fixes a problematic reference to `<nixpkgs>`
* removes the old `"ati"` driver (`radeon` is the default now)
* documents how to use `amdgpu` driver via experimental "Southern Islands" support
* notes regarding switcheroo
* adds example hardware probes for reference
=> apple/macbook-pro/11-5: various tweaks and documentation

README.md, flake.nix, framework/12th-gen-intel/README.md, framework/12th-gen-intel/default.nix
This sets up a few things that differ slightly from the original 11th gen Intel edition of the laptop
=> Add support for Framework laptop, 12th gen Intel Core edition

README.md, flake.nix, lenovo/thinkpad/t14/amd/gen3/default.nix
Tests were run and all pass.
I set the kernel to be 5.16 based on [this bug report](https://bugzilla.redhat.com/show_bug.cgi?id=2047878) discussing the necessary patch making it in to 5.16. In reality, this configuration results in my machine using 5.19.8 (5.16 [is EOL](https://lore.kernel.org/lkml/164987613419048@kroah.com/)) and works just fine. Please let me know if it's better to use 5.19 and I'll update.
=> Add thinkpad t14 amd gen3

msi/gs60/default.nix
NixOs renamed `utillinux` to `util-linux`
```
error: attribute 'utillinux' missing
at /nix/store/xmdajfhdaxc38kjymr7rdfdya6yv9r0s-source/msi/gs60/default.nix:26:9:
25|     resumeCommands = ''
26|       ${pkgs.utillinux}/bin/rfkill unblock wlan
|         ^
27|     '';
(use '--show-trace' to show detailed location information)
```
=> Fixed utillinux package renaming

onenetbook/4/goodix-stylus-mastykin/default.nix
New nixpkgs complains about it: `runCommandNoCC' has been renamed to/replaced by 'runCommand'`.
=> onenetbook/4: stop using runCommandNoCC

flake.nix, kobol/helios4/default.nix, kobol/helios4/modules/90-helios4-hwmon.rules, kobol/helios4/modules/fancontrol.nix, kobol/helios4/overlay.nix
This is ready for review, I might add the hdd activity led support later if I get to it, but it should already be useful without that.
=> kobol/helios4: init

pine64/pinebook-pro/firmware/ap6256-firmware/default.nix
runCommandNoCC has been deprecated and nixpkgs now throws an error on use of the command.
=> pine64/pinebook-pro: update runCommandNoCC to runCommand

lenovo/thinkpad/x1-extreme/default.nix
It's deprecated and doesn't work correctly anyway. Recent firmwares can power the GPU off if it drops off the bus, which can be forced with udev rules.
=> lenovo/thinkpad/x1-extreme: remove acpi_call

README.md, flake.nix, gpd/pocket-3/default.nix
This should presumably wait until NixOS/nixpkgs#194594 is merged, as I made the
workaround for `fonts.fontconfig.antialias` conditional on nixpkgs version.
- Sideway screen
=> gpd/pocket-3: init

README.md, flake.nix, starfive/visionfive/v1/README.md, starfive/visionfive/v1/default.nix, starfive/visionfive/v1/firmware.nix, starfive/visionfive/v1/linux.nix, starfive/visionfive/v1/sd-image-installer.nix, starfive/visionfive/v1/sd-image.nix, starfive/visionfive/v1/uboot.nix
Moving from https://github.com/NixOS/nixpkgs/pull/168826.
=> starfive/visionfive/v1: init

raspberry-pi/4/cpu-revision.nix, raspberry-pi/4/default.nix
Lot of libraries have checks to detect that they are running on a Raspberry Pi 4 and fail otherwise.
See https://github.com/gpiozero/gpiozero/issues/837.
This also happens with the current NixOS image, specifically:
```
$ python3
>>> from RPi import GPIO
>>> GPIO.setup(9, GPIO.IN)
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
RuntimeError: Not running on a RPi!
>>>
```
This sets the CPU revision which is the newest way these libraries do their detection.
I've been running this for a while with great results, finally remembered to post something here.
=> raspberrypi/4: allow pi libs to detect pi 4

lenovo/thinkpad/t480s/default.nix
I just realised that ssd support is missing despite the model having ssd
=> Add support for ssd to Lenovo ThinkPad T480s

apple/macbook-pro/14-1/README.md, apple/macbook-pro/14-1/btfix.sh, apple/macbook-pro/14-1/default.nix, apple/macbook-pro/14-1/disable-nvme-d3cold.sh, flake.nix
Extracted from my system configs. There's still a few issues with this machine:
1. Audio is a lost cause. Will probably need to bribe an Apple or Cirrus engineer for the datasheet.
2. The thunderbolt module will oops upon system resume, and subsequently refuse to work until next reboot.
3. The d3cold state needs to be disabled on the NVME controller for it to wake up.
4. The Bluetooth UART (/dev/ttyS0) is created and then deleted by udev in early boot. I am yet to figure out why. Hack around it by reloading the 8250_dw module, causing it to be re-created.
Any ideas for an alternative to the `/dev/ttyS0` hack are welcome,.
=> apple/macbook-pro: add support for 14,1

README.md, flake.nix, lenovo/thinkpad/x1/yoga/7th-gen/default.nix
The Thinkpad X1 yoga 7th gen comes with an intel Alder Lake CPU.
The default Kernel in nixos-unstable did not work with this device:
dmesg had the `hardware newer than driver` error.
After trying out one kernel at a time, at least 5.19 seems to be needed.
Without, only a TTY would show up.
The specific device being used for testing: https://www.lenovo.com/de/de/laptops/thinkpad/thinkpad-x1/ThinkPad-X1-Yoga-Gen-7-14-inch-Intel/p/LEN101T0010
=> add thinkpad x1 yoga 7th-gen

framework/default.nix
Enabling iio makes the Framework's brightness controls available to desktop environments like Gnome.
With this enabled, Gnome has a brightness slider and the automatic brightness adjustment option is available.
=> framework: Add iio in order to enable brightness control

raspberry-pi/4/default.nix
This is required for things like USB Boot to work correctly. Without it, NixOS will fail to discover the disk in Stage 1 of boot.
=> raspberry-pi/4: add pcie_brcmstb and reset-raspberrypi to kernelParams

starfive/visionfive/v1/README.md, starfive/visionfive/v1/sd-image-installer.nix, starfive/visionfive/v1/sd-image.nix
Do not force channels for ``sd-image``.
Fixup README.
=> starfive/visionfive/v1: Make sd-image more flake-friendly

asus/battery.nix
ASUS laptop batteries may have different battery names. [From the Arch wiki](https://wiki.archlinux.org/title/Laptop/ASUS#:~:text=note%3A%20as%20of%202020-12-11%2C%20the%20following%20battery%20device%20names%20are%20recognized%3A%20bat0%2C%20bat1%2C%20batc%20and%20batt.%5B4%5D%20adjust%20accordingly%20or%20use%20the%20single%20character%20wildcard%20(%3F)%2C%20e.g.%20bat%3F.) (referencing [these kernel lines](https://github.com/torvalds/linux/blob/1797d588af15174d4a4e7159dac8c800538e4f8c/drivers/platform/x86/asus-wmi.c#L440-L448)), BAT0, BAT1, BATC and BATT are all recognized names for ASUS batteries. This changes the battery script to use the wildcard to work with all these battery names.
=> Changed asus battery script to work with multiple battery names.

lenovo/thinkpad/t480/default.nix
After seeing https://github.com/NixOS/nixos-hardware/pull/482 this is also relevant on the t480.
=> Add support for ssd to Lenovo ThinkPad T480

framework/12th-gen-intel/default.nix, framework/default.nix
Add Ethernet Expansion Card support for the framework laptop. Due to automatic USB device suspension, the Ethernet Expansion Card was not working. Adding a udev rule to only suspend the card after 20 seconds fixes the problem. 
The framework support confirmed via email that all current Ethernet Expansion Cards share the same Product ID.
=> Add Ethernet Support on Framework

asus/rog-strix/g733qs/default.nix, asus/zephyrus/ga401/default.nix, asus/zephyrus/ga503/default.nix, common/gpu/nvidia-disable.nix, common/gpu/nvidia.nix, common/gpu/nvidia/default.nix, common/gpu/nvidia/disable.nix, common/gpu/nvidia/prime.nix, dell/g3/3779/default.nix, dell/xps/15-9500/nvidia/default.nix, dell/xps/15-9550/default.nix, dell/xps/15-9550/nvidia/default.nix, dell/xps/15-9560/intel/default.nix, dell/xps/15-9560/nvidia/default.nix, dell/xps/17-9700/intel/default.nix, dell/xps/17-9700/nvidia/default.nix, flake.nix, lenovo/ideapad/15arh05/default.nix, lenovo/legion/15ach6/default.nix, lenovo/legion/15arh05h/default.nix, lenovo/legion/16ithg6/default.nix, lenovo/thinkpad/e470/default.nix, lenovo/thinkpad/p1/default.nix, lenovo/thinkpad/p50/default.nix, lenovo/thinkpad/p51/default.nix, lenovo/thinkpad/p52/default.nix, msi/gl62/default.nix, omen/en00015p/default.nix
Fixes #338
Annoyingly, the flake module can't be deprecated cleanly. Suggestions welcome.
Note I can't properly test changes that involve prime/disable, so I'd appreciate confirmation that that works, as simple as this change looks. Also can't test the module changes, of course.
=> common/gpu/nvidia*: Migrate to common/gpu/nvidia/* and add non-prime

README.md, flake.nix, lenovo/legion/16ach6h/README.md, lenovo/legion/16ach6h/default.nix
Adds suport for the Legion 5 Pro 16ACH6H. AMD CPU+GPU files are due to the iGPU, is it correct to use them both?
Makes my Laptop boot with the propietary drivers which is already an advancement from where I was before.
There's a strange quirk with how its currently set up, for the NVIDIA part, the `mkDefault` in 
https://github.com/NixOS/nixos-hardware/blob/0099253ad0b5283f06ffe31cf010af3f9ad7837d/common/gpu/nvidia/default.nix#L4
Makes tools like `nvidia-smi` and co. dissapear from the shell's path. Removing it brings them back.
=> Add Lenovo Legion 5 Pro Gen 6

common/gpu/amd/default.nix
I get a very weird problem
There is such a line of code in `common/gpu/nvidia/default.nix`
`services.xserver.videoDrivers = lib.mkDefault [ "nvidia" ];`
But in `common/gpu/amd/default.nix` which serves a similar purpose. It is
` services.xserver.videoDrivers = [ "amdgpu" ];`
This means that if you use prime, that is, if you import these two files at the same time, `services.xserver.videoDrivers = lib.mkDefault [ "nvidia" ];` will override `services.xserver.videoDrivers = [ "amdgpu" ];`.
Since the parameters provided to mkOverride are not the same, the smaller one is overwritten. So we need to keep them in sync
This issue should cause problems with all configurations using hybrid graphics, as the nvidia proprietary drivers won't be installed, but it doesn't seem to cause the system to …
=> Add lib.mkDefault in services.xserver.videoDrivers = [ "amdgpu" ];

common/gpu/amd/default.nix
I'm working for make a usable profile for `Lenovo Legion 5 Pro 16ach6h`(The existing version in the repository has a lot of problems, I try to fix it) and I have a problem
This appears to be a Lenovo firmware issue and i try to fix it. This issue still reproducible on BIOS version `GKCN58WW`(22/12/16)
Lenovo Legion 5 Pro is a laptop which support a technology called "DDG" that can allow you switch between discrete graphics mode and hybrid mode (optiums).
In discrete graphics mode, the firmware provides the correct edid and anything works fine, the built-in display work well at 165hz.
But if switch to hybrid mode, the firmware provides a different edid, causing the built-in display only can work at 60hz.
So I extracted the edid file of discrete graphics mode and override the edid that …
=> Add a option to add(or disadd) amdgpu to kernelModule

common/cpu/amd/pstate.nix
There is no separate module now, and a clean option to enable it.
=> cpu/amd/pstate: enable correctly on kernel 6.1+

README.md, dell/latitude/7430/default.nix, flake.nix
Added configuration for the Dell Latitude 7430 laptop.
=> Latitude 7430: init

raspberry-pi/4/apply-overlays-dtmerge.nix
Fixes the issue reported in https://github.com/NixOS/nixos-hardware/issues/503 and updates the apply-overlays-dtmerge overlay with the nixpkgs changes made in https://github.com/NixOS/nixpkgs/commit/916ca8f2b0c208def051f8ea9760c534a40309db
=> raspberry-pi/4: dtmerge update

README.md, flake.nix, lenovo/yoga/6/13ALC6/default.nix
~~**Don't merge it, It's done for me but CONTRIBUTING.md is not implemented yet**~~ Ready for Review
Add support for the LENOVO Yoga 6 13ALC6 82ND
Ryzen 7 5700U
* Easy 10 hrs of battery
* Enable or disable charging limit by TLP config or manually, `echo 1 > /sys/bus/platform/drivers/ideapad_acpi/VPC2004:00/conservation_mode`
* Enable hardware video acceleration in Firefox
* Use latest kernel to make wifi and other things work
=> Add LENOVO Yoga 6 13ALC6 82ND

README.md, flake.nix, panasonic/letsnote/cf-lx4/default.nix
modified README
Backlight support for Panasonic Let's Note
=> Added configuration for panasonic let's note

raspberry-pi/4/apply-overlays-dtmerge.nix
Ported over from https://github.com/NixOS/nixpkgs/pull/205595
Previously whenever an overlay was found to be incompatible with a base device tree blob, the entire base dtb would be skipped in favor of processing the next one. This had the unfortunate effect where overlays would not fully be applied if any incompatibility was found. For example, this is an issue with build device trees specific for one flavor of raspberry pi if the overlay was not compatible _everywhere_.
The solution is to forego the `continue` keyword if an overlay is in compatible and instead use a compound conditional statement to skip incompatible overlays but continue trying to apply it to any remaining dtbs.
=> raspberry-pi/4/dtmerge: fix application of overlays

lenovo/legion/16ach6h/default.nix
16ach6h: Add `system.nixos.tags` for Dual-Direct GFX (DDG) specialisation.
=> 16ach6h: Add tags for Dual-Direct GFX (DDG) specialisation

microsoft/surface/common/kernel/linux-6.0.17/patches.nix
Fix copy-paste typo: "CONFIG_" prefix in structuredExtraConfig patches
- Unintentional typo, due to copy-paste from linux-surface upstream config
=> Fix copy-paste typo: "CONFIG_" prefix in structuredExtraConfig patches

README.md, flake.nix, lenovo/legion/15ich/README.md, lenovo/legion/15ich/default.nix
Adding hardware support for the Lenovo Legion Y530-15ICH. My specific configuration has the Core i7-8750H with a 4GB 1050Ti. 
I have tested this by importing the nixos-hardware repo as a submodule of my configuration repo and updating files as required. I will be leaving this as draft until I am confident everything works as intended, though I see no current issues.
=> Add Support for Lenovo Y530-15ICH

asus/rog-strix/g733qs/default.nix, common/gpu/nvidia/prime.nix
nixpkgs was updated (https://github.com/NixOS/nixpkgs/commit/2a7130d13a032093f5394ef0961842d1e1928789#diff-28ea4da3a9a595f8bd1a37a555c229f998f3a11b0715ebc5842ba266384eba73R326) and the default value of hardware.nvidia.prime.offload.enable was set to mkDefault reverseSyncCfg.enable;
This conflicted with the value set in prime, so I tried using mkOverride 990 instead. (https://discourse.nixos.org/t/what-does-mkdefault-do-exactly/9028)
=> Fix conflict to https://github.com/NixOS/nixpkgs/commit/2a7130d13a032093f5394ef0961842d1e1928789

common/gpu/amd/default.nix, lenovo/legion/16ach6h/default.nix, lenovo/legion/16ach6h/nvidia/default.nix
When I play the game through proton, I found that in the case of Dual-Direct GFX enabled (dGPU disabled), proton will crash directly
But in the case of hybrid, the game runs fine with or without `nvidia-offload`
After investigation, this is because when writing the specialization of Dual-Direct GFX, I did not completely remove all packages for amd igpu. I only removed `amdgpu` from `services.xserver.videoDrivers` by overriding. This is because the specialization of nix cannot implement such an operation as canceling an import. In the end, if it is enabled in Dual-Direct GFX In the absence of amd igpu, the `amdvlk` package caused the proton to crash.
In order to solve this problem, I add the option of whether to enable `amdvlk` to the configuration file of amd gpu, and open it by default, …
=> Add amdvlk and opencl options to amdgpu & Fix proton crash when Dual-Direct GFX enabled for lenovo legion 16ach6h

common/gpu/amd/default.nix
Disable install of amdvlk by default, don't set `AMD_VULKAN_ICD ="RADV"` when enabling amdvlk, and don't install OpenCL when enabling amdvlk.
=> amdlvk cleanup

raspberry-pi/4/default.nix
This should allow the rpi4 config to enable when `allowAliases = false` in the
nixpkgs config.
=> raspberry-pi/4: don't use an alias for the kernel pkg

README.md, flake.nix, gpd/win-2/default.nix
Adds the bare minimums for running NixOS on a GPD WIN 2 without the system being all weird and the display being incorrectly rotated.
=> gpd/win-2: init

lenovo/legion/16ach6h/hybrid/default.nix
It's for Intel laptops. 16ach6h is not one of them.
=> lenovo/legion/16ach6h: disable thermald

flake.nix, nxp/README.md, nxp/common/bsp/imx-atf.nix, nxp/common/bsp/imx-firmware.nix, nxp/common/bsp/imx-mkimage.nix, nxp/common/bsp/imx-optee-os.nix, nxp/common/bsp/imx-uboot.nix, nxp/common/bsp/linux-imx8.nix, nxp/common/modules.nix, nxp/common/overlay.nix, nxp/common/patches/0001-Add-UEFI-boot-for-imx8qm.patch, nxp/common/patches/0001-Add-UEFI-boot-for-imx8qxp.patch, nxp/imx8qm-mek/default.nix, nxp/imx8qm-mek/overlay.nix, nxp/imx8qxp-mek/overlay.nix
Currently there are two devices supported:
* imx8qm-mek
* imx8qxp-mek
Signed-off-by: Ivan Nikolaenko <ivan.nikolaenko@unikie.com>
Changes made in the way it makes very easy to add another mx8-based device or device-specific configuration.
=> Add NXP i.MX8 SOC family support.

lenovo/thinkpad/p14s/amd/gen2/default.nix
=> p14s: do not include acpi_backlight on newer kernel versions

lenovo/thinkpad/p14s/amd/gen2/default.nix, lenovo/thinkpad/t14s/amd/gen1/default.nix
The package was removed in https://github.com/NixOS/nixpkgs/pull/217196 and is now present in linux-firmware.
cc @lovesegfault @QuantMint, should we guard this against some version check? I'm not sure what exactly is needed for wifi to work: is having a 5.16+ kernel enough or would people *also* need a 20230210+ linux-firmware?
=> t14s,p14s: remove rtw89-firmware

README.md, dell/xps/15-7590/nvidia/default.nix, flake.nix
Add hardware configuration for the Dell XPS 15 7590 with NVIDIA graphics.
Import the Intel-based config, the common NVIDIA config and add the necessary bus IDs.
Not sure whether we are supposed to add `hardware.nvidia.powerManagement.enable = true;` here or leave it to the user to decide to enable it or not (I did personally). 
=> Add NVIDIA config for Dell XPS 15 7590

dell/xps/15-7590/default.nix
=> Enable thermald for Dell XPS 15 7590

dell/xps/15-7590/default.nix
Looks like it's no longer needed as of today.
=> Remove override of WiFi module for Dell XPS 15 7590

dell/xps/15-7590/README.wiki, dell/xps/15-7590/default.nix
- This device supports firmware updates through `fwupd`.
- Prefer deep sleep over s2idle which is inefficient.
- Remove old cruft in the corresponding readme.
=> dell-xps-15-7590: enable fwupd and deep sleep

common/cpu/intel/default.nix, common/gpu/intel.nix, common/gpu/intel/default.nix, common/gpu/intel/disable.nix, dell/xps/13-9300/default.nix, flake.nix
Recently had to disable the iGPU, but it turns out that even if you blacklist the module it will still get loaded by the KMS subsystem. Added a module that disables both modelled after the nvidia modules.
=> common/gpu/intel*: Migrate to common/gpu/intel/* and add disable

common/gpu/nvidia/disable.nix
Fixed turning off Nvidia dGPU using instructions from [arch wiki](https://wiki.archlinux.org/title/Hybrid_graphics#Using_udev_rules)
=> Fix disabling Nvidia dGPU

common/gpu/amd/default.nix
Follows upstream nixpkgs, see https://github.com/NixOS/nixpkgs/pull/218437
=> common/gpu/amd: use modesetting driver by default

README.md, flake.nix, hardkernel/odroid-hc4/default.nix
I propose to include some specific board options for the Odroid HC4 in nixos-hardware.
I have been successfully using NixOS on my Odroid HC4 since December 2021.
=> Add Hardkernel HC4 support

dell/xps/15-7590/nvidia/default.nix
Enable dynamic power management for the NVIDIA GTX 1650 mobile on the Dell XPS 7590. 
=> Enable NVIDIA power management for Dell XPS 7590

lenovo/legion/16ach6h/hybrid/default.nix
lenovo 16ach6h: add amd cpu pstate
=> lenovo 16ach6h: add amd cpu pstate

README.md, flake.nix, gpd/p2-max/default.nix
Module for the [GPD P2 Max](https://liliputing.com/first-look-gpd-p2-max-8-9-inch-mini-laptop/) ultrabook with Intel Kaby Lake m3-8100Y CPU
=> gpd/p2-max: init

README.md, flake.nix, morefine/m600/default.nix
The Morefine M600 is an AMD-powered Mini PC
CPU options (all 6000-series mobile):
• R9-6900HX
• R9-6850H
• R7-6850U
• R7-6800H
• R5-6600U
If bought with RAM + HDD, you would be getting DDR5 RAM @ 4800MHz and a NVMe drive, however, it can also be purchased “barebone”.
importing it via `<nixos-hardware>` or Flake input (will do when I reboot)
=> init morefine-m600

common/hidpi.nix, flake.nix, gpd/p2-max/default.nix, gpd/pocket-3/default.nix
Seems like we can't agree on what the "good" settings are.
For older NixOS versions this is largely a no-op anyway.
=> treewide: unset hardware.video.hidpi

lenovo/thinkpad/z/default.nix
=> thinkpad-z: move to hidpi module

lenovo/legion/15ach6/default.nix
Values are taken from <https://www.digitec.ch/en/s1/product/lenovo-legion-slim-7-1560-amd-ryzen-7-5800h-32-gb-1000-gb-ch-notebook-17240001?supplier=406802>
=> lenovo legion 7 slim 15ach6: add hidpi settings

raspberry-pi/4/backlight.nix, raspberry-pi/4/default.nix
This commit adds support for controlling the backlight on the official touch display for the Raspberry Pi 4. Using this overlay, the brightness on the display can be controlled using the following snippet:
```
echo "55" > /sys/class/backlight/rpi_backlight/brightness
```
=> feat: add backlight support for rpi4

raspberry-pi/4/touch-ft5406.nix
This adds the option to enable support for the [official Raspberry Pi Touch Display](https://www.raspberrypi.com/documentation/accessories/display.html).
Big thanks to @samueldr and all the others for their support in [#nixos-on-arm:nixos.org](https://matrix.to/#/#nixos-on-arm:nixos.org).
=> raspberry-pi/4: Add touch support for official 7" display.

raspberry-pi/4/default.nix
This commit removes the `rpi_backlight` driver from the list of default raspberry pi 4 kernel drivers. The driver will be loaded by the `raspberry-pi."4".backlight` overlay if it is enabled.
=> fix: remove rpi_backlight driver from rpi4 config

microsoft/surface/common/kernel/default.nix, microsoft/surface/common/kernel/linux-6.1.18/default.nix, microsoft/surface/common/kernel/linux-6.1.18/patches.nix, microsoft/surface/common/repos.nix, microsoft/surface/surface-go/default.nix
Update version 6.1 of the linux-surface kernel to 6.1.18.
=> microsoft-surface: upgrade kernel 6.1.6 to 6.1.18

raspberry-pi/4/default.nix
This option was recently added (in https://github.com/NixOS/nixos-hardware/pull/595), but the option was not exported from the RPi 4 config.
=> fix: add missing touch-ft5406 export to raspberry-pi config

common/pc/laptop/acpi_call.nix
power-profiles-daemon cannot use acpi_call. This avoids taining the kernel by installing an unnecessary kernel module.
=> Load acpi_call module only if tlp is being used

common/cpu/amd/raphael/igpu.nix, flake.nix
Adds settings that are necessary to be able to use the iGPU of AMD Raphael CPUs (Ryzen 7000-series).
Additional info:
- Ryzen 7000-series iGPU support came with 5.18 (afaik)
- Lowest, currently available LTS kernel with the needed support is 6.1, which works perfectly fine
- The latest LTS kernel is 6.2, which needs an additional kernel parameter to disable scatter/gather because it results in completely white or flashing screens (scatter/gather was introduced with 6.2)
- The current release candidates of 6.3 also need this parameter
Since I don't think it's sensible to use a specific version (in this case 6.1) I would rather just use the latest kernel and add the necessary parameter. Especially since 6.3 still needs it too.
=> Add settings for AMD Raphael iGPU

README.md, flake.nix, starfive/visionfive/v2/README.md, starfive/visionfive/v2/default.nix, starfive/visionfive/v2/firmware.nix, starfive/visionfive/v2/fix-memory-size.patch, starfive/visionfive/v2/linux-6.3.nix, starfive/visionfive/v2/linux_6_3.nix, starfive/visionfive/v2/opensbi.nix, starfive/visionfive/v2/sd-image-installer.nix, starfive/visionfive/v2/sd-image.nix, starfive/visionfive/v2/spl-tool.nix, starfive/visionfive/v2/uboot.nix
This PR add support for Starfive Visionfive 2 development board.
It uses the `JH7110_VisionFive2_upstream` kernel from Starfive. This kernel has support for only a minimal amount of hardware features (no display, ...). The SD-Image works without having to flash a new bootloader :).
I tested the README example.
=> Add Starfive Visionfive 2

hardkernel/odroid-hc4/default.nix
Source for the fancontrol config mentions that one of the lines should be deleted for the 5.15 kernel.
Fixes #616.
I tested on 5.15 only, sadly couldn't test other versions. I verified that `fancontrol` runs successfully and also that its config file is as expected. Also ran `./tests/run.py '<nixos-hardware/hardkernel/odroid-hc4>'`.
=> hardkernel/odroid-hc4: fix fancontrol on 5.15 kernel

README.md, tests/build-profile.nix
This was an oversight in https://github.com/NixOS/nixos-hardware/pull/556
=> nxp boards: also test evaluation in CI

nxp/common/modules.nix, nxp/common/overlay.nix, nxp/imx8qm-mek/default.nix
With overlays one cannot re-use nixpkgs across different machines, which is a performance issues. In this instance it's not really needed. Also each overlay is an expensive copy of all top-level packages.
cc @unbel13ver
=> nxp-imx8: drop kernel overlay

samsung/np900x3c/default.nix
=> samsung/np900x3c: drop deprecated synaptics

README.md, flake.nix, hp/elitebook/845/g9/default.nix
Added HP Elitebook 845 G9.
Changes in the README are simply whitespace to realign the columns.
I am consuming this as a flake directly from this branch in my fork.
=> Add HP Elitebook 845g9

common/cpu/amd/pstate.nix
AMD pstate now supports the active mode which is more efficient for power management.
This is active from linux 6.3 kernel
=> change default pstate mode for AMD cpus

raspberry-pi/4/backlight.nix, raspberry-pi/4/default.nix, raspberry-pi/4/modesetting.nix, raspberry-pi/4/poe-hat.nix, raspberry-pi/4/poe-plus-hat.nix
fixes #626
This updates the `poe` dts overlays to work with the newer kernel (6.1) on `nixpkgs` master.
~~I am unsure on how to keep `nixos-hardware` and `nixpkgs` in sync here. I suspect this update will break existing configs which aren't updated to `nixpkgs` master..~~
~~I also haven't tested the updated config on my raspberry pi 4, yet. But the config builds and _should_ work~~
EDIT:
With the assertion this PR should at least warn and not build with an incompatible kernel. 
I have also just tested this PR on my RP4b and the fan of the POE hat works without issues.
=> raspberry-pi."4": update poe hat overlay to work with newer kernel

focus/m2/gen1/default.nix
On older kernels up to 5.15.111 I was seeing this message:
```
[Firmware Bug]: TPM interrupt not working, polling instead
[    3.356315] irq 31: nobody cared (try booting with the "irqpoll" option)
```
Since, apart from that there was no other issues I ignored it.
After 5.15.111 kacpid worker thread started to consume 100% CPU. 
Disabling pooling fixes that issue. 
Upstream bug:
https://bugzilla.kernel.org/show_bug.cgi?id=204121
=> [FocusGen1M2] Disable TPM interrupt due to upstream bug

lenovo/thinkpad/x1/6th-gen/default.nix
According to https://wiki.archlinux.org/title/Lenovo_ThinkPad_X1_Carbon_(Gen_6)#Using_thermald, using newer thermald + newer kernel (which we have since 22.11) should be enough to workaround the throttling issue. `thermald` comes from intel and it seems to be better maintained than `throttled`, so I propose we switch to that.
=> lenovo-thinkpad-x1-6th-gen: swap throttled with thermald

README.md, flake.nix, hp/notebook/14-df0023/default.nix
Add new hardware configuration for the HP Notebook 14-df0023, my main machine.
Hardware spec: https://support.hp.com/us-en/document/c06166782
=> hp.14-df0023: init

starfive/visionfive/v2/README.md, starfive/visionfive/v2/firmware.nix, starfive/visionfive/v2/sd-image.nix
Add scripts to update the bootloader on the sd card or the QSPI flash.
The QSPI flash update script will only work when #630 and #646 is merged.
=> starfive visionfive2: Add firmware update script.

README.md, flake.nix, microchip/README.md, microchip/common/bsp/hss-payload-generator.nix, microchip/common/bsp/linux-icicle-kit.nix, microchip/common/bsp/patches/0001-Boot-environment-for-Microchip-Iciclle-Kit.patch, microchip/common/bsp/uboot.nix, microchip/common/bsp/uboot.yaml, microchip/common/modules.nix, microchip/common/overlay.nix, microchip/icicle-kit/default.nix, microchip/icicle-kit/overlay.nix
* Uses Linux kernel released by Microchip
- https://github.com/linux4microchip/linux.git
- Ver: v5.15   Tag: linux4microchip+fpga-2023.02
* Uses UBoot released by Microchip
- Ver: uboot-2022-01 Tag: linux4microchip+fpga-2023.02
To generate NixOS sd image for MICROCHIP icicle-kit refer:
https://github.com/tiiuae/ghaf.git
- [y] Tested the changes in your own NixOS Configuration
- [y] Tested the changes end-to-end by using your fork of `nixos-hardware` and
=> Add Microchip Icicle-kit board support.

README.md, flake.nix, pine64/star64/README.md, pine64/star64/default.nix, pine64/star64/firmware.nix, pine64/star64/irq-desc-to-data.patch, pine64/star64/linux-5.15.nix, pine64/star64/opensbi.nix, pine64/star64/pl330-name-collision.patch, pine64/star64/sd-image-installer.nix, pine64/star64/sd-image.nix, pine64/star64/spl-tool.nix, pine64/star64/star64-8GB.dts, pine64/star64/uboot.nix
Mostly based on the visionfive 2 config.
No GPU yet.
Sample image built directly on the board: https://app.cachix.org/api/v1/cache/fgaz/serve/hj72i7znp0rvc4dxs2xslw6b3ik3wifb/sd-image/nixos-sd-image-23.11pre-git-riscv64-linux-pine64-star64.img.zst (8GB RAM, user/pw: nixos)
=> star64: init

common/gpu/nvidia/disable.nix
Hello
This is a minor addition to /common/gpu/nvidia/disable.nix which adds more kernel modules to block: `nvidia_drm` and `nvidia_modeset`:
```nix
boot.blacklistedKernelModules = lib.mkDefault [ "nouveau" "nvidia" "nvidia_drm" "nvidia_modeset" ];
```
Today I wanted to fully disable my Nvidia dGPU on an Optimus laptop. I added the setup seen in the current disable.nix to my configuration.nix but it didn't work, my Nvidia dedicated GPU was still active and rampant on power consumption. I added these 2 more modules to the blacklist and this completely fixed the issue and now my dedicated GPU is fully disabled.
=> Added more blocked Nvidia kernel modules to fix the dGPU not being disabled

starfive/visionfive/v2/default.nix, starfive/visionfive/v2/linux-6.4.nix, starfive/visionfive/v2/verisilicon.patch
=> starfive visionfive2: update kernel to 6.4.0

apple/macbook-air/6/default.nix
This does not compile against 6.x Kernel.
This is also no longer necessary for 6.x Kernel.
One can use "acpi_video0" device instead of "mba6x_backlight" device.
Remove mba6x_backlight kernel module.
=> macbook-air-6: remove mba6x_bl kernel module

README.md, apple/t2/README.md, apple/t2/default.nix, apple/t2/fix-keyboard-backlight-and-touchbar.sh, apple/t2/pkgs/linux-t2.nix, flake.nix
This pull request adds all changes from https://github.com/kekrby/nixos-hardware as well as an update to the most recent kernel and a fix for keyboard backlight not working after suspend, making Apple Intel Macs with the T2 security chip quite usable overall.
=> apple/t2: init

microsoft/surface/common/ipts/default.nix
Added "iptsd-find-hidraw" after iptsd command so that it can automatically detech the current device on the system for ipts.
When building the system with current iptsd service, it gives error of needing a DEVICE for iptsd.service. This should fix that issue and automatically detech + enable the correct device.
Added $(iptsd-find-hidraw)
- [ x ] Tested the changes in your own NixOS Configuration
=> fixing iptsd not able to find DEVICE

common/gpu/intel/default.nix, gpd/pocket-3/default.nix
Fixes configs with `nixpkgs.config.allowAliases = false` after NixOS/nixpkgs#235202
I couldn't find any prior art in the repo for package aliases based on NixOS version, so let me know if there is a better/more preferred way to handle this
=> treewide: avoid alias usage for intel-vaapi-driver based on nixos version

lenovo/legion/15ach6/default.nix
This keeps breaking with kernel patches. There seems to be no real pattern. I'll maintain this myself on my config.
=> lenovo legion 7 slim 15ach6: remove brightness service

apple/t2/pkgs/linux-t2.nix
Updates the Linux kernel to 6.4.2, patches stay unchanged.
=> apple/t2: update to kernel 6.4.2

README.md, flake.nix, lenovo/legion/16irx8h/default.nix
added 16IRX8H Lenovo Legion 7i Pro (2023)
nvidia is disabled as hyprland fails and that is what i use in my system. if there are specific request i can test more. 
Tested on my own flake with referencing my own nixos-hardware fork locally. 
=> added 16IRX8H Lenovo Legion 7i Pro (2023)

microchip/common/bsp/patches/0002-Riscv-Fix-build-against-binutils-2.38.patch, microchip/common/bsp/uboot.nix
Fix for https://github.com/NixOS/nixpkgs/issues/235179 
Update Microchip uboot version to linux4microchip+fpga-2023.06
Patch for Microchip uboot, which fixes build issue against binutils 2.38
From version 2.38, binutils default to ISA spec version 20191213. This
means that the csr read/write (csrr*/csrw*) instructions and fence.i
instruction has separated from the `I` extension, become two standalone
extensions: Zicsr and Zifencei. As the kernel uses those instruction,
this causes build failure.
- [OK] Tested the changes in your own NixOS Configuration
- [OK] Tested the changes end-to-end by using your fork of `nixos-hardware` and
=> Microchip uboot build failure with nixpkgs 23.05

asus/zephyrus/ga402/default.nix
I previously added those flags but it was an error. The `acpi.prefer_micosoft_dsm_guide` was handled correctly by the kernel when they fixed the fan behaviour and the `pcie_aspm.policy` shall be handled by scripts or tools like TLP.  
=> ga402: remove useless kernel flags

README.md, deciso/dec/default.nix, flake.nix
Enables serial console output and getty for the headless [Deciso DEC2750](https://shop.opnsense.com/product/dec2750-opnsense-rack-security-appliance/). The unit ships stock with opnsense but I was able to install NixOS without much trouble after applying roughly this patch to build preconfigured install media.
Since all of the DEC series have a console port with a USB-to-serial chip built in I figure it is probably fine to name this `deciso/dec` rather than `deciso/dec2750`, but I don't have strong feelings on the topic either.
```
[matt@routnerr-3:~]$ neofetch 
▗▄▄▄       ▗▄▄▄▄    ▄▄▄▖            matt@routnerr-3 
▜███▙       ▜███▙  ▟███▛            --------------- 
▜███▙       ▜███▙▟███▛             OS: NixOS 23.05.2064.53657afe297 (Stoat) x86_64 
▜███▙       ▜██████▛              Host: …
```
=> deciso/dec: init, tested with DEC2750

lenovo/thinkpad/p14s/amd/gen2/default.nix, lenovo/thinkpad/t14s/amd/gen1/default.nix
=> p14s, t14s: fix linux firmware version check

gpd/pocket-3/default.nix
It seems S3 works on NixOS without this option now. I have tested this on NixOS 22.11/23.05, without issues.
Removing this option ensures better battery life whilst the UMPC is in sleep mode, and reduces the chances of overheating whilst in transit.
All tests have passed, save for these four:
```shell
The following 4 test(s) failed:
./tests/run.py '<nixos-hardware/raspberry-pi/4>'
./tests/run.py '<nixos-hardware/asus/zephyrus/ga402>'
./tests/run.py '<nixos-hardware/asus/zephyrus/ga401>'
./tests/run.py '<nixos-hardware/lenovo/legion/16irx8h>'
```
=> GPD-P3: Remove S2 sleep kernel param, use S3 instead

lenovo/thinkpad/p14s/amd/gen2/default.nix
This is my first upstream contribution (intend to contribute configs for
my NUC, GPD, and ClockworkPi devices). Essentially, this change
resolves https://github.com/NixOS/nixos-hardware/issues/492, by adding the `common/{cpu,gpu}/amd` Nix fragments to the
`imports` list for the Thinkpad P14s.
I have not been able to test these changes in my own configuration, but I have run the unit tests, which passed, save for the following tests, listed below:
```shell
The following 4 test(s) failed:
./tests/run.py '<nixos-hardware/raspberry-pi/4>'
./tests/run.py '<nixos-hardware/asus/zephyrus/ga402>'
./tests/run.py '<nixos-hardware/asus/zephyrus/ga401>'
./tests/run.py '<nixos-hardware/lenovo/legion/16irx8h>'```
=> p14s: Add common/{cpu,gpu}/amd to imports

README.md, framework/13th-gen-intel/README.md, framework/13th-gen-intel/default.nix, framework/README.md
Clarify 13th Gen Intel Core support. The chipsets and mainboard are similar
enough that no separate configuration is needed.
=> framework: Clarify 13th Gen Intel Core support

README.md, dell/xps/13-9333/README.wiki, dell/xps/13-9333/default.nix, flake.nix
Note1: In the `default.nix` file, I [imported](https://github.com/ttamttam/nixos-hardware/blob/df6673231f19e091b3202b1815b3531150a49fa8/dell/xps/13-9333/default.nix#L5) 
`../../../common/pc/ssd` because my laptop has currently an SSD, but
I'm not sure if it was the case when I bought it or if I installed it later.
Note2: Not sure about this [line](https://github.com/ttamttam/nixos-hardware/blob/df6673231f19e091b3202b1815b3531150a49fa8/dell/xps/13-9333/default.nix#L14) (`services.fwupd.enable = true;`).
=> Adding Dell XPS 13 9333

apple/t2/pkgs/linux-t2.nix
Update the linux kernel with t2 patches to 6.4.8
=> apple/t2: update to kernel 6.4.8

starfive/visionfive/v2/default.nix, starfive/visionfive/v2/linux-6.5.nix
=> starfive visionfive2: update kernel to 6.5.0-rc1

starfive/visionfive/v2/default.nix, starfive/visionfive/v2/qspi-patch.dts
This fixes the issue that the SPL is larger than the flash partition. This simply increases the partition to fit the slightly larger SPL.
This depends on #630.
Related PR upstream https://github.com/starfive-tech/linux/pull/99.
=> starfive visionfive2: Increase mtd0 partition to fit spl

common/gpu/nvidia/disable.nix
Adjust Nvidia disable module to match with CONTRIBUTING.md guidelines. Specifically to remove lib.mkDefault on options we would want to allow merging user config with.
Another PR performing this change treewide may be beneficial.
Related to #691 
Fixes #607 
=> common/nvidia disable: Remove `lib.mkDefault`

dell/xps/15-9560/default.nix, dell/xps/15-9560/xps-common.nix
Adjust XPS 9560 module to match with CONTRIBUTING.md guidelines. Specifically to remove `lib.mkDefault` on options we would want to allow merging user config with.
Related to #607 
=> XPS 9560: Remove `lib.mkDefault` on mergable options

README.md, flake.nix
This applies @Mic92's edit suggestions from https://github.com/NixOS/nixos-hardware/pull/675#discussion_r1278526926, fixing the README link and adding a flake.nix field for 13th-generation Intel-based Framework laptops.
=> Apply Mic92's suggestions re Framework 13th gen

pine64/star64/README.md
=> star64: remove unused flake input from README

apple/t2/pkgs/linux-t2.nix
Update the linux kernel with t2 patches to 6.4.9
=> apple/t2: update to kernel 6.4.9

raspberry-pi/4/modesetting.nix
Fixes #631
This should work with both nixos-23.05 and nixos-unstable
=> raspberry-pi/4: fix modesetting on 6.1 kernels

starfive/visionfive/v2/opensbi.nix
=> starfive visionfive2: use stable opensbi release

dell/xps/15-9560/README.wiki, dell/xps/15-9560/default.nix, dell/xps/15-9560/intel/default.nix, dell/xps/15-9560/nvidia/default.nix, dell/xps/15-9560/xps-common.nix
Added information about hardware functionality and solutions I have discovered:
- Firmware updates with `fwupd`
- System control with `libsmbios`
- TPM 2.0 functions not working (with solutions)
- Note on secure boot functionality
- Note on using the TPM to unlock root drive
And some configuration changes:
- Do not use `lib.mkDefault` for the GPU IDs. User should not need to change this and this will prevent accidentally changing it.
- Import the `common/cpu/intel/kaby-lake` configuration for intel and bumblebee configurations
=> Dell XPS 9560: Add info to README and adjust configuration

apple/t2/pkgs/linux-t2.nix
Update the linux kernel with t2 patches to 6.5
=> apple/t2: update to kernel 6.5

README.md, common/cpu/intel/elkhart-lake/default.nix, common/cpu/intel/jasper-lake/default.nix, flake.nix, hardkernel/odroid-h3/default.nix
Added intel Jasper and Elkhart lake common options: 
* Based on this documentation: https://jellyfin.org/docs/general/administration/hardware-acceleration/intel/#known-issues-and-limitations
* other relevant ticket: https://gitlab.freedesktop.org/drm/intel/-/issues/8080
Add initial support for odroid-h3 hardware:
* This should work for both odroid-h3 and h3+ as they both have a jasper
lake CPU (N5105 and N6005).
* I tested this only on a odroid h3+
=> Add initial support for Odroid h3/h3+

microsoft/surface/common/default.nix, microsoft/surface/common/kernel/default.nix, microsoft/surface/common/kernel/linux-6.4.12/default.nix, microsoft/surface/common/kernel/linux-6.4.12/patches.nix, microsoft/surface/common/repos.nix
- Adds kernel 6.4.12 with linux-surface patches
- Changes default `microsoft-surface.kernelVersion` to 6.4.12
- Tested on Surface Laptop 4 AMD
- Not tested on other surface devices
- Other kernel versions (6.1, etc) not tested
=> surface: add kernel 6.4.12

CODEOWNERS
I forgot to add myself when I added the module
=> Add fgaz to star64 codeowners

README.md, flake.nix, friendlyarm/nanopi-r5s/default.nix
Add an initial bootable configuration for the [FriendlyElec/FriendlyARM NanoPi R5s](https://wiki.friendlyelec.com/wiki/index.php/NanoPi_R5S). This config comes from https://github.com/inindev/nanopi-r5/issues/11#issue-1789308883 which I expanded a little bit in my [blog post](https://alanpearce.eu/post/nixos-on-nanopi-r5s/).
=> friendlyarm/nanopi-r5s: init config

microsoft/surface/common/kernel/linux-6.1.18/patches.nix
[The latest version of linux-surface](https://github.com/linux-surface/linux-surface/tree/7eb766437ef4bea52900e177a2bee86d4b4908b5/patches/6.1) does not contain 0015-intel-thread-director.patch. This was breaking the 6.1.x kernel build like so:
```
> Hunk #3 succeeded at 1314 (offset -5 lines).
> patching file arch/x86/kernel/acpi/boot.c
> Hunk #1 succeeded at 1250 (offset -5 lines).
> applying patch /nix/store/paasl6sbph09j5vm169307k2qzmrwd5c-source/patches/6.1/0014-rtc.patch
> patching file drivers/acpi/acpi_tad.c
> applying patch /nix/store/paasl6sbph09j5vm169307k2qzmrwd5c-source/patches/6.1/0015-intel-thread-director.patch
> /nix/store/vfdg65hiv4bwls48588msw8la7452w2q-stdenv-linux/setup: line 1216: /nix/store/paasl6sbph09j5vm169307k2qzmrwd5c-source/patches/6.1/0015-intel-thread-directo …
```
=> surface: Fix kernel 6.1.18 by removing 0015-intel-thread-director.patch

framework/default.nix
Change `mem_sleep_default=deep` kernel parameter to `acpi_osi="!Windows 2020"` (fixes a regression in s2idle, making it more power efficient than deep sleep). It's also a good idea to get rid of deep sleep on the 11th gen anyway, as it doesn't function correctly and takes 10-15 seconds to wake back up.
I haven't tested it using my own fork, as I just started using NixOS yesterday, but I've been using this kernel parameter on my Arch Linux install for a while now.
=> framework laptop 11th gen: Improve sleep power efficiency

asus/zephyrus/ga401/default.nix
Mapped fn+LeftArrow to be home key and fn+RightArrow to be end key.
The Asus Zephyrus GA401 does not have any home end functionality originally.
=> asus/zephyrus/ga401: fix keymapping

raspberry-pi/4/default.nix, raspberry-pi/4/xhci.nix
Implemented a device tree overlay to enable XHCI controller on Raspberry Pi 4 family. Useful for CM4 when dwc2 is not applicable due to lower performance.
Not sure why it is disabled by default, but upon comparing device trees of fresh Raspberry Pi OS Lite and NixOS, the status was "disabled" on NixOS and "okay" on RPi OS. This may be due to some trickery in closed source RPi bootloader
Imported from my own configuration: https://github.com/truelecter/hive/blob/master/cells/nixos/hosts/voron/_hardware-configuration.nix#L63-L90
=> Implement dt overlay for enabling built-in XHCIcontroller

pine64/star64/opensbi.nix
Same as 7f1836531b126cfcf584e7d7d71bf8758bb58969
=> star64: use stable opensbi release

pine64/star64/default.nix
initramfs was missing a bunch of modules
=> star64: fix boot from eMMC

.mergify.yml, bors.toml
bors no longer works for merge queues.
=> replace bors with mergify

tests/build-profile.nix
There seems to be recursive dependencies between adding video drivers and checking if the unfree flag is set.
=> build-profile: also accept nvidia license

tests/build-profile.nix
=> tests: set linux_latest as the default kernel

README.md, flake.nix, omen/15-en0010ca/README.md, omen/15-en0010ca/default.nix
~~The required modules not yet set to compile on Nixpkgs provided Kernels as of right now (See [the relevant PR](https://github.com/NixOS/nixpkgs/pull/255846)).~~
~~I've commented the relevant config out before the PR merges.~~
Added support for my laptop, a HP Omen 15 (2020). 
=> Add Omen 15-en0010ca

framework/12th-gen-intel/default.nix, framework/default.nix
This adds a patched ectool, to interact with the Embedded Controller
Can be used to interact with leds from userspace, etc. Not part of a nixos release yet, so package only gets added if it exists.
=> framework/*: add fw-ectool for led control, etc

README.md, flake.nix, lenovo/thinkpad/x1/11th-gen/default.nix
Adding Thinkpad X1 11th Gen.
Got id from:
```bash
$ nix-shell -p pciutils --run 'lspci -nn | grep VGA'
00:02.0 VGA compatible controller [0300]: Intel Corporation Raptor Lake-P [Iris Xe Graphics] [8086:a7a1] (rev 04)
```
=> Thinkpad X1 11th Gen: init

CODEOWNERS
Add self as an owner for pine64/pinebook-pro. My goal is to eventually remove all PineBook Pro config from nixos-hardware! :)
Prior contributions:
* https://github.com/NixOS/nixos-hardware/pull/444
* https://github.com/NixOS/nixos-hardware/pull/445
* https://github.com/NixOS/nixos-hardware/pull/446
Pending contributions:
* https://github.com/NixOS/nixos-hardware/pull/743
=> CODEOWNERS: add tomfitzhenry to Pine64 Pinebook Pro

pine64/star64/default.nix
By default it's "performance", which is not ideal.
Not sure if this belongs to nixos-hardware though.
=> star64: set governor to schedutil

README.md, dell/xps/15-9510/README.wiki, dell/xps/15-9510/default.nix, dell/xps/15-9510/nvidia/default.nix, flake.nix
=> chore: Add DELL XPS 9510

README.md, flake.nix, omen/16-n0005ne/README.md, omen/16-n0005ne/default.nix
Added profile for AMD only variant of the omen 16 line of HP laptops.
Currently this profile is almost identical to existing omen 15 profile but without any NVIDIA modules. 
=> init: omen-16-n0005ne

omen/15-en0010ca/default.nix, omen/15-en1007sa/default.nix, omen/16-n0005ne/default.nix, omen/en00015p/default.nix
AMD PState was missing as an import for Omen devices. This should improve batter life of the devices.
=> Add amd pstate to all omen laptops

README.md, asus/ally/rc71l/README.md, asus/ally/rc71l/default.nix, flake.nix
Added basic configuration for the ROG Ally RC71L (2023), based on what I have been using so far.
=> ROG Ally: Add basic config as default.nix

purism/librem/5r4/kernel/6.5.4.nix, purism/librem/5r4/kernel/default.nix, purism/librem/5r4/kernel/kernel.nix
Update the linux kernel to the latest release on https://source.puri.sm/Librem5/linux
=> purism/librem5r4: linuxPackages_librem5: 6.4.14-librem5 -> 6.5.6-librem5

pine64/rockpro64/default.nix
Controls the fan so it doesn't spin at full force after installation.  
rk3399's operating temps are -20 to 80°C. It has sensors for CPU and GPU. The MINSTART/-STOP values are a result of my own testing.  
Tested my fork without any changes and with `hardware.fancontrol.enable = false;` to disable it.
=> pine64-rockpro64: add fancontrol

README.md, asus/rog-strix/g513im/default.nix, flake.nix
Added a new profile for the Asus ROG Strix G513IM laptop.
=> Add Asus ROG Strix G513IM

README.md, flake.nix, hp/elitebook/845/g7/default.nix
Add configuration for HP Elitebook 845 g7
=> Add HP Elitebook 845 g7 configuration

pine64/star64/linux-5.15.nix
It was enabled in this nixpkgs commit:
https://github.com/NixOS/nixpkgs/commit/e00c606455cef66797d48b3a145e913b509a4077
=> star64: linux: force disable DRM_FBDEV_EMULATION

README.md, asus/zephyrus/gu603h/default.nix, flake.nix
Adds configs for the Asus ROG Zephyrus M16, model GU603H. My specific model is listed as a GU603HM, but I think other laptops in the same series would work too.
=> feat(asus/zephyrus): add GU603H (2021 Zephyrus M16)

framework/default.nix, microsoft/surface/default.nix
When importing deprecated modules `microsoft/surface/default.nix` and `framework/default.nix`, a link is shown to a markdown document guiding the user to import the new modules. These links are broken because they point to a non-existent `OLD-BEHAVIOUR-DEPRECATED.md`. This patch fixes them to point to the existing `OLD-BEHAVIOUR-DEPRECATION.md` documents.
=> Fixed broken links in deprecation assertions for framework and surface modules

starfive/visionfive/v2/default.nix, starfive/visionfive/v2/linux-6.6.nix
=> starfive visionfive2: update kernel to 6.6.0

raspberry-pi/4/default.nix, raspberry-pi/4/leds.nix
because the `boot.loader.raspberryPi.firmwareConfig` will be deprecated, others might want to disable the LEDs. Found in:
https://gist.github.com/SFrijters/206d2c09656affb04284f076c75a1969
=> raspberry-pi/4: add LED-disable overlay

framework/13-inch/12th-gen-intel/default.nix
Fixing EC crashes during sleep for FW13 12th gen Intel by blacklisting cros_ec_lpcs. Not sure about other generations. 
Tested it on my hardware for a month.
=> framework/13-inch/12th-gen-intel: ec crash fix

microsoft/surface/common/repos.nix
(First contribution to this repo) 
Bump the [linux-surface](https://github.com/linux-surface/linux-surface) version to the most recently [tagged release](https://github.com/linux-surface/linux-surface/releases/tag/arch-6.6.1-1).
Confirmed system comes up and without any noticable regressions using [this NixOS](https://github.com/iwanders/nixos-surface/blob/67fe8d0b35c2b04b1cc17b84b7c1c506940456dd/flake.nix#L4) configuration on an Surface Pro 9.
=> Bump linux-surface to a6eafcad32dc789ae92f42636b11e9aae6e7c879.

framework/13-inch/common/amd.nix
This fixes a bug that affects Framework AMD Ryzen laptops, also documented on the Arch wiki here: https://wiki.archlinux.org/title/Framework_Laptop_13#Suspend-then-hibernate_on_AMD_version
It looks like the patch has been merged to rtc-next, so should be present starting in Linux 6.8.
=> FW13 7040: workaround for SuspendThenHibernate bug

microsoft/surface/common/ipts/default.nix, microsoft/surface/common/repos.nix
Allow writing the [iptsd.conf](https://github.com/linux-surface/iptsd/blob/v1.4.0/etc/iptsd.conf) file from the nixos configuration.
So this allows specifying properties like [this](https://github.com/iwanders/nixos-surface/blob/f746cb6e58f81c9357aea6b4946e95c4016e8129/configuration.nix#L56-L61);
```nix
microsoft-surface.ipts.enable = true;
microsoft-surface.ipts.config = {
DFT = {
PositionMinMag = 500;
ButtonMinMag = 20000;
};
};
```
Which then results in:
```
[root@papyrus:/etc/nixos]# cat /etc/iptsd/iptsd.conf 
[DFT]
ButtonMinMag=20000
PositionMinMag=500
```
Which is then used by iptsd.
Also changed the rev from #787 to a tag.
Tested with [this config](https://github.com/iwanders/nixos-surface/blob/f746cb6e58f81c9357aea6b4946e95c4016e81 …
=> Linux surface give iptsd configurable options.

framework/13-inch/common/intel.nix
Disables an unused module that otherwise outputs an error log on bootup.
See https://community.frame.work/t/responded-linux-kernel-errors-about-cros-usbpd-charger/26264
I've had this disabled on 11th gen, and when upgraded it to 13th gen, still had log without it. I have not tested 12th gen but I assume it is the same.
=> framework intel: Disable cros-usbpd-charger

microsoft/surface/common/kernel/linux-6.1.x/default.nix, microsoft/surface/common/kernel/linux-6.5.x/default.nix
It's annoying to change `microsoft-surface.kernelVersion` every time it gets bumped. This should make it so you can specify the major version and it will always bump itself.
Running `nixos-rebuild build --flake github:ifd3f/infra/surface-major-version#shai-hulud` (which depends on my fork, but [sets `kernelVersion` to `"6.1"`](https://github.com/ifd3f/infra/commit/579ac8aba297d0f8f58f6c0f59eee3beb4521ef9)) successfully evaluated. I did not perform a full build.
=> surface: Allow specifying major versions for kernel

README.md, flake.nix, lenovo/ideapad/s145-15api/default.nix
Blacklist ideapad-laptop kernel module because it keeps messes with rfkill devices 
Specify which model snd-hda-intel should use, because without it external microphones won't work
- [ X ] Tested the changes in your own NixOS Configuration
- [ X ] Tested the changes end-to-end by using your fork of `nixos-hardware` and
=> Add support for lenovo idapad s145 15api laptop

microsoft/surface/common/default.nix, microsoft/surface/common/kernel/default.nix, microsoft/surface/common/kernel/linux-6.6.x/default.nix, microsoft/surface/common/kernel/linux-6.6.x/patches.nix, microsoft/surface/common/repos.nix
- linux: 6.5.11 -> 6.6.6
- linux-surface: arch-6.6.1-1 -> arch-6.6.4-1
- Update config for 6.6
- Tested on Surface Laptop 4 AMD
=> surface: linux 6.5.11 -> 6.6.6

README.md, flake.nix, gpd/win-max-2/2023/default.nix, gpd/win-max-2/default.nix
=> gpd-win-max-2-2023: init

microsoft/surface/common/default.nix, microsoft/surface/common/kernel/linux-6.6.x/default.nix, microsoft/surface/common/repos.nix
* surface: linux 6.6.6 -> 6.6.8
* linux-surface: arch-6.6.4-1 -> arch-6.6.6-1
* Tested on Surface Laptop 4 AMD
=> surface: linux 6.6.6 -> 6.6.8

purism/librem/5r4/kernel/kernel.nix
=> purism librem5r4: linuxPackages_librem5: 6.5.6-librem5 -> 6.6.6-librem5

README.md, dell/latitude/7390/default.nix, flake.nix
Adds a Nix module for the `Dell Latitude 7390` hardware.
importing it via `<nixos-hardware>` or Flake input - Completed and works
see (https://github.com/dominicegginton/dotfiles/commit/38fc4d2d66713fa08c32e5a85d938f06b642f5a6)
=> feat: add dell latitude 7390 module

common/cpu/amd/raphael/igpu.nix, flake.nix, lenovo/legion/16aph8/README.md, lenovo/legion/16aph8/default.nix
Added support for Lenovo Legion Slim 5 (16APH8)
Added PPD after researching the Framework laptops with AMD 7000 series
=> Added support for Lenovo Legion Slim 5 (16APH8)

starfive/visionfive/v2/firmware.nix, starfive/visionfive/v2/opensbi.nix, starfive/visionfive/v2/sd-image.nix, starfive/visionfive/v2/uboot.nix
=> starfive visionfive2: use upstream u-boot v2024.01-rc5

framework/13-inch/7040-amd/README.md
These are copied from the 13th-gen intel Framework README.
The steps are the same and they worked on my machine.
=> framework AMD 7040: add instructions on how to update fingerprint fw

microsoft/surface/common/kernel/linux-6.6.x/default.nix
This was missing as an option.
=> surface: Add majorVersion option to 6.6.x enum

framework/13-inch/common/default.nix
A kernel fix landed in https://github.com/torvalds/linux/commit/33038efb64f7576bac635164021f5c984d4c755f, which is in >= v6.7-rc5 and CC’ed to stable, so part of 6.6.8 too.
=> framework amd: apply headset mic fix on older kernels

microchip/common/bsp/linux-icicle-kit.nix, microchip/common/modules.nix
This change was mostly done, because in my NixOS configuration, I want to be able to use `boot.kernelPatches` to enable kernel options and patch the kernel.
* Improve by changing from legacy extraConfig to the structuredExtraConfig style kerenl configuration.
* Remove few unneeded kernel modules from default configuration.
* Make kernelPatches, structuredExtraConfig and extraMeta overrideable.
* Change callPackage-style function to actually take the individual attributes from pkgs.
* Get rid of recursive syntax.
=> microchip icicle-kit: Fixes to kernel

framework/13-inch/7040-amd/README.md, framework/13-inch/7040-amd/default.nix
A workaround has been [upstreamed](https://github.com/torvalds/linux/commit/a55bdad5dfd1efd4ed9ffe518897a21ca8e4e193) in Linux v6.7
=> framework amd: only apply suspend workaround on <6.7

dell/xps/15-9560/default.nix
Looks like it fails to evaluate in nixpkgs just now
cc @thiagokokada @danielstaleiny 
=> xps-15-9560: disable broken bumblebee for now

microsoft/surface/common/kernel/linux-6.6.x/default.nix, microsoft/surface/common/kernel/linux-6.6.x/patches.nix
As discussed here: https://github.com/NixOS/nixos-hardware/issues/523
1) `structuredExtraConfig` is called `extraStructuredConfig` when using `kernelPatches`.
2) `STREAMING_MEDIA` should be `STAGING_MEDIA`.
Since the kernel configs now are actually read, an error is thrown if any of the configs in `patches.nix` are unused, so `ignoreConfigErrors=true;` must be added to `default.nix` to make sure it builds either way.
With these changes the cameras on my Surface book 2 are recognized.
=> Make so that kernel configs are actually read when compiling for microsoft surface devices.

asus/zephyrus/ga401/default.nix
I have encountered a strange problem a long time ago.
If I put my laptop to sleep and wake it up again, it will go back to sleep a few seconds after waking up. If I wake it up again immediately, everything will be normal.
I always thought it was some bios bug or hardware issues, so I had no idea what to do.
Recently, I wanted to try the open source nvidia driver, so I read the nixos module for nvidia.
And I found [this](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/nixos/modules/hardware/video/nvidia.nix#L491).
Its specific documentation is [here](https://download.nvidia.com/XFree86/Linux-x86_64/435.17/README/powermanagement.html).
NVIDIA said this interface is still considered experimental and not used by default.
And after turning it off, the problem disappeared.
I can't confirm …
=> Disable `hardware.nvidia.powerManagement.enable`

dell/inspiron/5515/default.nix
since the update to 23.11, the screen would remain black frequently on boot. Pressing alt+sysrq+k would make the display manager start. Empirically, setting early kms up has solved the issue. I've been using this setting for about a month.
=> dell inspiron 5515: add early kms

lenovo/legion/16ach6h/README.md, lenovo/legion/16ach6h/default.nix, lenovo/legion/16ach6h/edid/default.nix, lenovo/legion/16ach6h/hybrid/default.nix
A few commits to fix various annoyances I had with the config.
Fixes #628 and #795
Before merging I'd like to discuss the following the various people using this config the fact that the currently selected `amdgpuBusId = "PCI:06:00:0"` will only work for people who have two drives installed, while those that have one need to select `PCI:05:00:0` (see also https://github.com/NixOS/nixos-hardware/issues/786#issuecomment-1890439075 for a similar case, this was also brought up to my attention a long time ago on discord with the same issue)
If I had to choose a "sane default" that would be to do `lib.mkDefault "PCI:05:00:0"` with an accompanying note to set this manually for 2 drive users, but I wanted to hear your thoughts about it.
^ cc @LostAttractor @afreakk @piousdeer 
importing it via …
=> 16ach6h: Various fixes

gpd/win-max-2/2023/README.md, gpd/win-max-2/2023/bmi260/default.nix, gpd/win-max-2/2023/bmi260/package.nix, gpd/win-max-2/2023/default.nix
- Synchronize with upstream changes
- Remove udev rule disabling PCI wakeup. It's already fixed in linux kernel mainline and backported https://github.com/torvalds/linux/commit/805c74eac8cb306dc69b87b6b066ab4da77ceaf1
- Initialize BMI260 driver
- found in https://chromium.googlesource.com/chromiumos/platform/ec/+/master/driver/accelgyro_bmi260.h
- repacked in https://github.com/hhd-dev/bmi260
I'm not sure where the BMI260 driver should be. I don't know if there's other device with NixOS users also use the BMI260. Seems it's too niche to package in nixpkgs. So I just put it here. I'm glad to discuss it.
=> GPD Win Max 2 2023: synchronize with upstream changes, initialize BMI260 driver

nxp/common/bsp/imx-atf.nix, nxp/common/bsp/imx-mkimage.nix, nxp/common/bsp/imx-optee-os.nix, nxp/common/bsp/imx-uboot.nix
Updated repositories for NXP/imx platform.
Old repositories doesn't exist anymore.
Fixed compilation issues.
=> Update repository path for nxp/imx

README.md, asus/fa507rm/default.nix, flake.nix
Add Support for Asus TUF A15 (FA507RM)
- [ x ] Tested the changes in your own NixOS Configuration (checked)
importing it via `<nixos-hardware>` or Flake input (checked against `<nixos-hardware>` method)
=> Add support for Asus TUF A15 (FA507RM)

README.md, flake.nix, nxp/README.md, nxp/imx8mp-evk/bsp/imx8mp-atf.nix, nxp/imx8mp-evk/bsp/imx8mp-boot.nix, nxp/imx8mp-evk/bsp/imx8mp-firmware.nix, nxp/imx8mp-evk/bsp/imx8mp-linux.nix, nxp/imx8mp-evk/bsp/imx8mp-optee-os.nix, nxp/imx8mp-evk/bsp/imx8mp-uboot.nix, nxp/imx8mp-evk/default.nix, nxp/imx8mp-evk/modules.nix, nxp/imx8mp-evk/overlay.nix, nxp/imx8mq-evk/bsp/imx8mq-atf.nix, nxp/imx8mq-evk/bsp/imx8mq-boot.nix, nxp/imx8mq-evk/bsp/imx8mq-firmware.nix, nxp/imx8mq-evk/bsp/imx8mq-linux.nix, nxp/imx8mq-evk/bsp/imx8mq-optee-os.nix, nxp/imx8mq-evk/bsp/imx8mq-uboot.nix, nxp/imx8mq-evk/default.nix, nxp/imx8mq-evk/modules.nix, nxp/imx8mq-evk/overlay.nix
Added support for following NXP evaluation platform
- iMX8 MPlus 
- iMX8 MQuad 
=> NXP iMX8 MPlus and iMX8 MQuad evaluation platform support

README.md, flake.nix, msi/b550-a-pro/default.nix
Add configuration for the msi B550 a pro motherboard.
I only tested with this specific motherboard but maybe the nct6683 chip is used on other msi B550 motheroboards I did not find this information =/
Also, I managed to run tests using `./tests/run.py 'msi/b550-a-pro'` but not `./tests/run.py '<nixos-hardware/msi/b550-a-pro>'`. Have I done any mistake ?
=> Add msi B550 a pro motherboard

lenovo/legion/16ach6h/hybrid/default.nix
It seems to break extra monitor modes
I've being using an extra monitor with a resolution of 2560x1440 and a maximum refresh rate of 180Hz. However only two modes 2560x1600@165Hz and 2560x1600@60Hz are available with this configuration applied. Interestingly, my Fedora system, which does not utilize this EDID, managed to work fine, with the mode 2560x1440@180Hz available. Therefore I tried comment it out and it worked perfectly.
=> fix: comment out the edid module for legion-16ach6h

lenovo/legion/16ach6h/edid/default.nix, lenovo/legion/16ach6h/hybrid/default.nix
With the recent #890, my internal display's refresh rate is restricted to 60 hz, and without it, my external monitor doesn't display anything (likely due to forcing it to an unsupported resolution/refresh rate).
This makes both the internal display and external monitors work correctly.
@yaoshiu feel free to test
=> 16ach6h: re-enable edid for internal display only

README.md, flake.nix, lenovo/thinkpad/x13/OLD-BEHAVIOUR-DEPRECATED.md, lenovo/thinkpad/x13/amd/default.nix, lenovo/thinkpad/x13/common.nix, lenovo/thinkpad/x13/default.nix, lenovo/thinkpad/x13/intel/default.nix, lenovo/thinkpad/x13/yoga/default.nix
Add Thinkpad X13 Gen1 variant for AMD CPU, which is the model I own. https://ubuntu.com/certified/202006-27979/20.04%20LTS.
This change moves some of the config files for the Intel variant, but leaves the Flake output `lenovo-thinkpad-x13` as-is to avoid breakage.
=> Add Thinkpad X13 Gen1 AMD variant

README.md, common/cpu/intel/comet-lake/default.nix, flake.nix, protectli/vp4670/default.nix
Added support for Protectli VP4670 [1], along with a module for its CPU, which is a Comet Lake 10810U [2].
[1] https://eu.protectli.com/product/vp4670/
[2] https://ark.intel.com/content/www/us/en/ark/products/201888/intel-core-i7-10810u-processor-12m-cache-up-to-4-90-ghz.html
=> protectli vp4670

asus/zephyrus/ga401/default.nix
Dynamic boost is only supported for Ampere and would result in `nvidia-powerd` service failing to start on anything lower.
I have a G14 with 1660TI and had to disable the option with `mkForce`, which I think is pretty ugly.
[Documentation for Dynamic Boost](https://download.nvidia.com/XFree86/Linux-x86_64/515.65.01/README/dynamicboost.html)
=> ga401: use mkDefault for dynamicBoost

flake.nix, milkv/pioneer/README.md, milkv/pioneer/default.nix, milkv/pioneer/fip.nix, milkv/pioneer/firmware.nix, milkv/pioneer/linux.nix, milkv/pioneer/linuxboot-initrd.nix, milkv/pioneer/linuxboot-kernel.nix, milkv/pioneer/opensbi.nix, milkv/pioneer/sd-image-installer.nix, milkv/pioneer/sd-image.nix, milkv/pioneer/zsbl-increase-timeout.patch, milkv/pioneer/zsbl.nix
This adds initial support for the Milk-V Pioneer board. This PR adds enough functionality to create an SD card installer image using the bootflow based on LinuxBoot(u-root). I leave other functionality like EFI-based booting to another PR.
There are still some quirks left over, especially around the console output. The default vendor settings are ok if you want graphical boot, i.e. you have the complete box or otherwise used some other GPU. They are somewhat subpar if you just have the board or want to run the box headless.
Anyway here is a reference / list of things that can be improved.
- LinuxBoot will only output the boot menu on the main console which is `tty1` as per the [vendor's device tree](https://github.com/sophgo/linux-riscv/blob/e208746094f22cba0e91ed588a41d739a908a28c/arch/ri …
=> milkv/pioneer: init

microsoft/surface/common/kernel/linux-6.6.x/default.nix
Update linux to 6.6.25 for surface.
NOTE: This is not intended to replace #878, but rather to provide an updated 6.6 kernel in the meanwhile
=> surface: linux 6.6.13 -> 6.6.25

README.md, flake.nix, lenovo/legion/16arha7/README.md, lenovo/legion/16arha7/audio/lenovo-16ARHA7_speaker-fix.nix, lenovo/legion/16arha7/audio/lenovo_16ARHA7_sound_fix.patch, lenovo/legion/16arha7/default.nix
A relatively small configuration for the Lenovo Legion Slim 7 Gen 7 (AMD version) that fixes non-working speakers. This also pulls in the AMD CPU and GPU modules and sets the DPI.
importing it via `<nixos-hardware>` or Flake input (see https://github.com/8bitbuddhist/nix-configuration/commit/12e98d14a4b0ba6254838ae4b330422518fae099)
=> Add Lenovo legion 16ARHA7

common/pc/default.nix
Has been default in nixpkgs for a long time now.
=> common/pc: remove libinput.enable

README.md, flake.nix, lenovo/thinkpad/z/default.nix, lenovo/thinkpad/z/gen1/default.nix, lenovo/thinkpad/z/gen1/z13/default.nix, lenovo/thinkpad/z/gen2/default.nix, lenovo/thinkpad/z/gen2/z13/default.nix, lenovo/thinkpad/z/z13/default.nix, lenovo/thinkpad/z13/default.nix
Lenovo released a second generation of their Z series Thinkpads. This series has a 13" & 16" laptop named Z13 & Z16 respectively that runs much of the exact same hardware , so rather than splitting out `z/z13/gen1`, I thought `z/gen1/z13` made more sense (even if Z16 is missing since no one with the hardware has added it).
~~Laptop is processing & will soon be in the mail, but I had the previous model (until got fried from an unlucky voltage spike) so I’m familiar enough with the hardware (co-authoring the Gen 1 commit). Gen 2 introduced nothing new other than a newer CPU, expanding RAM to 64 GB + SSD to 2 TB; the body, screen, battery, keyboard, trackpad & rest of the IO remains the same. The newer CPU requires a higher respective Linux …
=> Lenovo ThinkPad Z13 Gen 2

README.md, apple/macmini/4/default.nix, apple/macmini/default.nix, flake.nix
Hello,
I own a very old MacMini (2010) and I had the idea to install NixOS on it 2 days ago.
I've been searching for how to make the Nvidia chipset working, and I've extracted the relevant part in this PR.
This is my first PR in this project, please let me know if this is OK.
```
❯ lspci
00:00.0 Host bridge: NVIDIA Corporation MCP89 HOST Bridge (rev a1)
00:00.1 RAM memory: NVIDIA Corporation MCP89 Memory Controller (rev a1)
00:01.0 RAM memory: NVIDIA Corporation Device 0d6d (rev a1)
00:01.1 RAM memory: NVIDIA Corporation Device 0d6e (rev a1)
00:01.2 RAM memory: NVIDIA Corporation Device 0d6f (rev a1)
00:01.3 RAM memory: NVIDIA Corporation Device 0d70 (rev a1)
00:02.0 RAM memory: NVIDIA Corporation Device 0d71 (rev a1)
00:02.1 RAM memory: NVIDIA Corporation Device 0d72 (rev a1)
00:03.0 ISA …
```
=> macmini4: init

README.md, flake.nix, tuxedo/pulse/14/gen3/README.md, tuxedo/pulse/14/gen3/default.nix
Add relevant modules for TUXEDO Pulse 14 Gen3. The device is equipped with an AMD Ryzen 7 7840HS with integrated AMD Radeon M780 iGPU.
=> TUXEDO Pulse 14 Gen3: init

common/gpu/intel/default.nix, framework/13-inch/12th-gen-intel/default.nix, framework/13-inch/common/default.nix, framework/13-inch/common/intel.nix, framework/kmod.nix
Kernel: 6.8.2
Tested with: https://github.com/NixOS/nixpkgs/pull/300781
Came across this due to backlight not restored after reboot (https://github.com/NixOS/nixpkgs/issues/178345 - wasn't related) issue and followed as I have the same issue as (https://github.com/NixOS/nixpkgs/issues/202846#issue-1464490034) 2. with the screen "flickering" (like restarting once) and then weird display issue instead like above.
With this changes and above configuration it looks like t his on initrd luks-unlock (how it should be):
Previous picture:
(Display issues on current master with i915 loaded in initrd)
Superseeds https://github.com/NixOS/nixos-hardware/pull/846 (fixed and package updated https://github.com/NixOS/nixpkgs/pull/300781)
Fixes https://github.com/NixOS/nixos-hardware/pull/897 for latest …
=> framework-12th-gen-intel: Refactor

microsoft/surface/common/kernel/linux-6.8.x/default.nix
Update linux to 6.8.9 for surface.
=> surface: linux 6.8.6 -> 6.8.9

lenovo/legion/16arha7/default.nix
(Redo of #928)
Adds support for the fingerprint reader to the Lenovo Legion Slim 7 Gen 7 AMD 16ARHA7
=> Add fingerprint support for Lenovo Legion 16ARHA7

nxp/imx8mp-evk/bsp/imx8mp-uboot.nix, nxp/imx8mq-evk/bsp/imx8mq-uboot.nix
The buildUBoot function is intended for internal use and is dedicated  for Raspberry Pi platforms. With latest nixpkgs it is causing build failure in older uboot(prior to v2023.07) due to a Raspberry Pi patch.
Now this function is not used for the U-Boot build.
More Information:
https://github.com/NixOS/nixpkgs/pull/311614
https://github.com/NixOS/nixpkgs/pull/146634
=> Remove buildUBoot function from U-Boot build

asus/fa507nv/default.nix
Some of the changes can be considered opinionated but I think all of them are needed to achieve full functionality for the device.
I added the battery module and changed the NVIDIA module to the normal NVIDIA offload instead of sync. After looking at the Arch wiki turns out AMD CPU's are also supported, unlike how its stated in the NixOS wiki. So I changed it to Offload. 
Secondly I copied 2 lines from the module of Framework 16-inch laptop. The first line fixes a issue related to AMD CPU's (Its details are included in the URL in the module) and the other one is setting up PPD for power management.
Additionally I enabled asusd service. This might be considered opinionated but without this tool functionalities like keyboard color control, fan curves etc. are not easily doable.
Finally I …
=> Revision for Asus fa507nv

flake.nix
I've added the default XPS 9570 module to the flake.nix so it's possible to use it without being locked to one of the GPU setups provided.
=> Add missing default xps-15-9570 module to flake.nix

apple/t2/pkgs/linux-t2.nix
This PR bumps the kernel version of `apple/t2` from `6.7.7` to `6.9`, and likewise for the patches repo. This might include stability fixes and so far my laptop has not crashed.
=> apple/t2: update to kernel 6.9

common/cpu/amd/zenpower.nix, flake.nix
The zenpower module provides much more detailed data than k10temp on Zen CPUs. Use it.
=> cpu/amd/zenpower: new

README.md, flake.nix, huawei/machc-wa/README.md, huawei/machc-wa/default.nix
Created a config file for Huawei Matebook X Pro (2020). This file should work on all versions other than MACHC-WAH9L as that one does not include the Nvidia MX250 dGPU.
=> Added config for Huawei Matebook X Pro (2020)

framework/16-inch/common/default.nix
in https://github.com/NixOS/nixos-hardware/pull/903 , the framework-laptop-kmod was added, and automatically setup for 13" models. The 16" model will also be able to take advantage of the kmod, once the 6.10 kernel patches are in place.
Kernel Patchset: https://lore.kernel.org/chrome-platform/20231005160701.19987-1-dustin@howett.net/
Add `kmod` import to 16" Framework `default.nix`
=> framework: Add framework-laptop-kmod for 16" model as well

lenovo/legion/16arha7/README.md, lenovo/legion/16arha7/default.nix
This adds a check to prevent installing the speaker fix if the kernel is later than 6.9. Kernel 6.9-rc3 introduced the fix for the speaker issue, so this patch shouldn't be needed.
=> Add kernel version check for Lenovo 16ARHA7 speaker fix

README.md, asus/fx506hm/README.md, asus/fx506hm/default.nix, flake.nix
I was already doing something like this in my configuration for a while and I decided it'd be best to publish it to this repo as well, so that other people can make use of it.
Sorry for going off-topic but, I was wondering, do these configs get into the hardware scan NixOS does when generating a config, or is it up to the user to manually use these?
=> Add config for ASUS TUF FX506HM

README.md, asus/zenbook/ux371/README.md, asus/zenbook/ux371/default.nix, common/cpu/intel/cpu-only.nix, common/cpu/intel/tiger-lake/default.nix, common/gpu/intel/default.nix, flake.nix
This laptop uses the tiger-lake chipset which didn't have a chipset folder, so I added it and added handling for loading the new Intel Iris Xe graphics driver over i915 if the kernel is new enough.
=> asus/zenbook/ux371: init

common/hidpi.nix
=> hidpi: drop legacy options

apple/t2/pkgs/linux-t2.nix
Updates kernel to 6.9.3 to resolve regressions reported by users. Also updates the patches repo to include the APFS module required to obtain the firmware files.
=> apple/t2: update to kernel 6.9.3

README.md, flake.nix, lenovo/ideapad/16ach6/README.md, lenovo/ideapad/16ach6/default.nix
Add configuration for the Lenovo IdeaPad 5 Pro 16ACH6 laptop. It only includes the common modules and sets up Nvidia prime.
I've been testing this on my fork for months, but just noticed I hadn't created the PR yet while upgrading to 24.05 :see_no_evil:
=> Add configuration for Lenovo IdeaPad 5 Pro 16ACH6

purism/librem/5r4/kernel.nix, purism/librem/5r4/u-boot/default.nix
this pr fixes building the librem5's version of uboot and also is a (long overdue...) update of the linux kernel version
=> purism librem5r4: kernel 6.6.6pureos1 -> 6.6.29pureos1, fix uboot

raspberry-pi/4/bluetooth.nix, raspberry-pi/4/default.nix
Bluetooth don't work on raspberry pi 4 by default with the RPI kernel. The thread https://github.com/NixOS/nixpkgs/issues/123725#issuecomment-1613705556, even referenced by [the wiki](https://wiki.nixos.org/wiki/NixOS_on_ARM/Raspberry_Pi_4), provide a `bluetooth.nix` from [lloeki](https://github.com/lloeki) that never got the chance to be merged directly into nixos-hardware. This PR just add that `bluetooth` config. 
=> Raspberry pi 4: Fix bluetooth

flake.nix, gigabyte/b550/b550-fix-suspend.nix
This adds gigabyte-b550 to the flake outputs, it is currently missing (https://github.com/NixOS/nixos-hardware/issues/926)
This also fixes a quoting error in one of the systemd unit scripts that was causing it to fail
=> Fix issues with exisiting Gigabyte B550 patches

common/gpu/amd/default.nix, lenovo/legion/15ach6h/nvidia/default.nix, lenovo/legion/16ach6h/nvidia/default.nix, lenovo/legion/16achg6/nvidia/default.nix
This is now provided in nixpkgs (see https://github.com/NixOS/nixpkgs/pull/318175).
=> treewide: drop hardware.amdgpu.amdvlk option

common/cpu/amd/raphael/igpu.nix
Scatter/gather was introduced in 6.2 kernel and caused flickering and various issues when running iGPU on Ryzen 7000-series CPUs. This issue is not observed in kernel 6.6 or newer versions so we can enable it for kernel 6.6 and newer versions.
Closes #918
=> amd/cpu/raphael-igpu: enable scatter/gather for kernel 6.6+

lenovo/legion/16ach6h/hybrid/default.nix
Lenovo Legion 5 pro can use zenpower kernel module. tested with mangohud, I can view cpu tdp.
=> Lenovo 16ACH6H: use zenpower kernel module

common/pc/hdd/default.nix, common/pc/laptop/hdd/default.nix, hp/elitebook/2560p/default.nix, hp/notebook/14-df0023/default.nix
We havent't had anything meaningful configuration in this module for a while. So let's deprecate it.
=> deprecate commons/hdd

acer/aspire/4810t/default.nix, apple/macbook-pro/10-1/default.nix, apple/macmini/4/default.nix, asus/zephyrus/ga402x/amdgpu/default.nix, asus/zephyrus/ga402x/nvidia/default.nix, common/gpu/amd/default.nix, common/gpu/intel/default.nix, common/gpu/nvidia/default.nix, dell/precision/7520/default.nix, dell/xps/15-9510/nvidia/default.nix, focus/m2/gen1/default.nix, gpd/pocket-3/default.nix, lenovo/thinkpad/p1/3th-gen/nvidia.nix, lenovo/thinkpad/p50/default.nix, lenovo/thinkpad/p51/default.nix, lenovo/thinkpad/p52/default.nix, lenovo/yoga/6/13ALC6/default.nix, lenovo/yoga/7/14ARH7/amdgpu/default.nix, lenovo/yoga/7/14ARH7/nvidia/default.nix, system76/gaze18/default.nix
Appears to be a fix for #996 (currently building)
[^1]
[^1]: Please consider [giving up MS GitHub](https://sfconservancy.org/GiveUpGitHub/) or offering a non-proprietary, non-US-corporate-controlled mirror for this free software project. I wish to delete this Microsoft account in the future, but I need more projects like this to support alternative methods to send patches & contribute.
=> remove driSupport, opengl → graphics

apple/t2/pkgs/linux-t2.nix
Update kernel to 6.9.4
Updates patches
It's still kind of flaky, but much more stable than 6.9.3 for me 
=> apple/t2: update to kernel 6.9.4

common/gpu/24.05-compat.nix
fixes https://github.com/NixOS/nixos-hardware/issues/1000
=> common/gpu/24.05-compat: don't create conflicts with user configuration

microsoft/surface/surface-pro-intel/default.nix, microsoft/surface/surface-pro-intel/thermal-conf.xml
added thermald configuration that has been optimized for the surface pro intel series. fixes thermal throttling issues, especially when holding 100% cpu for long periods.
=> surface pro intel: thermald configuration

apple/macbook-pro/14-1/README.md, apple/macbook-pro/14-1/default.nix
update macbookpro14,1 profile to 24.05 release (2024)
- comment out broken workarounds, add replacements
- fix libinput for (hypersensitive/broken) touchpad 
- pin down propper cpu, gpu, acpi, ... support
=> update macbookpro14,1 profile to 24.05 release (2024)

asus/zephyrus/ga402x/amdgpu/default.nix, asus/zephyrus/ga402x/nvidia/default.nix, common/gpu/amd/default.nix, common/gpu/intel/default.nix, lenovo/yoga/6/13ALC6/default.nix, lenovo/yoga/7/14ARH7/amdgpu/default.nix, lenovo/yoga/7/14ARH7/nvidia/default.nix
Initial motivation: https://github.com/NixOS/nixpkgs/issues/283083
=> Remove libvdpau-va-gl and cleanup vdpau in our modules

common/gpu/nvidia/default.nix
- `common/gpu/nvidia/default.nix` conditionally use `pkgs.libva-vdpau-driver` if it exists instead of `pkgs.vaapiVdpau` to handle upstream rename in https://github.com/NixOS/nixpkgs/pull/317542 (this fixes [Issue 1015](https://github.com/NixOS/nixos-hardware/issues/1015) )
=> common/gpu/nvidia: vaapiVdpau -> libva-vdpau-driver

lenovo/yoga/6/13ALC6/default.nix
=> enable bluetooth support for Yoga 6 13ALC6.

asus/zephyrus/ga402x/nvidia/default.nix, common/gpu/amd/default.nix, lenovo/legion/15ach6h/hybrid/default.nix, lenovo/legion/16ach6h/hybrid/default.nix, lenovo/yoga/7/14ARH7/nvidia/default.nix
Option is now in nixpkgs under `hardware.amdgpu.initrd.enable` as of NixOS/nixpkgs@6a0b6a6b74a71be7c37b9d8bc4472cf087aff709
Tests completed at eval time only.
=> gpu/amd: Remove `loadInInitrd` option

README.md, flake.nix, raspberry-pi/3/default.nix, tests/run.py
Upstream my config for Raspberry PI 3
It's just some config that make it works for me
It's heavily inspired by the file that create sd-image for Aarch64
I don't understand everything of it
=> Raspberry Pi 3: init

pine64/pinebook-pro/README.md
Per discussion in #882, this PR removes an obsolete issue section in the docs
(this is a change to the README only, no code changes are done here)
=> pine64/pinebook-pro: remove obsolete issue docs

apple/t2/pkgs/linux-t2.nix
This PR bumps the version of the apple/t2 kernel to 6.9.8 and the patches repo to the latest 6.9 branch ref. The kernel definition was refactored out to a let binding to improve readability.
`HID_APPLE_MAGIC_BACKLIGHT` is removed as related changes are upstreamed to a different module.
Tested working on my own hardware (`MacBookPro16,2`).
=> apple/t2: update kernel and patches

README.md, flake.nix, lenovo/thinkpad/t14s/amd/gen4/default.nix
My Lenovo Thinkpad T14s Gen 4 does not propery power off after shutdown. The display goes blank but the CPU runs very hot and the fan starts to spin up. In this state, the battery is drained within around an hour.
Adding the `apm` parameter fixes this behaviour.
Maybe someone else can chime in if they had similar problems.
=> Fix Lenovo Thinkpad T14s not powering off

common/gpu/nvidia/default.nix
libva-vdpau-driver has not seen a new release in over a decade and is a common cause for bugs in some applications. NixOS has also been using the now preferred nvidia-vaapi-driver since https://github.com/NixOS/nixpkgs/pull/162660, so there isn't much reason to keep this
This is commonly required for many applications. As of https://github.com/NixOS/nixpkgs/pull/324921 this will also enable `nvidia-drm.fbdev=1`, possibly fixing issues such as https://github.com/NixOS/nixpkgs/issues/302059. This will hopefully be done upstream in NixOS as well with https://github.com/NixOS/nixpkgs/pull/326369
CC @Mic92 based on [this](https://github.com/NixOS/nixpkgs/issues/302059#issuecomment-2222143794) comment
=> common-gpu-nvidia: drop libva-vdpau-driver, enable modesetting by default

lenovo/thinkpad/x260/default.nix
Remove BTRFS related setting for ThinkPad x260
The note about BTRFS has been removed from the linked Arch wiki page in January 2021 with a comment:
> Removing note about problems with Btrfs and ALPM, since issues have been fixed in the kernel (4.15 -> https://www.spinics.net/lists/linux-btrfs/msg101833.html))
See: https://wiki.archlinux.org/index.php?title=TLP&oldid=650059
=> Remove BTRFS related setting for ThinkPad x260

flake.nix
This lets the `flake.nix` export the modules as paths instead of importing them first. This should work just as well for anyone doing `imports = [ inputs.nixos-hardware.nixosModules.foo ]`, but the key difference is that the module system knows the names of the modules imported that way.
This is important for several reasons. At least it let's the module system:
* report error locations properly (instead of `<importing module>:anon-X`)
* deduplicate multiple imports of the same module
* make `disabledModules` work.
I ran into each of those problems at some point or another. There are workarounds like specifying the file path manually instead of using the indirection of the table exported via the `flake.nix`, ... but that then also bypasses the abstraction that is supposed to be provided …
=> flake.nix: export paths instead of imported files

common/gpu/24.05-compat.nix
I had an build error (see #1045), due to a missing alias of `hardware.graphics.package` => `hardware.opengl.package`, as well as `hardware.graphics.package32` => `hardware.opengl.package32`.
I realised this was fixable on the end of `nixos-hardware`, and thus this PR was born.
I've tested it in a Flake input on my fork, and in my configuration. The build error is no longer an issue with Nixpkgs input targeted at 24.05.
=> fix: Add more aliases to 24.05-compat

README.md, asus/rog-strix/x570e/default.nix, flake.nix
This driver configuration fixes bluetooth for my host (asus-rog-strix-x570e).
=> asus-rog-strix-x570e: init

flake.nix, lenovo/thinkpad/t14/amd/gen5/default.nix
Add a hardware target for Lenovo Thinkpad T14 Gen5, which uses the same settings as Gen4...
=> Create lenovo-thinkpad-t14-gen5 entry

framework/16-inch/common/default.nix
This addition tells libinput that the built-in keyboard is indeed internal, allowing the "Disable-While-Typing" setting to take effect.
The method is explained at https://linuxtouchpad.org/libinput/2022/05/07/disable-while-typing.html.
=> framework/16-inch: Mark keyboard as internal for libinput

microsoft/surface/common/default.nix, microsoft/surface/common/kernel/linux-package.nix
Fixes a kernel version check for Surface devices. Currently, `isVersionOf` is always `true` instead of testing `kernelVersion`.
=> surface: fix isVersionOf check

asus/zephyrus/ga402x/ATTR-SET-DEPRECATION.md, asus/zephyrus/ga402x/default.nix, flake.nix
This PR:
- Replaces `asus-zephyrus-ga402x.amdgpu` with a `asus-zephyrus-ga402x-amdgpu` entry.
- Replaces `asus-zephyrus-ga402x.nvidia` with a `asus-zephyrus-ga402x-nvidia` entry.
- Makes `asus-zephyrus-ga402x` throw a deprecation warning.
FIXES: #1052 
Background:
The `asus-zephyrus-ga402x` provides an attr-set with `amdgpu` and `nvidia` entries, to allow users to choose whether to enable only the AMD-GPU driver, or also enable the NVidia driver with (by default) Prime enabled.
However, this attr-set style seems to be broken by PR #1046, which exports modules as paths, instead.
That change seems to cause an error of "value is a path while a set was expected".
=> Create asus-zephyrus-ga402x-amdgpu and asus-zephyrus-ga402x-nvidia entries

README.md
Fix the text for the link for the Omen 14-fb0798ng. Nothing to test as is only a README change.
Link text repaired for Omen 14-fb0798ng
=> fix link text for Omen 14-fb0798ng

microsoft/surface/common/kernel/linux-6.9.x/default.nix
Update linux for surface to 6.9.12
Cc: @tracteurblinde
=> surface: linux 6.9.9 -> 6.9.12

common/gpu/intel/default.nix, framework/kmod.nix, gpd/win-max-2/2023/bmi260/default.nix, gpd/win-max-2/default.nix, purism/librem/5r4/default.nix, raspberry-pi/4/digi-amp-plus.nix
`lib.mdDoc` was marked deprecated in NixOS 24.05 and has been a no-op for [quite a while](https://github.com/NixOS/nixpkgs/pull/237557). Let's remove it!
Benefits: No more trace warnings during eval.
=> treewide: remove uses of lib.mdDoc

asus/zephyrus/ga402x/shared.nix
The bug that seemed to make the internal keyboard on the ASUS Zephyrus GA402X take 1-2 keypresses after suspend seems to be fixed in (at least) kernel 6.9.x.
This adds an option to select to turn the auto-suspend on or off for this device.
- On kernels before 6.9.x, default to disabling auto-suspend
- On more-recent kernels, default to enabling auto-suspend
=> On ASUS Zephyrus GA402X, make enabling auto-suspend on the keyboard optional

tuxedo/pulse/14/gen3/README.md, tuxedo/pulse/14/gen3/default.nix
Update to a closer kernel version which fixes the shutdown problem with Tuxedo Gen3.
=> fix: update fix to a closer version which fixes shutdown problems on tuxedo gen3

common/gpu/intel/default.nix
It seems that nobody except me used this option so nobody ever noticed that it does not work at all.
I don't know why but i915 driver seems to throw `failed to probe lspcon` on my dell precision 5540 for no reason when it tries to load early, especially considering that early loading works perfectly on my other nvidia optimus laptop: ideapad that has a crappy bios. My temporary solution to this is just disabling early loading but if anyone has any suggestions on how to fix it, tell me.
fixed the option.
=> 🛠 Fix intelgpu.loadInInitrd (it now does something)

README.md, flake.nix, lenovo/thinkpad/p14s/intel/default.nix, lenovo/thinkpad/p14s/intel/gen3/default.nix
Add basic support for Lenovo ThinkPad P14s Gen 3 (Intel) with NVIDIA graphics.
[Lenovo PSREF](https://psref.lenovo.com/WDProduct/ThinkPad/ThinkPad_P14s_Gen_3_Intel).
=> Add Lenovo ThinkPad P14s Gen 3 (Intel)

dell/xps/13-9380/README.wiki, dell/xps/13-9380/default.nix
Just enabling fwupd service like on any other xps13.
Also changed the wiki mentioning how to update firmware.
=> xps13-9380: enable fwupd

lenovo/legion/16ach6h/edid/default.nix
Slightly abstracts the EDID implementation by using the newly introduced `hardware.display` module
=> 16ach6h: Use the hardware.display module

README.md
=> doc: add missing Apple iMac entry

common/gpu/intel/default.nix
#1014 removed the "va_gl" driver library, but did not remove the `VDPAU_DRIVER` environment variable that overrides the VDPAU driver library selection to `libvdpau-va-gl`.
This is a problem, because if I try to run `vdpauinfo` on a hybrid graphics laptop with Intel + Nvidia, that variable points to a now nonexistent libvdpau library, so the command fails. It is reasonable to expect the user to manually provide the environment variable themselves if needed alongside the no longer recommended `libvdpau-va-gl`
----------
Note: With my hybrid graphics laptop on Xorg, `vdpauinfo` tries to select "va_gl" even without the environment variable (and also just doesn't work at all when forced to "nvidia"). On Wayland it correctly selects the Nvidia VDPAU library without any envionment variable …
=> gpu/intel: cleanup vdpau variable

lenovo/yoga/6/13ALC6/default.nix
Add extra modprobe options to fix unstable wifi on Yoga laptops.
=> lenovo: fix unstable wifi on Yoga laptops

common/gpu/nvidia/ada-lovelace/default.nix, common/gpu/nvidia/ampere/default.nix, common/gpu/nvidia/maxwell/default.nix, common/gpu/nvidia/pascal/default.nix, common/gpu/nvidia/turing/default.nix, dell/xps/15-7590/nvidia/default.nix, dell/xps/15-9570/nvidia/default.nix, flake.nix
And add logic to enable the opensource drivers if the NVIDIA driver package and micro architecture supports it
=> Add configurations for nvidia microarchitectures

dell/g3/3779/default.nix, dell/xps/15-9500/nvidia/default.nix, dell/xps/15-9510/nvidia/default.nix, dell/xps/15-9520/nvidia/default.nix, dell/xps/15-9550/nvidia/default.nix, dell/xps/15-9560/default.nix, dell/xps/15-9560/nvidia/default.nix, dell/xps/17-9700/nvidia/default.nix, tests/flake.lock
Allows these configurations to build on latest nixpkgs.
Also update the flake.lock for tests.
=> Dell: Add Nvidia Architectures

README.md, flake.nix, gpd/win-mini/2024/README.md, gpd/win-mini/2024/default.nix, gpd/win-mini/default.nix
Adding support for GPD Win Mini 2024.
=> gpd/win-mini/2024: add initial configuration

lenovo/legion/15arh05h/default.nix
https://github.com/NixOS/nixos-hardware/issues/1100
Tested with:
```diff
-    nixos-hardware.url = "github:NixOS/nixos-hardware";
+    nixos-hardware.url = "github:DontEatOreo/nixos-hardware/lenovo-legion-15arh05h-nvidia-arch";
```
Was able to rebuild, restart and log in *(on GNOME 46.4 - Wayland)*
=> lenovo-legion-15arh05h: add NVIDIA architecture

README.md, asus/zephyrus/gu605my/default.nix, flake.nix
Added the configuration for my GU605MY. It's currently identical to the Zephyrus M16 GU603H and seems to be running well so far for the most part. 
- added module to asus/zephyrus/gu605my
- added entry to flake outputs
- added entry in README table
=> Adding Asus Zephyrus G16 GU605MY

README.md, flake.nix, msi/gl65/10SDR-492/default.nix
Add initial configuration for MSI GL65 laptop model. I believe this meets the criteria for Nvidia specification mentioned in #1100.
=> msigl65: add initial configuration

apple/imac/14-2/default.nix, apple/macbook-pro/10-1/default.nix, common/gpu/nvidia/kepler/default.nix, focus/m2/gen1/default.nix, lenovo/ideapad/15ach6/default.nix, lenovo/ideapad/15arh05/default.nix, lenovo/ideapad/16ach6/default.nix, lenovo/legion/15ach6/default.nix, lenovo/legion/15ach6h/hybrid/default.nix, lenovo/legion/15ich/default.nix, lenovo/legion/16irx8h/default.nix, lenovo/legion/16ithg6/default.nix, lenovo/legion/t526amr5/default.nix, lenovo/thinkpad/e470/default.nix, lenovo/thinkpad/p14s/intel/gen3/default.nix, lenovo/thinkpad/p50/default.nix, lenovo/thinkpad/p51/default.nix, lenovo/thinkpad/p52/default.nix, lenovo/yoga/7/14ARH7/nvidia/default.nix, msi/gl62/default.nix, omen/14-fb0798ng/default.nix, omen/15-en0002np/default.nix, omen/15-en0010ca/default.nix, omen/15-en1007sa/default.nix, omen/16-n0280nd/default.nix, system76/gaze18/default.nix
Allows evaluation with latest nixpkgs
Fixes #1100 
=> Treewide: Add Nvidia Architecture

README.md, apple/macbook-pro/8-1/README.md, apple/macbook-pro/8-1/default.nix, flake.nix
I added a new profile for Apple MacBook Pro 8,1
importing it via Flake input
=> Treewide: Add new profile for Apple MacBook Pro 8,1

README.md, flake.nix, starlabs/README.md, starlabs/starlite/i5/README.md, starlabs/starlite/i5/default.nix
Add profile for Star Labs' StarLite 5 tablet. Screen rotation is basically the only thing that didn't work out of the box--this fixes that.
@samueldr's suggestion in https://github.com/NixOS/nixos-hardware/issues/871 to identify profiles based on product_sku seemed like a good one, so that's what I'm doing here!
Verified proper behavior on my own hardware running Plasma v6 with this branch as flake input.
=> starlabs: init, add starlite 5 tablet

flake.nix, malibal/aon/s1/README.wiki, malibal/aon/s1/default.nix
Add initial support for the [MALIBAL Aon S1](https://www.malibal.com/shop/laptops/aon-s1/).
=> malibal/aon/s1: Add initial intel-only support

asus/zephyrus/gu605my/default.nix
- updated nvidia architecture to ada-lovelace.
- added default value nvidia dynamicBoost as it is supported by the gpu
- added default to enable asusd
- added fix in udev to correctly map the mic mute key
=> Update.asus zephyrus g16 gu605my

framework/README.md
The documentation in the Framework section referenced fw-ectool only being in nixpkgs-unstable. This is no longer the case. 
(It's just a documentation change, so should be fine)
=> framework: fix outdated documentation on fw-ectool

lenovo/yoga/6/13ALC6/default.nix
Add mkDefault for bluetooth enabling on the Lenovo Yoga 6 13ALC6 for consistency with the codebase.
=> lenovo-yoga-6-13ALC6: add mkDefault for bluetooth

apple/t2/pkgs/linux-t2.nix
Update kernel patches and update kernel to 6.11 for Apple T2 devices
=> apple/t2: bump kernel to 6.11

asus/rog-strix/x570e/default.nix
asus-rog-strix-x570: add nct6775 kernel module for temperature and fan sensor
=> asus-rog-strix-x570: add nct6775 kernel module for temperature and fan sensor

lenovo/thinkpad/x1/6th-gen/QHD/default.nix
=> Remove fonts.fontconfig.dpi in Lenovo Thinkpad X1 6th Gen QHD

common/hidpi.nix
=> only incrase font size for older kernel

asus/rog-strix/x570e/default.nix
asus-rog-strix-x570: add troubleshooting notice for bluetooth device missing
Whenever someone is suffering with Bluetooth driver issue, the most likely place they'll look after a correct driver is here. And the proposed driver here won't work because odds are it's also a hardware/electrical issue. So I think, this is a good place to document this.
I have tested this on my computer, more than once. A bit weird, I know... I always forget why this goes bad and I end up thinking I have a software problem at NixOS again. Like, someone broke something at nixpkgs, but no.
=> asus-rog-strix-x570: add troubleshooting notice for bluetooth device missing

README.md, flake.nix, system76/galp5-1650/default.nix
Adds the system76 galp5 (1650 version in this case)
=> Add system76 galp5-1650

dell/precision/5560/README.md, dell/precision/5560/default.nix, flake.nix
Added config for `Dell Precision 5560`
=> dell-precision-5560: init

framework/16-inch/common/default.nix
Use the upstream libinput keyboard detection quirks configuration to ensure Framework 16 laptop keyboards are detected and treated as internal keyboards. Notably, this means that non-ANSI Framework keyboards are correctly detected and treated as being internal keyboards rather than external ones.
Also add a comment noting that this configuration is part of more recent upstream libinput releases, and that it can be removed once we no longer need to support older versions of libinput. That probably means once NixOS 24.05 is out of support.
=> Framework 16: use upstream libinput keyboard detection

framework/16-inch/common/default.nix
Add a udev rule to allow the keyboard modules to be reconfigured on a Framework 16 laptop.
=> Framework 16: udev rules for keyboard config

README.md, flake.nix, lenovo/thinkpad/x1-extreme/gen3/default.nix
Add module for Lenovo Thinkpad X1 Extreme (Gen 3).
Gen 2 and Gen 4 were already there.
One thing that was new compared to either is a kernel parameter for the `psmouse` module which fixes clicking with the clickpad. The solution is described here: https://discourse.nixos.org/t/touchpad-click-not-working/12276
=> thinkpad/x1-extreme/gen3: add module

asus/zenbook/ux371/default.nix
=> intel gpu: only enable xe driver starting with lunar lake

common/gpu/intel/default.nix, lenovo/thinkpad/t480s/default.nix
Adds support for certain hardware accelerators on the T480s's iGPU.
=> Enable t480s gpu acceleration

README.md, flake.nix, tuxedo/aura/15/gen1/default.nix
Adds config for tuxedo aura 15 gen 1
https://www.tuxedocomputers.com/de/Linux-Hardware/Linux-Notebooks/15-16-Zoll/TUXEDO-Aura-15-Gen1.tuxedo
=> add tuxedo aura 15 gen1

README.md, dell/inspiron/7460/README.md, dell/inspiron/7460/default.nix, flake.nix
=> add dell inspiron 7460

microsoft/surface/OLD-BEHAVIOUR-DEPRECATION.md, microsoft/surface/README.md, microsoft/surface/TODO.org, microsoft/surface/common/repos.nix, microsoft/surface/surface-go/firmware/ath10k/default.nix
ath10k firmware did not fully support QCA6174 devices.
The fixed firmware was upstreamed in Nov 2021.
This adds a deprecation warning in preparation to remove this fix, in an effort to not break anyone who hasn't updated.
I expect to make a follow-up PR to remove the code to provide the non-upstreamed firmware by the end of 2024.
=> microsoft/surface: Deprecate option to install non-upstreamed ath10k QCA6174 firmware 

README.md, dell/precision/5490/README.md, dell/precision/5490/default.nix, flake.nix
Add minimal configuration for dell precision 5490.
=> Add dell precision 5490

gpd/win-max-2/2023/bmi260/default.nix, gpd/win-max-2/2023/bmi260/package.nix
Upstream: https://github.com/hhd-dev/bmi260/releases/tag/v1.0.0
Reformat with `nixfmt-rfc-style`
=> gpd-win-max-2-2023/bmi260: 0.0.2 -> 1.0.0

README.md, asus/zenbook/ux535/README.md, asus/zenbook/ux535/default.nix, flake.nix
Added Asus Zenbook Pro ux535
I've been using NixOS on this laptop for a while now, so I figured my configuration was hopefully stable enough to be upstreamed here for others to use. All values were taken from my config, along with some other values that I've found to cause bugs if set turned off.
I found the contributing docs to be outdated when it came to running the testing python script, it seems to have had major changes made three weeks ago that have changed it's usage. The command: `./tests/run.py --jobs 4 --verbose --nixos-hardware ./.` worked for me to test all modules, I couldn't figure out how we're now meant to test only a single module (--jobs 4 is only because I ran out of Memory without a limit, and it ran quickly enough with 4 without using too much, you could probably …
=> Add Asus Zenbook ux535

common/gpu/intel/alder-lake/default.nix, common/gpu/intel/bay-trail/default.nix, common/gpu/intel/braswell/default.nix, common/gpu/intel/broadwell/default.nix, common/gpu/intel/comet-lake/default.nix, common/gpu/intel/default.nix, common/gpu/intel/elkhart-lake/default.nix, common/gpu/intel/haswell/default.nix, common/gpu/intel/jasper-lake/default.nix, common/gpu/intel/kaby-lake/default.nix, common/gpu/intel/sandy-bridge/default.nix, common/gpu/intel/tiger-lake/default.nix, dell/xps/15-9550/default.nix
https://github.com/NixOS/nixos-hardware/pull/1186, but only the intelgpu changes
Fixes https://github.com/NixOS/nixos-hardware/issues/1170
Closes #573 (Supercedes)
=> Add some extra configurable options to intelgpu

starfive/visionfive/v2/sd-image.nix
repro
```nix
{
inputs.nixpkgs.url = "github:nixos/nixpkgs/nixos-unstable";
inputs.nixos-hardware.url = "github:nixos/nixos-hardware/38279034170b1e2929b2be33bdaedbf14a57bfeb";
#inputs.nixos-hardware.url = "github:pbsds/nixos-hardware/vf2-default";
#inputs.nixos-hardware.url = "github:pbsds/nixos-hardware/vf2-default-alt"; (this pr)
outputs = { self, nixpkgs, nixos-hardware, ... }: {
packages."x86_64-linux".default = (import "${nixpkgs}/nixos" {
system = "x86_64-linux";
configuration =
{ config, ... }: {
imports = [
nixos-hardware.nixosModules.starfive-visionfive-2
"${nixos-hardware}/starfive/visionfive/v2/sd-image-installer.nix"
];
sdImage.compressImage = false;
nixpkgs.crossSystem.system = "riscv64-linux";
system.stateVersion = "24.05";
};
}).config.system.build.sdImage;
};
}
```
causes …
=> Make `nixosModules.starfive-visionfive-2` merge with sd-image

common/cpu/intel/alder-lake/cpu-only.nix, common/cpu/intel/alder-lake/default.nix, common/gpu/intel/kaby-lake/default.nix, flake.nix, lenovo/thinkpad/x1/6th-gen/default.nix
Creates a new config for intel alder lake (using the existing gpu module). Also updates the thinkpad x1 6th gen config to import the cpu architecture-specific module.
=> common-cpu-intel-alder-lake: init

common/cpu/intel/braswell/default.nix, common/cpu/intel/broadwell/default.nix, common/cpu/intel/comet-lake/default.nix, common/cpu/intel/elkhart-lake/default.nix, common/cpu/intel/haswell/default.nix, common/cpu/intel/jasper-lake/default.nix, common/cpu/intel/kaby-lake/default.nix, common/cpu/intel/lunar-lake/cpu-only.nix, common/cpu/intel/lunar-lake/default.nix, common/cpu/intel/sandy-bridge/default.nix, common/cpu/intel/tiger-lake/default.nix, common/gpu/intel/lunar-lake/default.nix, tests/flake.lock
=> common/gpu/intel/lunar-lake: enable xe driver

apple/macbook-pro/12-1/default.nix
Module brcmfmac cannot be unloaded with rmmod when brcmfmac_wcc is loaded. This leads brcmfmac to crash on wake up.
=> Unload brcmfmac_wcc (if loaded) before brcmfmac

common/gpu/intel/default.nix
Commit message is self-explanatory.
=> common/gpu/intel: Disable intel-ocl due to web.archive.org outage

asus/zephyrus/ga402x/shared.nix
this allows generating a options.json without setting any module option
=> Set missing lib.literalExpression

lenovo/thinkpad/z/gen2/z13/default.nix
Add modem fcc unlock script for ThinkPad Z13 Gen2
```bash
$ lsusb | grep 2c7c:030a
Bus 001 Device 003: ID 2c7c:030a Quectel Wireless Solutions Co., Ltd. Quectel EM05-G
```
=> lenovo/z/gen2/z13: Add modem fcc unlock

common/gpu/intel/default.nix
Now that the Internet Archive is back online, this reverts commit e8a2f6d5513fe7b7d15701b2d05404ffdc3b6dda.
=> Revert "common/gpu/intel: Disable intel-ocl due to web.archive.org outage"

common/gpu/nvidia/ada-lovelace/default.nix, common/gpu/nvidia/ampere/default.nix, common/gpu/nvidia/turing/default.nix
Fixed "nividia" typo.
I'm unsure if this change impact other things but looks like  "nividiaPackage" only referenced in these files.
=> Fix "nividia" typo

README.md, apple/macbook-air/7/README.md, apple/macbook-air/7/default.nix, flake.nix
added macbook air 7 and added to flake.nix and readme, also added readme in folder describing issues with wifi driver
- [ x ] Tested the changes in your own NixOS Configuration
=> macbook air 7

framework/13-inch/common/default.nix, framework/16-inch/common/default.nix, framework/bluetooth.nix
Framework have published a workaround for a bug that affects the MediaTek Bluetooth and Wi-Fi cards used in their laptops on kernel version 6.11.  Their workaround assumes a writable /etc/systemd directory, so reimplement the workaround for NixOS.
For the Framework version of the workaround, see:
https://github.com/FrameworkComputer/linux-docs/tree/eab0148ae8223eddaed8f0cd4cd73f9399ecdb65/hibernation/kernel-6-11-workarounds
=> Framework: add workaround for Bluetooth device issues

README.md, flake.nix, minisforum/v3/audio.nix, minisforum/v3/default.nix, minisforum/v3/dsdt.patch, minisforum/v3/power.nix, minisforum/v3/sensors.nix, minisforum/v3/src.nix
> Add fixes and power settings for the Minisforum V3 3-in-1 Tablet
+ Accelerometer fixes
+ ACPI DSDT patch (Is there a better way of doing this?)
+ udev rules to fix inverted values
+ Power settings
+ Enable ASPM (Should the script even be added or behind an option?)
+ Set policy to `powersupersave`
+ Audio fixes
+ Alsa rules
+ modprobe config for microphone
+ [#5 - Optimizing power draw](https://github.com/mudkipme/awesome-minisforum-v3/issues/5#issue-2391536450)
+ [#2 - Accelerometer](https://github.com/mudkipme/awesome-minisforum-v3/issues/2#issuecomment-2279282784)
+ [#9 - volume control fixes](https://github.com/mudkipme/awesome-minisforum-v3/issues/9#issue-2407782714)
+ [#10 - volume control workaround](https://github.com/mudkipme/awesome-minisforum-v3/issues/10#issuecomment-23174740 …
=> minisforum/v3: init

README.md, lenovo/ideapad/16ahp9/README.md, lenovo/ideapad/16ahp9/default.nix, lenovo/ideapad/16iah8/README.md, lenovo/ideapad/16iah8/default.nix
As descripted in #1203, my laptop (16IAH8) had the wrong CPU and GPU configuration. I added another Ideapad (16AHP9) which has both and AMD and GPU, unlike mine.
=> Lenovo Ideapads 16IAH8 corrected hardware, added 16AHP9

tests/flake.nix
The nixpkgs used to test profiles was (likely mistakenly) hardcoded to `nixos-unstable-small`, and as a result both nixpkgs{Unstable,Stable} used the same nixpkgs version. This causes unexpected assertion failures with `(lib.versionAtLeast (lib.versions.majorMinor lib.version) "24.11")`
This PR unhardcodes the value and resolves the potential issue.
Note that this fails 3 tests at the time of writing, namely `x86_64-linux.nixos-stable-lenovo-legion-16ach6h{,-hybrid,-nvidia}`, all because of a non-existent `hardware.display` option in stable nixpkgs.
=> tests: fix unused importPath in unfreeNixpkgs function

lenovo/legion/16ach6h/edid/default.nix
=> fix eval with 24.05

README.md, apple/macbook-pro/11-1/README.md, apple/macbook-pro/11-1/default.nix, flake.nix
Just a simple module I wrote for my late 2013 MacBook Pro and would like to share with the community.
=> apple: init MacBookPro11,1

tests/flake.lock, tuxedo/aura/15/gen1/default.nix
updates the test flake's lockfile and migrate a renamed option in tuxedo to fix ci.
for tuxedo, this doesn't seem to be the intended behavior... could this be a bug in the module system? either way, this should make ci green.
=> tests: update flake lock; tuxedo/aura/15-gen1: migrate renamed option

apple/t2/default.nix
same as in https://github.com/NixOS/nixos-hardware/pull/1225
=> apple/t2: deprecate enableTinyDfr option

framework/13-inch/7040-amd/default.nix
The comparison previously used the default kernel's version instead of the selected kernel's version. This makes the comparison use the actually selected kernel's version.
=> framework: Fix kernel version comparison for preventWakeOnAC

apple/t2/pkgs/linux-t2.nix
Bumps the t2 kernel from 6.11 to 6.11.7.
=> apple/t2: bump kernel from 6.11 to 6.11.7

framework/13-inch/common/amd.nix, framework/16-inch/common/amd.nix
Framework users (including me) have issues with PSR. We can trade some battery life for stability here. So far there is no workaround except disabling PSR.
See:
- https://community.frame.work/t/fedora-kde-becomes-suddenly-slow/58459
- https://gitlab.freedesktop.org/drm/amd/-/issues/3647
=> framework: workaround display issues on AMD GPUs

framework/13-inch/11th-gen-intel/default.nix, framework/13-inch/12th-gen-intel/default.nix, framework/13-inch/7040-amd/default.nix, framework/13-inch/common/audio.nix, framework/13-inch/common/default.nix
This PR adds the `hardware.framework.laptop13.audioEnhancement` option, which adds filters that enhance the audio coming from the laptop speakers. This config yields vastly enhanced audio, including much better bass.
These techniques are heavily inspired by the Asahi project's [asahi-audio](https://github.com/AsahiLinux/asahi-audio) repo and contains an equalizer transformed from the "Lappy McTopface" preset from [ee-framework-presets](https://github.com/ceiphr/ee-framework-presets) (both MIT-licensed).
I am unsure about putting the option under `hardware.framework.laptop13`, but this applies to Framework Laptop 13, but not the 16 and there wasn't an existing option for this subset.
I had this in my personal config for quite a bit of time, but decided to upstream it, in case it helps …
=> framework: Add `hardware.framework.laptop13.audioEnhancement` option

flake.nix
Lenovo Ideapad 16AHP9 was not available in the flake. This is just a one-liner which adds an alias to the module.
=> Added Lenovo Ideapad 16AHP9 to Flake.nix

README.md
I realized after #1260 that the URL in the readme is misspelt. This PR just fixes this.
=> Fix typo in Lenovo IdeaPad 16AHP9 URL

flake.nix
Added missing reference mainly because I needed it personally. 
[Issue referencing the problem](https://github.com/NixOS/nixos-hardware/issues/1259) 
added a reference to an alreaady existing module, assuming that it was left out due to a typo. 
**Really not that much**
importing it via  Flake input
- the only reason I even bothered to fix it was personal need and contributing it here is really just a way of pointing out the omission (merge it or edit the file in-browser, I won't feel slighted either way)
> Thanks for all your hard work here and elsewhere in Nixland! 
> Thomas Leon Highbaugh
=> Added missing flake reference for the Lenovo Legion 16IRX9H

apple/t2/pkgs/linux-t2.nix
Bump the kernel of t2 devices to 6.12.2
note: draft because ci is building the kernel
=> apple/t2: bump kernel from 6.11.7 to 6.12.2

apple/t2/pkgs/linux-t2.nix
Bump the kernel version to fix regressions
=> apple/t2: kernel 6.12.2 -> 6.12.4

microsoft/surface/common/default.nix, microsoft/surface/common/kernel/linux-surface/default.nix, microsoft/surface/common/kernel/linux-surface/patches.nix, microsoft/surface/common/repos.nix
When using zfs this requires openZFS 2.2.7 or openZFS 2.3.0-rc4
=> microsoft/surface: Update to kernel 6.12.4

raspberry-pi/4/default.nix, raspberry-pi/4/tv-hat.nix
This PR adds support to the [Raspberry Pi TV HAT](https://www.raspberrypi.com/products/raspberry-pi-tv-hat/). I needed to add two overlays one for the tv-hat and another one to enable SPI. I wasn't sure if merging them on the same file or not, at the end I put them together.
=> raspberry-pi-4: add tv-hat overlay

dell/precision/5560/README.md, dell/precision/5560/default.nix
- removed redundant `i915.modeset=1`
- enabled `services.fwupd`
=> dell-precision-5560: remove redundant config and enable fwupd

README.md, lenovo/thinkpad/t14/amd/gen5/default.nix
This PR should remove constant battery drain specific to this device (and others, but I only have this one to test) as suggested in e.g.
- https://bbs.archlinux.org/viewtopic.php?id=298895
- https://bbs.archlinux.org/viewtopic.php?id=234913
=> enable acpi.ec_no_wakeup in Thinkpad T14 AMD Gen 5

dell/latitude/3480/default.nix, dell/latitude/7430/default.nix, gpd/pocket-3/default.nix
Closes #1300
Removed `services.xserver.videoDrivers = [ "intel" ];` from: 
- `gpd/pocket-3` (tested on my device)
- `dell/latitude/3480` (not tested)
- `dell/latitude/7430` (not tested)
Since "modesetting" is the default first item nothing additional needs to be added.
From https://github.com/NixOS/nixpkgs/blob/cbd8ec4de4469333c82ff40d057350c30e9f7d36/pkgs/servers/x11/xorg/overrides.nix#L1024 :
```nix
xf86videointel = throw ''
xf86videointel has been removed as the package is unmaintained and the driver is no longer functional.
Please remove "intel" from `services.xserver.videoDrivers` and switch to the "modesetting" driver.
''; # Added 2024-12-16;
```
Further documented here: https://github.com/NixOS/nixpkgs/pull/365448/ …
=> fix: remove intel from services.xserver.videoDrivers due to deprecation in 24.11

starfive/visionfive/v2/default.nix, starfive/visionfive/v2/firmware.nix, starfive/visionfive/v2/sd-image.nix, starfive/visionfive/v2/spl-tool.nix
Adds an easy way to override the sources for uboot and OpenSBI, this makes it easier for someone to switch to a the vendor's u-boot and OpenSBI.
=> starfive visionfive2: allow uboot and opensbi source overrides

raspberry-pi/4/leds.nix
currently the overlays are not applied.
and somehow it got renamed... compare kernel:
- 6.1: https://github.com/raspberrypi/linux/blob/rpi-6.1.y/arch/arm/boot/dts/overlays/act-led-overlay.dts
- 6.2+: https://github.com/raspberrypi/linux/blob/rpi-6.6.y/arch/arm/boot/dts/overlays/act-led-overlay.dts
=> raspberry-pi.4.leds: enable overlays-dtmerge + fix target names

README.md, flake.nix, lenovo/yoga/7/14IAH7/hybrid/default.nix, lenovo/yoga/7/14IAH7/integrated/default.nix, lenovo/yoga/7/14IAH7/shared.nix
- Added `lenovo-yoga-7-14IAH7-integrated`
- Added `lenovo-yoga-7-14IAH7-hybrid`
=> lenovo/yoga/7/14IAH7: init

README.md, asus/flow/gv302x/amdgpu/default.nix, asus/flow/gv302x/nvidia/default.nix, asus/flow/gv302x/shared.nix, flake.nix
=> Adding support for GV302X* 2023

README.md, flake.nix, slimbook/hero/rpl-rtx/README.md, slimbook/hero/rpl-rtx/default.nix
Create a profile for the Slimbook "HERO" model.
I have tested with `nix run ./test#run`, as well.
<details><summary>Obsolete error:</summary>
Please note that I have commented out the imports from `common/cpu/intel` and `common/gpu/intel/coffee-lake`, as they call `common/gpu/intel` and produces the following error during the build:
```bash
> sudo nixos-rebuild switch --flake .
building the system configuration...
error:
… while calling the 'head' builtin
at /nix/store/wj2qla569hnxwqfc26imv5hqbxc1rc27-source/lib/attrsets.nix:1574:11:
1573|         || pred here (elemAt values 1) (head values) then
1574|           head values
|           ^
1575|         else
… while evaluating the attribute 'value'
at …
```
=> Slimbook/hero: Init

README.md, asus/fa506ic/default.nix, flake.nix
Add Asus tuf a15(2021) fa506ic hardware config
=> asus: init fa506ic

common/gpu/intel/tiger-lake/default.nix
fixes https://github.com/NixOS/nixos-hardware/issues/1278
Don't try to use `Xe` on Tiger Lake, since the module won't load unless you use `force_probe`
=> gpu/intel/tiger-lake: don't try to use Xe by default

README.md, flake.nix, lenovo/ideacentre/k330/README.md, lenovo/ideacentre/k330/default.nix
This will add a default configuration for the Lenovo IdeaCentre K330
Since I don't really know what I am doing here, I'll need some input from more experienced Nix users. The main goal was to help out with an instability that came from wayland being a default even on old systems (for plasma desktops). #1297 
The contributing guidelines recommend to import
- CPU (Intel)
- GPU (NVIDIA)
- PC (in this case) | Laptop
- HDD | SSD
I imported CPU, GPU and PC but am unsure about the storage component since presumably most old systmes that somebody wants to revive will use a cheap SSD, including mine while the original hardware was almost certainly a HDD (in my case a Seagate Barracuda)
Best,
Gab
=> Lenovo ideacentre k330

lenovo/thinkpad/z/gen2/z13/default.nix
Fixes evaluation warning
[^1]
[^1]: Please consider [giving up MS GitHub](https://sfconservancy.org/GiveUpGitHub/) or offering a non-proprietary, non-US-corporate-controlled mirror for this free software project. I wish to delete this Microsoft account in the future, but I need more projects like this to support alternative methods to send patches & contribute.
=> lenovo-z13-gen2: networking.networkmanager.fccUnlockScripts → networking.modemmanager.fccUnlockScripts

README.md, flake.nix, xiaomi/fix-boot-quirk.nix, xiaomi/redmibook/16-pro-2024/README.md, xiaomi/redmibook/16-pro-2024/default.nix
~~Also exposed the boot fix as a module since other models might be affected as well~~
=> xiaomi/redmibook/16-pro-2024: init

README.md, dell/latitude/5490/default.nix, flake.nix
`./dell/latitude/5490` exists, but is not included in `flake.nix`.
=> include Dell Latitude 549 in flake.nix

README.md, flake.nix, gpd/pocket-4/default.nix
Here's a Pocket 4 first pass based on the Pocket 3 setup.
I'm testing this on the [Pocket 4 with AI 9 HX 370](https://gpdstore.net/gpd-mini-laptop/gpd-pocket-4/#cgkit-tab-additional_information) using NixOS 24.11 and mainline kernel 6.12. Apart from the display rotation needed in kernel params and WM settings like the Pocket 3, basic desktop stuff seems to just work.
❌ Fingerprint Reader: [HOLTEK FocalTech Fingerprint Device](https://linux-hardware.org/?id=usb:2808-0752). No driver support yet. Places to watch: [1](https://fprint.freedesktop.org/supported-devices.html), [2](https://github.com/ftfpteams/focaltech-linux-fingerprint-driver)
❓ Optional hardware modules (KVM, serial, LTE). I don't have any of these to try out. YMMV.
=> gpd/pocket-4: init

framework/README.md, framework/kmod.nix
Fixes #1028 
Changes several aspects of [framework-laptop-kmod](https://github.com/DHowett/framework-laptop-kmod) support:
- default value has been changed to true when NixOS >= 24.05 *and* linux kernel >=6.10; false otherwise
- adds required patch for framework AMD enablement when kernel <6.10
- add README section describing usage
Also: this may be an upstream nixpkgs issue, but the lack of a good lore.kernel.org fetcher is kind of surprising. I tried using [this sample code with `fetchpatch`](https://discourse.nixos.org/t/fetching-patches-from-lore-kernel-org/45594) initially, but got weird errors with it. I [implemented](https://git.lain.faith/haskal/dragnpkgs/src/commit/ecdf449848aaa8fe368922fb3cb28d2ce8b09be7/lib/fetchb4) a `fetchb4` fetcher for my own personal usage, which uses `b4` …
=> framework: refactor kmod for improved AMD support

lenovo/legion/16ach6h/README.md, lenovo/legion/16ach6h/hybrid/default.nix
Added and enabled `nvidia-powerd` (via [`dynamicBoost`](https://download.nvidia.com/XFree86/Linux-x86_64/550.142/README/dynamicboost.html)) to take advantage of the laptop's power profiles. Prior to this change, the performance profiles  (color-coded and cycled through via Fn + Q) have no effect on the dGPU `Current Power Limit` (CPL for short). This value can be observed via `sudo nvidia-smi -q -d POWER` or in `nvtop`.
*Example on my RTX 3060-based laptop with a maximum (GPU) power limit of 130 W*:
For simplicity I used "maximum performance power profile" in KDE Plasma settings and ran Uniengine Heaven benchmark in the foreground.
* `dynamicBoost` **disabled** (or `nvidia-powerd` stopped): No matter the load, CPL == `Default Power Limit` (80 W).
* `dynamicBoost` **enabled** …
=> Legion 16ach6h gpu power

nxp/common/bsp/linux-imx8.nix
https://github.com/NixOS/nixpkgs/pull/366004
introduced a breaking change that if a module is declared but it is not being used it will fail.
=> nxp-imx: fix unused modules errors

nxp/common/bsp/linux-imx8.nix, nxp/imx8mp-evk/bsp/imx8mp-linux.nix, nxp/imx8mq-evk/bsp/imx8mq-linux.nix
this fixes the unused modules error that was introduced by https://github.com/NixOS/nixpkgs/pull/366004
for all the imx8 targets
=> imx8: fix the unused module error accross all imx8

framework/kmod.nix
see build failure at https://github.com/NuschtOS/search.nuschtos.de/actions/runs/12948513311/job/36117329099?pr=40
=> Fix doc build by adding missing defaultText

gpd/pocket-4/default.nix
The Pocket 4 (AI 9 HX 370 version tested) fails to init the amdgpu module when using kernel version 6.6, producing a mostly-broken display. This change defaults to at minimum kernel version 6.12 where the display is probed without issue and runs at native resolution as expected.
=> gpd/pocket-4: change minimum default kernel version to 6.12 to fix amdgpu error

README.md, dell/latitude/7420/default.nix, flake.nix
This adds an entry for `dell-latitude-7420`. Before using this change with my 7420, VA-API wasn't working, so I had no hardware accelerated video decoding; now VA-API is working.
I'm not specially setting any kernel parameters like some other entries do, because I don't think it's necessary in this case. Our Tiger Lake module already sets `i915.enable_guc=3`, and other i915 settings can be left at the default (e.g. upstream Linux defaults `i915.enable_fbc` to `-1`, meaning that FBC should be enabled for chips for which that is supported). 
I did not run `nix run ./tests#run .` as requested by `CONTRIBUTING.md`, because when I tried, my load average went to 60 until my OOM killer was activated. Nonetheless, this is a pretty straightforward …
=> dell/latitude/7420: init

apple/t2/default.nix, apple/t2/pkgs/linux-t2.nix
* bumped the kernel to 6.13
* ~~updated a renamed option to silence warnings~~
* removed apple_set_os loader as related functionality had been included in the kernel
=> apple/t2: kernel update and various option updates

CODEOWNERS
=> codeowners: remove tomfitzhenry from pinebook-pro

framework/13-inch/12th-gen-intel/default.nix
See https://community.frame.work/t/hdmi-audio-output/9523/23 for more details
Tested on framework 13th gen
Would need somebody to test this on 12th gen aswell
=> framework/13-inch/12th-gen-intel: add hdmi audio fix

framework/13-inch/12th-gen-intel/default.nix
This reverts commit 8b5ef47338c924c827c00dec69cf7108744fe199.
fixes https://github.com/NixOS/nixos-hardware/issues/1362
=> Revert "framework/13-inch/12th-gen-intel: add hdmi audio fix"

README.md, dell/g3/3579/default.nix, flake.nix
Added profile for Dell G3 3579 laptop that enables fan sensors kernel drivers
=> Added profile for Dell G3 3579 laptop

README.md, flake.nix, hardkernel/odroid-h4/default.nix
- Add support for hardkernel ODROID H4
I decided to add only one module, it should work the same for the base, H4+ and H4 Ultra variants. There is precedent for this as the ODROID H3 module also does not differentiate between H3 and H3+.
=> hardkernel/odroid-h4: init

framework/13-inch/intel-core-ultra-series1/default.nix
Boot error message before patch:
```
$ journalctl | grep vpu
Feb 03 03:10:51 nixos kernel: intel_vpu 0000:00:0b.0: [drm] *ERROR* ivpu_fw_request(): Failed to request firmware: -2
Feb 03 03:10:51 nixos kernel: intel_vpu 0000:00:0b.0: [drm] ivpu_hw_power_down(): NPU not idle during power down
Feb 03 03:10:51 nixos kernel: intel_vpu 0000:00:0b.0: probe with driver intel_vpu failed with error -2
```
Fixed after patch:
```
$ journalctl | grep vpu
Feb 03 03:13:30 nixos kernel: intel_vpu 0000:00:0b.0: [drm] Firmware: intel/vpu/vpu_37xx_v0.0.bin, version: 20240221*MTL_CLIENT_SILICON-release*2101*ci_tag_ud202408_vpu_rc_20240221_2101*845c105994a
Feb 03 03:13:30 nixos kernel: [drm] Initialized intel_vpu 1.0.0 for 0000:00:0b.0 on minor 0
```
Source: …
=> framework/13-inch/intel-core-ultra-series1: fix intel_vpu firmware error -2

purism/librem/5r4/audio.nix, purism/librem/5r4/kernel.nix
the audio changes are a bit annoying but hopefully that can be removed once 25.05 is released
=> purism/librem/5r4: kernel: 6.6.29 -> 6.6.74, update pulseaudio options

README.md, dell/xps/15-9530/README.wiki, dell/xps/15-9530/default.nix, dell/xps/15-9530/nvidia/default.nix, flake.nix
Created this from original pr #881 and keep @bashfulrobot as main author.
This is my first contribution to any nix related project so happy to take feedback since i'm bit of a noob!
Thanks for an awsome flake!
=> Dell XPS 15 9530

common/gpu/nvidia/default.nix
https://github.com/NixOS/nixpkgs/pull/326369 has been merged.
Remove a line that has been marked as unneeded.
=> common/gpu/nvidia: remove a default value

dell/e7240/default.nix, framework/13-inch/intel-core-ultra-series1/default.nix
Add check for hardware.enableRedistributableFirmware as discussed in #1358
=> framework/13-inch/intel-core-ultra-series1: add check for hardware.enableRedistributableFirmware

dell/xps/13-9315/default.nix
Since a ~recent update, the Dell XPS 13-9315 integrated screen started to flicker.
This is apparently due to the Panel Self Refresh (PSR) feature of the screen.
This PR adds a kernelParams to disable PSR, which fixes the flickering.
=> dell/xps/13-9315: fix screen flickering

raspberry-pi/4/poe-hat.nix, raspberry-pi/4/poe-plus-hat.nix
Updating poe-hat and poe-plus-hat overlays to include PWM polarity value ([ref](https://github.com/raspberrypi/linux/commit/e951bdb8b1b93e288c0147a722a22017d63e3f17))
=> raspberry-pi-4: poe-hat: add PWM polarity value

README.md, aoostar/r1/n100/default.nix, flake.nix
Add definition for the Aoostar R1 NAS.
In order to get micro-code updates, to select the right driver for hardware transcoding on the integrated GPU, and serve as a place for further customization in the future. I left a note about the "super io" chip used in that computer.
=> Set Alder Lake support for the Aoostar R1 N100

README.md, flake.nix, radxa/README.md, radxa/rock-4c-plus/default.nix, radxa/rock-5b/default.nix, radxa/rock-pi-4/default.nix, radxa/rock-pi-e/default.nix, rockchip/default.nix, rockchip/rk3328/default.nix, rockchip/rk3399/default.nix, rockchip/rk3588/default.nix
* Add ROCK 5B, ROCK Pi E, and ROCK Pi 4 (U-Boot reports as ROCK Pi 4A) support
* Refactor Rockchip devices bootloader installation. All Rockchip U-Boot packages contain `u-boot.itb` and `idbloader.img`, and so far the installation offsets are the same across 3 different SoCs.
All 3 new devices and the existing ROCK 4C+ are tested.
=> Add rest of Radxa devices that alredy have U-Boot package in nixpkgs

README.md, flake.nix, gigabyte/b650/README.md, gigabyte/b650/b650-fix-suspend.nix, gigabyte/b650/default.nix
Fixing the long-unsolved issue with Gigabyte B650 series mainboards where the system is unable to suspend properly. The solution is adapted from https://bbs.archlinux.org/viewtopic.php?pid=2227023.
=> Fix Gigabyte B650 suspend issue

apple/t2/pkgs/linux-t2/latest.json
removes a now-redundant patch that fixes an upstream bug, which was included as part of 6.13.4. 
=> apple/t2: update patches for the latest kernel

README.md, common/cpu/intel/skylake/cpu-only.nix, common/cpu/intel/skylake/default.nix, common/gpu/intel/skylake/default.nix, dell/inspiron/7559/README.md, dell/inspiron/7559/default.nix, flake.nix
- Adds Skylake CPU/GPU config
- Verified support with `vainfo` and on Firefox + Chrome hardware acceleration
- Adds Inspiron 7559 entries
- Uses Nvidia Prime with offloading for support between the onboard and discrete GPU
- Notes on some optional configuration in the README
- Tested on fresh NixOS install using Flakes and Plasma DE
=> Add Dell Inspiron 7559 and corresponding Skylake architecture

README.md, flake.nix, tuxedo/infinitybook/default.nix, tuxedo/infinitybook/pro14/gen7/default.nix, tuxedo/infinitybook/pro14/gen9-intel/README.md, tuxedo/infinitybook/pro14/gen9-intel/default.nix
Commonized the existing TUXEDO InfinityBook configurations and add one for my new laptop :)
=> Add support for TUXEDO InfinityBook Pro Intel Gen9

pine64/rockpro64/README.md, pine64/rockpro64/console.nix, pine64/rockpro64/default.nix
- Added HDMI output configuration by enabling the console=tty0 kernel parameter to direct output to HDMI instead of serial.
- Included necessary kernel modules in the initial RAM disk (initrd):
- Added dwmac_rk module for network support.
- Added rockchipdrm for HDMI support.
=> pine64/rockpro64: HDMI output and Network in initrd

dell/xps/13-9350/default.nix
I don't have the Laptop yet but looking at the specs it's a Lunar Lake CPU. I don't see any harm in adding this.
<https://www.notebookcheck.net/Dell-XPS-13-9350-laptop-review-Intel-Lunar-Lake-is-the-perfect-fit.911314.0.html>
> Dell XPS 13 9350 laptop review: Intel Lunar Lake is the perfect fit
=> dell/xps/13-9350: use lunar-lake cpu config

gpd/win-max-2/2023/bmi260/package.nix
fix: https://github.com/NixOS/nixos-hardware/issues/1352
https://github.com/hhd-dev/bmi260/commit/2d764db2bd69f2922d7fad6cb162136e32f357a2
=> gpd-win-max-2-2023/bmi260: 1.0.0 -> 1.1.0

gigabyte/b550/README.md, gigabyte/b550/b550-fix-suspend.nix
@NireBryce (contributor of the original change): any chance you can test this on your B550, or at least compare the IDs in lspci and /proc/acpi/wakeup)? It *should* do the same thing (you should see GPP0 and GPP8 "disabled" in /proc/acpi/wakeup after rebooting with this applied, and suspend/wakeup should work) but in a way not prone to accidentally togging rather than disabling wakeups.
I've had it in my local config for a while (didn't realize nixos-hardware carried motherboard-specific fixes like this one), and I'm pretty sure I'm working around the same bug, but I can't be 100% sure the device IDs on your system match mine (would surprise me if they didn't, but given the BIOS seems to be buggy to begin with I'd prefer to verify that assumption...)
Instead of using systemd oneshot …
=> Simplify implementation of B550 suspend fix

apple/t2/pkgs/linux-t2/generic.nix, apple/t2/pkgs/linux-t2/latest.json, apple/t2/pkgs/linux-t2/stable.json
update apple-t2 kernel patches.
this includes a new touchpad driver which was tested and should feel smoother. users may need to re-set touchpad settings in their DE.
=> apple/t2: sync patches

apple/t2/default.nix, apple/t2/pkgs/brcm-firmware/default.nix, apple/t2/pkgs/brcm-firmware/fetchmacos.nix, apple/t2/pkgs/brcm-firmware/get-firmware-standalone.patch, apple/t2/pkgs/brcm-firmware/get-firmware.nix, apple/t2/pkgs/brcm-firmware/macrecovery.nix
Adds new option to configure the Wi-Fi and Bluetooth firmware for T2 Macs. This is done by creating a package `brcm-firmware` whose derivation fetches a macOS recovery image, mounts it, and then extracts the firmware.
Everything seems to be working on my machine.
=> apple/t2: add Wi-Fi and Bluetooth firmware option

lenovo/thinkpad/x13/yoga/default.nix
During setting up my Lenovo Thinkpad X13 Yoga with a Thinkpad Thunderbolt Dock, I discovered that my device failed to communicate with the dock, especially for the ethernet connection. By adding the ``services.hardware.bolt.enable = true`` configuration, my laptop now successfully connects to the ethernet connected to the Thunderbolt dock.
Happy to discuss this suggested change in more detail.
=> lenovo/thinkpad/x13-yoga: add thunderbolt support

framework/13-inch/common/default.nix, framework/16-inch/common/default.nix
It seems like the modprobe configuration is not guareded with the right condition -- matching with `pkgs.linux.version` doesn't reflect the kernel the user might have opted into.
With this change, `boot.kernelPackages = pkgs.linuxPackages_6_1;` will correctly set the modprobe configuration no matter what the default kernel nixpkgs ships.
Note: I have changed this option for both 13 and 16 inch models, however I have only tested it for the 13 inch model. 
=> framework: fix TRRS headphones modprobe

lenovo/thinkpad/x1/yoga/7th-gen/default.nix
The comment above the kernel version check is not relevant for the current nixos-unstable. We leave the check in place but make at least the comment less scary.
Fixes #1370. As discussed with @MayNiklas.
=> Make comment less intimidating (Lenovo X1 Yoga Gen 7)

README.md, common/cpu/intel/whiskey-lake/cpu-only.nix, common/cpu/intel/whiskey-lake/default.nix, common/gpu/intel/whiskey-lake/default.nix, flake.nix, lenovo/thinkpad/p43s/README.md, lenovo/thinkpad/p43s/default.nix
=> added lenovo thinkpad p43s

nxp/imx8mp-evk/bsp/imx8mp-atf.nix
Updated makeFlags as latest buildArmTrustedFirmware specifies CC and LD explicitly, which doesn't work well with the nxp imx8mp-evk platform.
=> [imx8mp-evk] fix firmware compilation issue

nxp/imx8mp-evk/bsp/imx8mp-atf.nix, nxp/imx8mp-evk/bsp/imx8mp-boot.nix, nxp/imx8mq-evk/bsp/imx8mq-atf.nix, nxp/imx8mq-evk/bsp/imx8mq-boot.nix
Fixes native build issue for iMX8MP-evk
Fixes cross and native build issue for iMX8MQ-evk
- Using package specific derivation instead of buildArmTrustedFirmware
=> Pr  imx8 atf build issues

README.md, flake.nix, lenovo/legion/16arh7h/README.md, lenovo/legion/16arh7h/hybrid/default.nix, lenovo/legion/16arh7h/igpu-only/default.nix
Added profiles for Lenovo Legion 5 Pro 16ARH7H.
Includes configuration for igpu only as well as nvidia hybrid (offload mode) 
=> Add Lenovo Legion 5 Pro 16arh7h

common/cpu/intel/comet-lake/default.nix, lenovo/thinkpad/e14/intel/default.nix
The E14 has a i5-10210U which is from comet lake.
see https://www.intel.com/content/www/us/en/products/sku/195436/intel-core-i510210u-processor-6m-cache-up-to-4-20-ghz/specifications.html
=> E14-intel: import intel comet lake

README.md, flake.nix, lenovo/thinkpad/x13s/README.md, lenovo/thinkpad/x13s/default.nix
Add support for the Lenovo X13s machine running on aarch64 architecture of the Snapdragon Elite X gen 3.
There are few issues:
- custom kernel (not sure where to upstream), should it be here or go directly to the nixpkgs
(the kernel could be reused for similar machines running on the aarch64 snapdragon and using UEFI)
- caching of the kernel as the build takes long time
- creation of install iso https://github.com/kuruczgy/x1e-nixos-config/pull/108
- support for DTB in the install ISO https://github.com/NixOS/nixpkgs/pull/396334
- hardcoded Wifi/BT MAC addresses
- BIOS/UEFI firmware update, have option to either [create update image](https://support.lenovo.com/us/en/downloads/ds556845-bios-update-utility-bootable-cd-for-windows-11-thinkpad-x13s-gen-1-type-21bx-21by) or use unofficialy …
=> lenovo-thinkpad-x13s: Add support for aarch64 system

README.md, flake.nix, lenovo/thinkpad/x1/2nd-gen/default.nix
The 2nd Gen might be a bit aged, but mine runs still very well. So far I was using the 7th gen module, but thought it might potentially be helpfull to actually pull Haswell optimizations.
Until I can check those boxes below I'll leave this as draft.
=> Lenovo X1 2nd Gen: init

asus/zephyrus/gu605my/default.nix, asus/zephyrus/shared/backlight.nix
=> Feature.asus zephyrus g16 gu605 my backlight and keyboard rules

hp/elitebook/830/g6/default.nix
The previous implementation was checking the kernel version through
`pkgs.linux`, which is only representative of the final system if
`boot.kernelPackages` is left as the default value of
`pkgs.linuxPackages`.
You can of course change this to other package sets, such as
`pkgs.linuxPackages_latest`. Instead, we now reference the kernel
through `config.boot.kernelPackages.kernel`.
=> hp/elitebook/830/g6: check kernel version through `config` instead of `pkgs`

lenovo/thinkpad/p14s/default.nix
The previous implementation was checking the kernel version through
`pkgs.linux`, which is only representative of the final system if
`boot.kernelPackages` is left as the default value of
`pkgs.linuxPackages`.
You can of course change this to other package sets, such as
`pkgs.linuxPackages_latest`. Instead, we now reference the kernel
through `config.boot.kernelPackages.kernel`.
=> lenovo/thinkpad/p14s: check kernel version through `config` instead of `pkgs`

lenovo/thinkpad/x13s/default.nix
The previous implementation was sourcing the kernel through `pkgs.linux`,
which is only representative of the final system if `boot.kernelPackages`
is left as the default value of `pkgs.linuxPackages`.
You can of course change this to other package sets, such as
`pkgs.linuxPackages_latest`. Instead, we now reference the kernel
through `config.boot.kernelPackages.kernel`.
=> lenovo/thinkpad/x13s: source kernel through `config` instead of `pkgs`

omen/14-fb0798ng/default.nix, omen/15-en0010ca/default.nix, omen/15-en1007sa/default.nix, omen/16-n0005ne/default.nix, omen/16-n0280nd/default.nix
The previous implementation was checking the kernel version through
`pkgs.linux`, which is only representative of the final system if
`boot.kernelPackages` is left as the default value of
`pkgs.linuxPackages`.
You can of course change this to other package sets, such as
`pkgs.linuxPackages_latest`. Instead, we now reference the kernel
through `config.boot.kernelPackages.kernel`.
=> omen/*: check kernel version through `config` instead of `pkgs`

README.md, flake.nix, framework/13-inch/amd-ai-300-series/README.md, framework/13-inch/amd-ai-300-series/default.nix
Add a module for the new Framework AMD AI 300 Series.  Largely this is a clone of the 7040 AMD series module.
=> Add Framework AMD AI 300 Series

README.md, flake.nix, gmktec/nucbox/g3-plus/default.nix
Product page:
<https://www.gmktec.com/products/nucbox-g3-plus-enhanced-performance-mini-pc-with-intel-n150-processor>
This profile just configures the Intel Twin Lake N150 CPU and integrated graphics for this mini-PC. fstrim is also enabled for the SSD. That's all this seemed to need to function properly. As is now expected from Intel NUC systems, it provides a solid "out-of-the-box" experience. No special quirks are apparent.
We import the Alder Lake modules since Twin Lake is just a refreshed version of the Alder Lake-N series. Re-using those seems to be fine for this purpose.
=> gmktec/nucbox/g3-plus: init

README.md, flake.nix, lenovo/thinkpad/x1/yoga/8th-gen/default.nix
Convertible laptop equipped with e.g. 13th Gen Intel Core i7-1365U × 12, 32 GiB RAM, and 512 MiB or 1 TiB SSD HDD.
Adds a configuration, which is practically identical to the [7th-gen model](https://github.com/NixOS/nixos-hardware/blob/master/lenovo/thinkpad/x1/yoga/7th-gen/default.nix).
@MayNiklas, would you mind to review?
1.) The model has a fingerprint reader integrated in the power button. I'm not sure whether this is already covered or I should to add [the related configuration](https://github.com/NixOS/nixos-hardware/blob/master/lenovo/thinkpad/default.nix#L10C5-L10C35) to this PR.
2.) My `hardware-configuration.nix`, which is derived from the one generated by the GUI installer, looks like this:
```nix
{ config, lib, modulesPath, ... }:
{
imports = [
(modulesPath + …
```
=> Add Lenovo ThinkPad X1 Yoga Gen 8

README.md, asus/zenbook/ux481/README.md, asus/zenbook/ux481/intelgpu/default.nix, asus/zenbook/ux481/nvidia/default.nix, asus/zenbook/ux481/shared.nix, flake.nix
Added support for the Asus Zenbook Duo 14 UX481. It contains a profile for only using Intel iGPU and one also enabling the Nvidia dGPU.
I have lib.mkForce dynamicboost off as it makes the dGPU not work.
I also added kernel parameters that are necessary for suspend to work, this is due to the nvme not booting up in time on resume for it to mount properly. This problem applied both with the original Intel Optane nvme, as well as the new Kingston nvme I use.
importing it via `<nixos-hardware>` or Flake input (I tested using flake input)
=> Add Asus Zenbook Duo 14 UX481

README.md, asus/rog-strix/g533zw/default.nix, flake.nix
Add support for Asus ROG Strix G533zw. The configuration is based on the asus-zephyrus-gu603h since they have essentially the same hardware. I also included asus/battery.nix support though this may not be necessary.
I ran the tests pointing the nixos-hardware URL to my fork, am currently using my nixos-hardware fork as an input and including the asus-rog-strix-g533zw package. Everything is working!
I also added the import to the flake.nix file and included an entry in the README.md!
- [ :heavy_check_mark:  ] Tested the changes in your own NixOS Configuration
- [ :heavy_check_mark:  ] Tested the changes end-to-end by using your fork of `nixos-hardware` and
=> add asus-rog-strix-g533zw

lenovo/thinkpad/x1/yoga/default.nix
Assuming that all (recent) Lenovo X1 Yoga models have an integrated fingerprint reader and allow updating the firmware, we can enable the two related services by default.
Ping for review @Mic92, @MayNiklas, @mschneiderwng
=> Enable fingerprint reader and FW update for Lenovo X1 Yoga models

lenovo/legion/15ich/default.nix
Updated CPU import for the Lenovo Legion Y530-15ICH to use the generation specific CPU rather than the generic import. 
=> lenovo/legion/15ich: Use Coffee Lake CPU

tuxedo/infinitybook/default.nix
As all Infinitybook models come equipped with Bluetooth, I think it's a good idea to enable it by default.
=> TUXEDO Infinitybook: Enable bluetooth by default

common/gpu/nvidia/prime.nix
This enables a boot option that switches off NVIDIA GPU. Allows for battery saving.
@moduon MT-9339
=> feat(nvidia-prime): automatic battery-saver specialisation

README.md, flake.nix, framework/12-inch/13th-gen-intel/README.md, framework/12-inch/13th-gen-intel/default.nix, framework/12-inch/common/default.nix
Add support for the new [Framework Laptop 12](https://frame.work/laptop12).
Pre-orders have opened but devices haven't started shipping yet.
=> framework: Add framework12

README.md, flake.nix, lenovo/ideapad/14imh9/README.md, lenovo/ideapad/14imh9/default.nix
Added the definition for `Lenovo Ideapad 5 Pro 14IMH9 / XiaoXin Pro 14IMH9 2024`. They are basically the same product but rebranded and sold in different regions.
As there were a lot of vendor specific changes, `README.md` does not document all of them. Comments in `default.nix` should be self-explanatory, though.
=> Add Lenovo Ideapad 5 Pro 14IMH9 / XiaoXin Pro 14IMH9 2024

framework/13-inch/common/audio.nix
Just a fix to a typo in the description of the hardware.framework.laptop13.audioEnhancement option.
=> fix typo in framework audio.nix

nxp/imx8mp-evk/bsp/imx8mp-boot.nix, nxp/imx8mq-evk/bsp/imx8mq-boot.nix
**Update correct hash for imx mkimage utility**
- Don't fetch dotGit directory.
- DotGit directory gets different object packs when it is pulled from different nixpkgs versions which causes Hash mismatch.
e.g. nixpkgs revs: 2631b0b7abcea6e640ce31cd78ea58910d31e650
and 2795c506fe8fb7b03c36ccb51f75b6df0ab2553f produces different hash due to differences in dotgit object packs.
- Patch Makefile not use git revision from .git.
=> Update correct hash for imx mkimage utility

README.md, flake.nix, lenovo/thinkpad/x1/13th-gen/default.nix
Added Lenovo Thinkpad X1 13th Gen (Lunar Lake).
=> Add Lenovo Thinkpad X1 13th Gen

raspberry-pi/4/default.nix, raspberry-pi/4/gpio.nix
Add an optional module via hardware.raspberry-pi."4".gpio.enable that allows lgpio and pgpiod to work.  Without this configuration, pigpiod won't start (it needs the `iomem=relaxed` kernel parameter), and lgpio won't work for users in the `gpio` group because the `/dev/gpiochip*` devices have the wrong permissions.
See also https://github.com/NixOS/nixpkgs/pull/352308
- [X ] Tested the changes in your own NixOS Configuration
- [ X] Tested the changes end-to-end by using your fork of `nixos-hardware` and
=> add optional config that makes lgpio and pigpio work

pine64/pinebook-pro/keyboard-updater/default.nix
This updates the changed name of libusb. Tested on my pinebook and it seems to worked for me.
=> Address libusb rename in pinebook configuration for issue #1488

README.md, flake.nix, lenovo/thinkpad/p14s/amd/gen5/default.nix
Added configuration for Lenovo ThinkPad P14s AMD Gen 5
=> Lenovo ThinkPad P14s AMD Gen 5: init

README.md, dell/precision/3490/default.nix, dell/precision/3490/intel/default.nix, dell/precision/3490/nvidia/default.nix, dell/precision/3490/shared.nix, flake.nix
This PR adds the 3490 variant without the nvidia GPU.
The `dell-precision-3490` output is now deprecated, and `*-nvidia` and `*-intel` output are created.
=> dell-precision-3490: add variant without nvidia GPU

README.md, flake.nix, xiaomi/redmibook/15-pro-2021/README.md, xiaomi/redmibook/15-pro-2021/default.nix
=> xiaomi/redmibook/15-pro-2021: init

lenovo/legion/16arh7h/hybrid/default.nix
Hybrid mode now includes amd video drivers for lenovo legion 16arh7h
=> Updated hybrid nvidia offload mode to include amd video drivers

framework/13-inch/amd-ai-300-series/default.nix
Tested suspend and hibernate working with this config:
```nix
{
disko.devices = {
disk = {
nvme0n1 = {
device = "/dev/nvme0n1";
type = "disk";
content = {
type = "gpt";
partitions = {
boot = {
priority = 1;
start = "34s";
end = "2047s";
type = "EF02"; # for grub MBR
};
ESP = {
priority = 2;
start = "2048s";
end = "2099199s";
type = "EF00";
content = {
type = "filesystem";
format = "vfat";
mountpoint = "/boot";
};
};
luks = {
priority = 3;
start = "2099200s";
type = "8309";
content = {
type = "luks";
name = "crypted-nvme0n1";
settings.allowDiscards = true;
content = {
type = "lvm_pv";
vg = "nvme0n1";
};
};
};
};
};
};
};
lvm_vg = {
nvme0n1 = {
type = "lvm_vg";
lvs = {
a_swap = {
size = "64GiB";
content = {
type = "swap";
};
};
z_persist = {
size = "100%FREE";
content = {
type = "zfs";
pool …
```
=> framework-amd-ai-300-series: bump kernel to latest for suspend support

framework/13-inch/amd-ai-300-series/default.nix
=> framework-amd-ai-300-series: mkDefault boot.kernelPackages

framework/12-inch/13th-gen-intel/default.nix
NixOS kernels don't have pinctrl_tigerlake built-in, we need to make sure it loads before soc_button_array. Adding it to the initrd ensures that.
=> framework/12-inch: Fix tabletmode 

flake.nix, framework/desktop/amd-ai-max-300-series/README.md, framework/desktop/amd-ai-max-300-series/default.nix
Initial support for Framework Desktop - AMD Ryzen AI MAX 300 Series.
=> framework: Add Framework Desktop

microsoft/surface/common/kernel/6.12/patches.nix, microsoft/surface/common/kernel/6.15/patches.nix
Due to [nixpkgs #431115](https://github.com/NixOS/nixpkgs/pull/431115) and [nixpkgs #432497](https://github.com/NixOS/nixpkgs/pull/432497), using `extraStructuredConfig` now throws an error rather then being silently ignored. This PR updates the kernel patches for the Microsoft surface kernels to use `structuredExtraConfig` instead, to correctly configure the kernel without any errors.
I'm currently running the fixed branch of my fork on my Surface 5.
=> Fix Typo Preventing Microsoft Surface Kernels from Building

framework/16-inch/common/default.nix
Framework 16 does not have a built-in headphone jack, this is not needed.
The kernel has also reverted the quick, so matching on a kernel version does nothing useful.
=> framework 16: Remove headset quirk

microsoft/surface/README.md
Docs update only. Provides useful information about potential userspace issues commonly caused by applying the patches.
I figured a docs PR would be conservative rather than modifying the derivations, since this is just one example of potential IPU6 issues.
=> microsoft/surface: update wireplumber docs

flake.nix
This PR simply adds an import of ideapad-s5-16iah8 which the dev probably forgot to add. Resolves #1588 
=> fix: add missing import of ideapad 16iah8

README.md, flake.nix, lenovo/thinkpad/t14/intel/default.nix, lenovo/thinkpad/t14/intel/gen6/default.nix
Adds support for Lenovo ThinkPad T14 Intel Gen 6 with Intel Core Ultra processors (Lunar Lake architecture).
- **CPU/GPU Support**: Uses  module for Intel Core Ultra 5/7 processors with Intel Arc integrated graphics
- **Kernel Requirements**: Ensures kernel 6.8+ for full Lunar Lake support  
- **Hardware Optimizations**: 
-  for ThinkPad brightness control
-  for touchpad click registration
- Disables  service for modern Intel power management
- **Module Structure**: Added both base Intel T14 profile and Gen 6 specific profile
- **Documentation**: Updated README.md table and flake.nix entries
- Intel Core Ultra 7 268V processor
- Intel Arc Graphics 130V/140V 
- All hardware functionality verified working
- Kernel 6.16.0 with xe driver loaded successfully
The kernel parameters and …
=> Add ThinkPad T14 Intel Gen 6 support

flake.lock
On a7600cef40e350c6f3fcb6eefb6f0d6b09c7d05e all the inputs on `flake.nix` were moved to `tests/flake.nix`, but `flake.lock` was not updated correctly, and a reference to `nixpkgs` still remains, producing this error upon evaluation when used as an input to my flake:
```
evaluating file '<nix/derivation-internal.nix>'
copying "/nix/store/xjzjf1f6nyg6yqxb6v5awf9hs14606yp-source" to the store...
evaluating file '/nix/store/xjzjf1f6nyg6yqxb6v5awf9hs14606yp-source/flake.nix'
evaluating file '/nix/store/xjzjf1f6nyg6yqxb6v5awf9hs14606yp-source/flake.nix'
warning: updating lock file '"/nix/store/xjzjf1f6nyg6yqxb6v5awf9hs14606yp-source/flake.lock"':
• Removed input 'nixpkgs'
error:… while updating the lock file of flake 'path:/nix/store/xjzjf1f6nyg6yqxb6v5awf9hs14606yp-source?lastModified=0&narHash …
```
=> Update flake.lock, dropping unused `nixpkgs` input

asus/fa507nv/default.nix
I personally own this laptop, I am running gnome and on sleep the graphics always corrupt without fail, this setting has been the only way to correct it.
Just adding power Management on the ASUS fa507nv for the reason above
Just adding power Management on the ASUS fa507nv for the reason above
=> Adding Power Management on Asus fa507nv

system76/gaze18/default.nix
- Add CPU module
- use services.xserver.videoDrivers instead initrd.kernelModules for Nvidia graphics
=> System76/gaze18: minor fixes

nxp/imx8mp-evk/bsp/imx8mp-atf.nix, nxp/imx8mp-evk/bsp/imx8mp-boot.nix, nxp/imx8mp-evk/bsp/imx8mp-firmware.nix, nxp/imx8mp-evk/bsp/imx8mp-linux.nix, nxp/imx8mp-evk/bsp/imx8mp-optee-os.nix, nxp/imx8mp-evk/bsp/imx8mp-uboot.nix
=> bsp update for imx8mp-evk

README.md, flake.nix, framework/16-inch/amd-ai-300-series/README.md, framework/16-inch/amd-ai-300-series/default.nix
=> Add Framework Laptop 16 AMD AI 300 Series

README.md, dell/precision/5570/README.md, dell/precision/5570/default.nix, flake.nix
Add support for Dell Precision 5570
=> Added Dell Precision 5570

fydetab/duo/default.nix
=> fydetab/duo: fix typo with enable option

fydetab/duo/README.md, fydetab/duo/config, fydetab/duo/default.nix, fydetab/duo/himax.nix
Fixes this error:
```
error: A definition for option `hardware.firmware' is not of type `list of package'. TypeError: Definition values:
- In `/nix/store/1jcq7nbm2bj68bpa85fblak3c87a917r-source/fydetab/duo': <derivation ap6275p-firmware-2023-11-05>
- In `/nix/store/1jcq7nbm2bj68bpa85fblak3c87a917r-source/fydetab/duo': <derivation mali-g610-firmware-2024-08-23>
- In `/nix/store/1jcq7nbm2bj68bpa85fblak3c87a917r-source/fydetab/duo': <derivation himax-firmware-2024-11-09>
```
Also fixes the himax firmware, forgot to get a hash. I've also changed the graphics section of the README to clarify things more.
=> fydetab/duo: fix hardware.firmware being applied

apple/macbook-air/6/default.nix
The BCM4360 wireless chipset is only supported in `broadcom-wl` (`broadcom_sta`) not in the `b43`/`bcma` kernel modules
https://wireless.docs.kernel.org/en/latest/en/users/drivers/b43/devices.html
https://wiki.debian.org/wl#Supported_Devices
=> MacBookAir6,x: fix wireless

README.md, flake.nix, linglong/nova-studio/README.md, linglong/nova-studio/default.nix
Adds support for [Linglong Nova Studio](https://www.firstarpc.com/).
=> linglong/nova-studio: init

README.md, flake.nix, panasonic/letsnote/cf-lx3/default.nix
=> panasonic: add Let's Note CF-LX3 configuration

README.md
While working on https://github.com/NixOS/nixos-hardware/pull/1535 I noticed there was a missing Dell entry, which got me looking for other missing entries. This adds all the other ones I found, as well as fixing up a couple typos in existing entries, and some table reformatting. 
This was done by just manually going through results from `for FILE in $(fd default.nix); do if \! rg $(dirname ${FILE}) README.md >/dev/null; then echo ${FILE} missing; fi; done | rg -v common` and seeing which results were legitimately missing
I think I caught all of the real missing ones. While reviewing the raw table I decided to properly align most columns so that it's easier to edit/read.
Can do `git diff -w` to see the real non-alignment changes, which to summarize are:
Added:
- Kobol Helios 4
- Lenovo …
=> Add missing README entries and re-align columns
