NixOS/nixos-hardware

- audio-gd/compass2.nix
http://www.audio-gd.com/Pro/Headphoneamp/Compass%202/Compass2EN.htm
> audio-gd/compass2: init

- dell/xps-15-9550.nix
- dell/xps-15-9550.wiki
Here is a dump of everything I know about getting my laptop running. It's highly unstructured however---and I was the one who emailed the list warning against precisely this lack of structure. So in the interest of not being a hypocrite :), let me know the best we to organize this.
I imagine that the 13" variant Dell xps-13-9350 would most/share all of these settings, there is also a question of how that should be handled.
> WIP: Dell XPS 15 9550

- lenovo/x140e.nix
This is my laptop configuration for my x140e. I bet there's more that could be incorporated from the other Lenovo configs (TLP power management, harddisk fall locking), but I haven't tested them on my machine.
> Add Lenovo x140e laptop

- .gitignore
- apple/macbook-pro-10-1.nix
- apple/macbook-pro-10-1.wiki
- dell/xps-15-9550.nix
- dell/xps-15-9550.wiki
- `.gitignore` so I don't commit junk
- Rename to avoid deprecation on Dell XPS, my personal computer.
> Apple MacBook Pro 10,1 + misc fixes

- README.org
- lenovo/thinkpad/x250/default.nix
Basically a meta profile that combines thinkpad + intel.
> add lenovo x250

- .travis.yml
Perhaps it's not required. I'd like to check.
> travis: drop sudo

- dell/xps/15-9550/README.wiki
How I fixed my XPS15 after it being dead for two months
> Add a note about rcu_sched problems

- lenovo/thinkpad/cpu-throttling-bug.nix
- lenovo/thinkpad/t480s/default.nix
- lenovo/thinkpad/x1/6th-gen/default.nix
The T480s also suffers from this bug.
> T480s: use CPU throttling fix too

- CONTRIBUTING.md
> [rebased from #67] Suggestions for CONTRIBUTING

- README.md
- lenovo/thinkpad/t430/default.nix
Copied everything from t440p, added a fix for the brightness keys
> thinkpad: introduce t430

- CODEOWNERS
- README.md
- dell/xps/13-9380/README.wiki
- dell/xps/13-9380/default.nix
- release.nix
This is pretty much a copy of XPS 9370, without kaby-laky and the throttle bug. I was getting lockups with the kaby-laky changes and the throttle bug did not seem to have an impact either way.
> dell/xps/13-9380: init

- README.md
> README: Add Dell XPS 13 9360 profile

- README.md
- dell/e7240/README.md
- dell/e7240/default.nix
- release.nix
> Add Dell E7240 Profile

- dell/xps/13-9360/default.nix
- dell/xps/13-9370/default.nix
- dell/xps/13-9380/default.nix
- dell/xps/15-9550/default.nix
This may prevent the swelling battery issue.
> dell/xps: enable thermald service

- README.md
- dell/xps/13-7390/README.wiki
- dell/xps/13-7390/default.nix
Initial profile for Dell XPS-7390, late 2019.
> Add Dell XPS-7390 Profile

- README.md
- lenovo/thinkpad/t420/default.nix
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/nixos/nixos-hardware/129)
> Add Lenovo ThinkPad T420 profile

- dell/xps/15-7590/README.wiki
- dell/xps/15-7590/default.nix
Still working out bugs with Graphics, but the Wifi only working with 5.1 is an issue that will have to be readdressed.
> Initial 15-7590

- README.md
- lenovo/thinkpad/e495/default.nix
Added the hardware profile for the Thinkpad E495
To fix these issues:
https://github.com/NixOS/nixpkgs/issues/69289
https://github.com/NixOS/nixpkgs/issues/42788
> Added profile for issues 69289

- lenovo/thinkpad/e495/default.nix
> thinkpad/e495: fix evaluation

- dell/xps/15-7590/README.wiki
- dell/xps/15-7590/default.nix
Also don't set nixpkgs.pkgs. Instead just add an overlay.
> xps/15-7590: don't enable unfree firmware by default

- lenovo/thinkpad/t460s/default.nix
See there links for details:
https://github.com/NixOS/nixos-hardware/pull/134#pullrequestreview-336181593
https://github.com/NixOS/nixos-hardware/pull/134#discussion_r361146814
/cc @Mic92
> Improve support for t460s

- README.md
- lenovo/thinkpad/x1/7th-gen/audio.nix
- lenovo/thinkpad/x1/7th-gen/default.nix
Not sure how this fits with the "opinionated" bit in CONTRIBUTING.md, but I see similar stuff in lenovo/thinkpad/t490 so maybe it's OK?
This only works with unstable for now, until SOF is in stable (https://github.com/NixOS/nixpkgs/pull/87988).
> lenovo/thinkpad/x1/7th-gen: init

- README.md
> README.md: document fetchgit

- README.md
- dell/precision/5530/default.nix
- flake.nix
reopening of #187 because I messed up with git somehow
> add dell precision 5530

- README.md
- lenovo/thinkpad/x220/default.nix
Tested locally, I'm posting from a Thinkpad x220 booted with the patch applied.
> Thinkpad x220 has a Sandy Bridge CPU

- README.md
- flake.nix
- lenovo/thinkpad/t14s/default.nix
Copied from t495.
Replaces https://github.com/NixOS/nixos-hardware/pull/198
> t14s: init

- README.md
- dell/xps/15-9550/README.wiki
- dell/xps/15-9550/nvidia/default.nix
- flake.nix
I've been using this (but hand-rolled, in github.com/Ericson2314/nixos-configuration/) for quite some time.
> Copy NVidia 9500 NVidia settings for 9550

- README.md
- flake.nix
- gpd/micropc/default.nix
Add a configuration for the [GPD MicroPC](https://www.gpd.hk/gpdmicropc)
> add gpd-micropc

- README.md
- flake.nix
- mnt/reform2-nitrogen8m/default.nix
- mnt/reform2-nitrogen8m/kernel/default.nix
- mnt/reform2-nitrogen8m/kernel/linux-5.7.nix
- mnt/reform2-nitrogen8m/uboot/default.nix
- mnt/reform2-nitrogen8m/uboot/env_vars.patch
- mnt/reform2-nitrogen8m/uboot/shell-syntax.patch
An aarch64 laptop. If this is merged then I will create a flake that imports this module to build an installer.
https://www.crowdsupply.com/mnt/reform
https://mntre.com/
> Add mnt-reform2-nitrogen8m

- common/pc/laptop/default.nix
fixes https://github.com/NixOS/nixos-hardware/issues/268
> pc/laptop: fix evaluation on 20.09

- README.md
- flake.nix
- lenovo/thinkpad/p1/3th-gen/audio.nix
- lenovo/thinkpad/p1/3th-gen/default.nix
- lenovo/thinkpad/p1/3th-gen/nvidia.nix
- lenovo/thinkpad/p1/default.nix
Add lenovo-thinkpad-p1 support
> Add lenovo-thinkpad-p1

- dell/precision/5530/default.nix
Fix flicker with a workaround found on the arch wiki. I have been testing it for a month.
Also remove one kernel parameter from my previous PR which is not required (and actually has nothing to do with nouveau). I took it from the issue I linked in comment without thinking very long...
> Dell Precision 5530: fix screen flicker

- lenovo/thinkpad/p1/default.nix
system76 is fixed here: https://github.com/NixOS/nixpkgs/pull/128198
> p1: remove nvidia module again

- lenovo/thinkpad/l13/default.nix
found while reviewing: https://github.com/NixOS/nixos-hardware/pull/283
> thinkpad-l13: add ssd

- README.md
A lot of links where broken.
Inlining links for all profiles makes it easier to review and contribute.
> README: inline links

- README.md
- asus/zephyrus/ga401/default.nix
- flake.nix
> Add asus rog zephyrus g14 ga401

- README.md
- flake.nix
- lenovo/thinkpad/e14/amd/default.nix
- lenovo/thinkpad/e14/default.nix
- lenovo/thinkpad/e14/intel/default.nix
Init profiles for the Lenovo ThinkPad E14.
This is mostly based on the L14 and not completely ready yet, it already seems to work quite well, but I haven't tested all details yet. I put it here for feedback and keeping track of the progress.
Disclosure: I only have an E14 with AMD, not with Intel.
> Lenovo ThinkPad E14

- .github/workflows/test.yml
- README.md
- dell/poweredge/README.md
- dell/poweredge/r7515/default.nix
- flake.nix
https://www.dell.com/en-us/work/shop/productdetailstxn/poweredge-r7515#techspecs_section
> add dell poweredge r7515

- README.md
- dell/inspiron/5509/README.md
- dell/inspiron/5509/README.wiki
- dell/inspiron/5509/default.nix
- flake.nix
> Add Dell Inspiron 5509

- README.md
- flake.nix
- supermicro/m11sdv-8c-ln4f/README.md
- supermicro/m11sdv-8c-ln4f/default.nix
Tested this on my Supermicro M11SDV-8C-LN4F.
> add Supermicro M11SDV-8C-LN4F.

- README.md
- dell/inspiron/5515/README.md
- dell/inspiron/5515/default.nix
- dell/inspiron/5515/fix_touchpad.sh
- flake.nix
I have been testing this for about a month.
> add dell inspiron-5515

- README.md
- dell/xps/17-9710/README.wiki
- dell/xps/17-9710/intel/README.wiki
- dell/xps/17-9710/intel/default.nix
- flake.nix
Mostly just to share the fix for non-working sound
Tested with Kernel 5.15.12 on the non-nvidia xps17
> add xps 17 9710

- README.md
- flake.nix
- framework/default.nix
- Enable deep sleep
- Use kernel that's 5.12 or latest
- Enable fingerprint scanner
- HiDPI
closes #323
> feat(framework): Add initial support

- asus/zephyrus/ga503/default.nix
Signed-off-by: Mark Sagi-Kazar <mark.sagikazar@gmail.com>
> fix: asus zephyrus g15 mute button

- CONTRIBUTING.md
- README.md
- dell/xps/17-9700/README.wiki
- dell/xps/17-9700/common.nix
- dell/xps/17-9700/intel/default.nix
- dell/xps/17-9700/nvidia/default.nix
- flake.nix
Fixes https://github.com/NixOS/nixos-hardware/issues/290
See https://github.com/NixOS/nixos-hardware/pull/291
> Add Dell XPS 17 9700

- framework/default.nix
As in the below forum post, this is not perhaps the most ideal solution
to the problem, but it is the simplest.
https://community.frame.work/t/headset-microphone-on-linux/12387/3
> framework: Fix TRRS headphones missing a mic

- framework/default.nix
https://community.frame.work/t/headphone-jack-intermittent-noise/5246/55
> framework: Fix headphone noise when on powersave

- lenovo/thinkpad/t14s/amd/gen1/default.nix
> Fix Wifi for Lenovo Thinkpad T14s Gen1

- README.md
- flake.nix
- lenovo/thinkpad/t590/default.nix
Copied from T550 and T490 config.
Omit the pulseaudio profile from T490 config for now.
> added lenovo thinkpad T590

- README.md
- flake.nix
- omen/en00015p/default.nix
Added support for my personal laptop. Did all the steps and it seems ok.
> Add support for Omen en00015p laptop

- README.md
- flake.nix
- lenovo/thinkpad/p16s/amd/gen1/default.nix
I'm not a NixOS specialist, so I don't know if this enough but at least for me it works.
> Add lenovo/thinkpad/p16s/amd/gen1

- framework/12th-gen-intel/default.nix
Fixes #466 until it's fixed in kernel or firmware.
> framework-12th-gen-intel: workaround iGPU hangs

- starfive/visionfive/v1/README.md
> starfive/visionfive/v1: Fix README indentation

- README.md
- flake.nix
- lenovo/thinkpad/x1/10th-gen/default.nix
> Adds Lenovo Thinkpad X1 10th-gen

- kobol/helios4/overlay.nix
> kobol/helios4: update kernel patches

- README.md
- dell/latitude/3340/default.nix
- flake.nix
> Latitude 3340: init

- README.md
- dell/xps/13-9300/README.wiki
- dell/xps/13-9300/default.nix
- dell/xps/sleep-resume/bluetooth/default.nix
- dell/xps/sleep-resume/i2c-designware/default.nix
- flake.nix
Config settings for Dell XPS 13 / 9300
> Config settings for Dell XPS 13 / 9300

- asus/zephyrus/ga402/default.nix
> asus-zephyrus-ga402: fix mic mute button

- tests/run.py
> fix evaluation of rpi4

- README.md
- flake.nix
- lenovo/thinkpad/t520/default.nix
Borrow `t420`'s config since the machines only mainly differ in their screen sizes
> lenovo/thinkpad/t520: create

- asus/zephyrus/ga401/default.nix
Improve the configuration of asus ga401
> Improve the configuration of asus ga401

- framework/12th-gen-intel/default.nix
- framework/default.nix
> drop hidpi comment

- README.md
- dell/precision/3541/default.nix
- dell/precision/3541/intel/default.nix
- flake.nix
Support for Dell Precision 3541
Issue: #614 
> add dell precision 3541

- README.md
- dell/xps/15-9520/README.wiki
- dell/xps/15-9520/default.nix
- dell/xps/15-9520/nvidia/default.nix
- flake.nix
> Add config for Dell XPS 15 9520

- README.md
- flake.nix
- lenovo/thinkpad/x390/default.nix
Added Lenovo Thinkpad X390 model
- [ x ] Tested the changes in your own NixOS Configuration
> Added Lenovo Thinkpad X390

- README.md
- flake.nix
- focus/m2/gen1/default.nix
Add focus m2 gen1
```
❯  ./tests/run.py '<nixos-hardware/focus/m2/gen1>'                                                                                                                                                                                                     
OK <nixos-hardware/focus/m2/gen1>
```
> feat: Add focus m2 gen1

- starfive/visionfive/v2/uboot.nix
> starfive visionfive2: u-boot: update to SDK version v3.0.4

- framework/12th-gen-intel/default.nix
Someone figured out a reliable workaround to make the brightness and airplane mode keys on the Framework 12th gen work. This is that change.
> Framework 12th gen: add keys workaround

- README.md
- dell/inspiron/14-5420/README.md
- dell/inspiron/14-5420/default.nix
- flake.nix
> inspiron 14 5420: initial

- purism/librem/5r4/README.md
- purism/librem/5r4/default.nix
- purism/librem/5r4/kernel/6.4.14.nix
- purism/librem/5r4/kernel/default.nix
- purism/librem/5r4/u-boot/default.nix
> purism librem5r4: linux: 6.4.5-librem5 -> 6.4.14-librem5, firmware-imx: 8.15 -> 8.20

- starfive/visionfive/v2/uboot.nix
> starfive visionfive2: update u-boot to SDK version v3.6.1

- pine64/star64/README.md
- pine64/star64/firmware.nix
star64: add mmc firmware updater
And make the sd one actually write to the sd
> star64: add mmc firmware updater

- .github/workflows/test.yml
> only trigger ci on master branch and pull requests

- CODEOWNERS
Added myself to the codeowners file. If anyone else wants to hop on this as well, feel free! Just hoping to get notifications, so I can review the code.
> chore: Add @emiller88 to CODEOWNERS for framework

- pine64/star64/linux-5.15.nix
> star64: linux: 5.15.128 -> 5.15.131

- starfive/visionfive/v2/uboot.nix
> starfive visionfive2: update u-boot to SDK version v3.7.5

- raspberry-pi/4/default.nix
- raspberry-pi/4/digi-amp-plus.nix
> raspberrypi."4": add DigiAMP+ overlay

- dell/xps/15-9510/default.nix
- dell/xps/15-9510/nvidia/default.nix
Overall changes are planned to merge some configurations into Nvidia module and boosting Wireless Card connection and stability.
> Add OpenGL configurations and WiFi tunning

- starfive/visionfive/v2/uboot.nix
> starfive visionfive2: update u-boot to SDK version v3.8.2

- dell/xps/15-9510/nvidia/default.nix
> misc: Update nvidia settings

- tests/pyproject.toml
- tests/run.py
> Tests: add mypy / ruff checks

- apple/t2/default.nix
- apple/t2/pkgs/linux-t2.nix
- tests/build-profile.nix
- tests/run.py
> speed up ci using nix-eval-jobs

- dell/xps/13-9310/default.nix
> Update config for xps-13-9010

- starfive/visionfive/v2/uboot.nix
> starfive visionfive2: update u-boot to SDK version v5.10.3

- README.md
- flake.nix
- tuxedo/infinitybook/pro14/gen7/README.md
- tuxedo/infinitybook/pro14/gen7/default.nix
> Add TUXEDO InfinityBook Pro 14 - Gen7 config

- README.md
- flake.nix
- hp/elitebook/845/g8/default.nix
Added configuration for HP EliteBook 845 G8
> Added configuration for HP EliteBook 845 G8

- dell/xps/13-7390/README.wiki
- dell/xps/13-7390/default.nix
> Add fwupd to Dell XPS 13 7390 config

- README.md
- flake.nix
- lenovo/yoga/7/slim/gen8/default.nix
> Add support for Yoga Slim 7 Gen8

- starfive/visionfive/v2/uboot.nix
> starfive visionfive2: update u-boot to 2024.01

- microsoft/surface/common/kernel/linux-6.6.x/default.nix
* surface: linux 6.6.10 -> 6.6.13
Cc: @Cryolitia @roukydesbois
> surface: linux 6.6.10 -> 6.6.13

- microchip/README.md
Correct system updated in platform README.
No testing required.
> microchip icicle-kit README update

- README.md
- dell/xps/15-9570/README.wiki
- dell/xps/15-9570/default.nix
- dell/xps/15-9570/intel/default.nix
- dell/xps/15-9570/nvidia/default.nix
- dell/xps/15-9570/xps-common.nix
- flake.nix
Adding configuration for Dell XPS 15 9570.
> dell-xps-15-9570: init

- friendlyarm/nanopc-t4/README.md
> link offical wiki page instead of unoffical

- hp/elitebook/2560p/network.nix
> hp elitebook: fix eval

- README.md
- flake.nix
- lenovo/thinkpad/l480/default.nix
> lenovo/thinkpad/l480: init

- README.md
- flake.nix
- omen/14-fb0798ng/README.md
- omen/14-fb0798ng/default.nix
I bought this laptop a few days ago and added the features similar to the other omen laptops.
I can game and use blender with these changes and it accepts the nvidia gpu or the intel gpu. 
> omen/14-fb0798ng: init

- starfive/visionfive/v2/default.nix
- starfive/visionfive/v2/linux-6.6.nix
Reverts NixOS/nixos-hardware#958
> Revert "starfive visionfive2: use mainline kernel"

- framework/README.md
Wanted to update my Framework's firmware, but ran into some problems. Wrote it down so it can help others.
> framework: Better firmware update instructions and troubleshooting

- README.md
> link to matrix room

- .github/workflows/test.yml
- apple/macbook-pro/10-1/default.nix
- apple/macmini/4/default.nix
- asus/zephyrus/ga402x/amdgpu/default.nix
- common/gpu/24.05-compat.nix
- common/gpu/amd/default.nix
- common/gpu/intel/default.nix
- common/gpu/nvidia/default.nix
- dell/precision/7520/default.nix
- gpd/pocket-3/default.nix
- lenovo/thinkpad/p1/3th-gen/nvidia.nix
- lenovo/thinkpad/p51/default.nix
- lenovo/thinkpad/p52/default.nix
- lenovo/yoga/6/13ALC6/default.nix
- lenovo/yoga/7/14ARH7/amdgpu/default.nix
- tests/run.py
> Fix and test 24.05 evaluation

- .github/workflows/test.yml
- .mergify.yml
> add new tests to mergify configuration

- CODEOWNERS
Add codeowners for reviews in Tuxedo Pulse Laptops.
> feat: Update CODEOWNERS for Tuxedo Pulse Laptops

- README.md
- dell/optiplex/3050/default.nix
- flake.nix
Basic support for Dell Optiplex 3050
> Dell Optiplex 3050: init

- README.md
- asus/rog-strix/g713ie/default.nix
- flake.nix
Set GPU pins for asus rog-strix g713ie
> asus-rog-strix-g713ie: init

- README.md
- flake.nix
- lenovo/ideapad/15ach6/README.md
- lenovo/ideapad/15ach6/default.nix
Added configuration for Lenovo IdeaPad Gaming 3 15ach6, used it for a month or so on my system and decided to add it to this repository. This is my first time making a pull request, so please let me there is something wrong with my request.
- Added configuration to the appropriate directory.
- [ x ] Updated `flake.nix`
- [ x ] Updated `README.md`
- [ x ] Tested the changes in your own NixOS Configuration
I also ran the test script as described in CONTRIBUTING.md
> Added configuration for Lenovo IdeaPad Gaming 3 15ach6

- .github/workflows/test.yml
- .mergify.yml
- apple/imac/18-2/default.nix
- kobol/helios4/default.nix
- tests/build-profile.nix
- tests/flake.lock
- tests/flake.nix
- tests/run.py
> Fix ci and make it reproducible

- .mergify.yml
> mergify: merge in batches of 5

- dell/latitude/5490/README.md
- dell/latitude/5490/default.nix
Add Dell Latitude 5490, and it's workarounds.
> Add Dell Latitude 5490

- README.md
- apple/imac/14-2/README.md
- apple/imac/14-2/default.nix
- flake.nix
This PR requires https://github.com/NixOS/nixpkgs/pull/337948 to work correctly.
> Apple iMac 14,2: init

- asus/fa507rm/default.nix
- asus/rog-strix/g513im/default.nix
- asus/rog-strix/g713ie/default.nix
- asus/rog-strix/g733qs/default.nix
- asus/zephyrus/ga401/default.nix
- asus/zephyrus/ga402x/nvidia/default.nix
- asus/zephyrus/ga502/default.nix
- asus/zephyrus/ga503/default.nix
- asus/zephyrus/gu603h/default.nix
To fix build on latest nixpkgs.
Makes progress on #1100 
> Asus: Add Nvidia architectures

- lenovo/legion/16ach6h/hybrid/default.nix
> lenovo-legion-16ach6h: Add nvidia architecture

- asus/zephyrus/ga402x/shared.nix
This allows a user to disable the `power/wakeup` on the ASUS ITE 8245 Device Vendor `0b05`, Model `193b`.
This device tends to send a power "wakeup" immediately after a Suspend, meaning the Suspend  is resumed before it can actually suspend.
This is set to disable the wakeup, by default.
> Disable USB wakeup on the ASUS ITE 8295 Device on Asus Zephyrus GA402X laptop

- README.md
- flake.nix
- hp/laptop/14s-dq2024nf/default.nix
I added a new profile for HP Laptop 14s dq2024nf
importing it via Flake input
> Add new profile for HP Laptop 14s dq2024nf

- README.md
- dell/xps/13-9315/README.wiki
- dell/xps/13-9315/default.nix
- flake.nix
Added Dell XPS 9315
I've been using NixOS on this laptop for a while now, so here a small (non opinionated) config. Beside the camera and microphone (ipu6 crappy drivers), everything should work well, I'll contribute my findings/fixes in the future.
> add dell xps 9315

- apple/t2/default.nix
uses `mkMerge` to separate configuration options in the `apple/t2` module, and adds an option to disable `tiny-dfr`
`tiny-dfr` is still enabled by default to not cause issues with existing setups that rely on it
> apple/t2: add tiny-dfr option

- hp/laptop/14s-dq2024nf/default.nix
Enabled thermald, the temperature management daemon.
> Update profile for HP Laptop 14s dq2024nf

- README.md
- lenovo/legion/16irx9h/default.nix
Same as https://github.com/NixOS/nixos-hardware/pull/1227 but rebased
> Adding a sound speaker fix. Issue #1039

- README.md
- flake.nix
- framework/13-inch/intel-core-ultra-series1/README.md
- framework/13-inch/intel-core-ultra-series1/default.nix
Just picking up where #988 left off. Been running that branch for 2 weeks or so, and haven't noticed any issues.
> framework: Add Intel Core Ultra Series 1

- common/cpu/intel/coffee-lake/cpu-only.nix
- common/cpu/intel/coffee-lake/default.nix
- common/gpu/intel/coffee-lake/default.nix
Added support For Intel CoffeeLake cpu and gpu
> 「✨」 feat(Intel CoffeeLake): Added support

- gigabyte/b650/README.md
There is no fix AFAIK, but maybe this information is useful nonetheless.
> Add information on Gigabyte B650M Aorus Elite AX

- dell/precision/5530/default.nix
Added Nvidia GPU support with prime, fwupd and thermald (also the Intel coffee lake config)
> feat(Dell Precision 5530): Added Nvidia support and some other feature

- microsoft/surface/common/kernel/linux-surface/default.nix
> surface: linux 6.12.4 -> 6.12.6

- microsoft/surface/common/kernel/linux-surface/default.nix
> surface: linux 6.12.6 -> 6.12.7

- microsoft/surface/common/kernel/linux-surface/default.nix
- microsoft/surface/common/repos.nix
> surface: linux 6.12.7 -> 6.12.8

- README.md
> Oversight in the readme

- microsoft/surface/common/kernel/linux-surface/default.nix
> surface: linux 6.12.8 -> 6.12.9

- README.md
- flake.nix
- omen/15-ce002ns/README.md
- omen/15-ce002ns/default.nix
Testing has been limited to a headless server through SSH, however.
> omen/15-ce002ns: Init

- microsoft/surface/common/kernel/linux-surface/default.nix
> surface: linux 6.12.9 -> 6.12.11

- README.md
- flake.nix
- lenovo/thinkpad/t490s/default.nix
Boilerplate config for Lenovo ThinkPad T490s.
> Lenovo ThinkPad T490s

- README.md
- dell/inspiron/3442/README.md
- dell/inspiron/3442/default.nix
Added Config for **Dell Inspiron 3442** focusing on graphics support, firmware updates, thermal management, and wireless connectivity.
> Dell Inspiron 3442

- microsoft/surface/common/kernel/linux-surface/default.nix
> surface: linux 6.12.11 -> 6.12.12

- microsoft/surface/common/kernel/linux-surface/default.nix
> surface: linux 6.12.12 -> 6.12.14

- apple/t2/pkgs/linux-t2/latest.json
- apple/t2/pkgs/linux-t2/stable.json
Update patches to match the ones accepted upstream.
Tested working, no extra issues found.
> apple/t2: update patches

- README.md
- flake.nix
- lenovo/thinkpad/e15/README.md
- lenovo/thinkpad/e15/default.nix
- lenovo/thinkpad/e15/intel/default.nix
Adds Lenovo Thinkpad e15 Intel
> lenovo/thinkpad/e15/intel: init

- apple/t2/default.nix
silence warning for nixos-unstable users by selectively updating the option for unstable users.
> apple/t2: migrate renamed option

- README.md
- flake.nix
- lenovo/thinkpad/p14s/intel/gen5/default.nix
Added config for Lenovo Thinkpad P14s Gen 5 Intel. 
> Add Lenovo Thinkpad P14s Gen 5 Intel

- README.md
- flake.nix
- lenovo/yoga/7/14ILL10/README.md
- lenovo/yoga/7/14ILL10/default.nix
Adds simple lenovo/yoga/7/14ILL10
> lenovo/yoga/7/14ILL10: init

- CONTRIBUTING.md
- common/gpu/nvidia/fermi/default.nix
- dell/xps/15-9530/nvidia/default.nix
- lenovo/ideacentre/k330/default.nix
- tests/build-profile.nix
- tests/flake.lock
- tests/flake.nix
> tests: Nixpkgs update

- README.md
- flake.nix
- lenovo/legion/16iah7h/default.nix
Add 16iah7h
- [✔] Tested the changes in your own NixOS Configuration
- [✔] Tested the changes end-to-end by using your fork of `nixos-hardware` and
> Add 16iah7h

- dell/inspiron/3442/default.nix
> removed explicit gpu mention as it's included in cpu profile

- README.md
> add community meetings to CONTRIBUTING.md

- README.md
I assume this is the intended link
> README: fix team url

- flake.nix
fixes https://github.com/NixOS/nixos-hardware/issues/1531
> added inspiron 3442 to the flake

- microsoft/surface/common/default.nix
> surface: linux 6.15.3 -> 6.15.6

- fydetab/duo/u-boot.nix
> Fix fydetab duo eval

- README.md
- flake.nix
- lenovo/thinkpad/p14s/intel/gen2/README
- lenovo/thinkpad/p14s/intel/gen2/default.nix
> Lenovo thinkpad p14s intel gen2
